import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import nodemailer from "npm:nodemailer@7";

const H={"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*","access-control-allow-headers":"authorization, apikey, content-type, x-client-info","access-control-allow-methods":"POST, OPTIONS"};
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
function env(){const url=Deno.env.get("SUPABASE_URL")!;const pubs=Deno.env.get("SUPABASE_PUBLISHABLE_KEYS");const secs=Deno.env.get("SUPABASE_SECRET_KEYS");const pub=pubs?JSON.parse(pubs)?.default:Deno.env.get("SUPABASE_ANON_KEY");const secret=secs?JSON.parse(secs)?.default:Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!pub||!secret)throw new Error("Backend configuration missing");return{url,pub,secret}}
function admin(){const{url,secret}=env();return createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}})}type DB=ReturnType<typeof admin>;
async function actor(req:Request){const h=req.headers.get("authorization")||"",token=h.toLowerCase().startsWith("bearer ")?h.slice(7).trim():"";if(!token)return null;const{url,pub}=env();const scoped=createClient(url,pub,{auth:{persistSession:false,autoRefreshToken:false}});const{data,error}=await scoped.auth.getUser(token);if(error||!data.user)return null;const owner=typeof data.user.app_metadata?.workspace_owner_id==="string"?data.user.app_metadata.workspace_owner_id.trim():"";return{id:owner||data.user.id,token}}
function firstName(v:string|null|undefined){return String(v||"").trim().split(/\s+/)[0]||""}
function esc(v:string){return String(v||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;")}
function attr(v:string){return esc(v).replace(/'/g,"&#39;")}
function liveTimeline(page:any){const t=page?.timeline_v3;return Boolean(page?.id&&page?.is_public&&["ready","sent"].includes(String(page?.status||""))&&t&&Number(t.version)===3&&Array.isArray(t.tracks)&&t.tracks.length>0)}
function loomReady(page:any){return liveTimeline(page)||Boolean(page?.rendered_video_url&&page?.rendered_at)}
function lockedTemplate(lead:any){return String(lead?.video_template_key||(lead?.customer_type==="private"?"pv-privat":"energiekosten"))}
function tracked(base:string,token:string,url:string){return `${base}/api/t/c/${token}?url=${encodeURIComponent(url)}`}
function trackHtml(text:string,base:string,token:string,page:any){const videoUrl=page?.slug?`${base}/v/${page.slug}`:"";const videoHref=videoUrl?tracked(base,token,videoUrl):"";const thumb=String(page?.thumbnail_url||page?.website_capture_url||"");let linked=esc(text).replace(/https?:\/\/[^\s&lt;&gt;]+/g,(url)=>`<a href="${tracked(base,token,url)}" style="color:#0a5bd7;text-decoration:underline">${url}</a>`).replace(/\n/g,"<br>");if(videoUrl&&videoHref){const escapedUrl=esc(videoUrl);const linkedUrl=`<a href="${tracked(base,token,videoUrl)}" style="color:#0a5bd7;text-decoration:underline">${videoUrl}</a>`;const card=`<div style="margin:18px 0 20px;max-width:560px"><a href="${attr(videoHref)}" style="display:block;text-decoration:none;color:#111">${thumb?`<img src="${attr(thumb)}" width="560" alt="Persönliche Videoanalyse ansehen" style="display:block;width:100%;max-width:560px;height:auto;border:1px solid #e5e7eb;border-radius:14px 14px 0 0">`:""}<span style="display:block;padding:13px 16px;background:#0b2033;color:#fff;border-radius:${thumb?"0 0 14px 14px":"14px"};font-family:Arial,sans-serif;font-size:15px;font-weight:700;text-align:center">▶ Persönliche Videoanalyse ansehen</span></a></div>`;linked=linked.replace(linkedUrl,card).replace(escapedUrl,card)}return `<div style="font-family:Arial,sans-serif;font-size:15px;line-height:1.65;color:#151515">${linked}<br><br><span style="font-size:11px;color:#8a8a8a">Kein Interesse? <a href="${base}/u/${token}">Abmelden</a></span><img src="${base}/api/t/o/${token}" width="1" height="1" alt="" style="display:none"></div>`}
async function leadRow(db:DB,userId:string,leadId:string){const{data,error}=await db.from("energy_leads").select("*").eq("id",leadId).eq("user_id",userId).maybeSingle();if(error||!data)throw new Error("Lead nicht gefunden");return data}
async function workflow(db:DB,userId:string,leadId:string){const{data,error}=await db.from("energy_crm_lead_workflow").select("*").eq("lead_id",leadId).eq("user_id",userId).maybeSingle();if(error)throw error;return data}
async function contacts(db:DB,userId:string,leadId:string){const{data}=await db.from("energy_lead_contacts").select("id,name,title,email,phone,source_url,confidence,is_primary,source,updated_at").eq("lead_id",leadId).eq("user_id",userId).order("is_primary",{ascending:false}).order("confidence",{ascending:false}).limit(12);return data||[]}
async function latestPage(db:DB,userId:string,leadId:string,templateKey:string){const{data}=await db.from("energy_video_pages").select("id,slug,status,is_public,rendered_video_url,rendered_at,template_key,duration_seconds,updated_at,timeline_v3,website_capture_url,thumbnail_url,website_capture_status,website_capture_width,website_capture_height,presenter_video_url,studio_revision").eq("lead_id",leadId).eq("user_id",userId).eq("template_key",templateKey).neq("status","archived").order("updated_at",{ascending:false}).limit(1).maybeSingle();return data||null}
async function latestDraft(db:DB,userId:string,leadId:string){const{data}=await db.from("energy_messages").select("id,status,to_email,from_email,subject,body_text,mailbox_id,tracking_token,metadata,created_at,updated_at,sent_at,opened_at,clicked_at,replied_at,error").eq("lead_id",leadId).eq("user_id",userId).eq("direction","outbound").in("status",["draft","ready"]).order("updated_at",{ascending:false}).limit(1).maybeSingle();return data||null}
async function chooseMailbox(db:DB,userId:string){const{data}=await db.from("energy_mailboxes").select("*").eq("user_id",userId).eq("status","ready").order("sent_today",{ascending:true}).limit(1).maybeSingle();if(!data)throw new Error("Keine versandbereite Mailbox");return data}
async function mailboxSecret(db:DB,userId:string,id:string){const{data,error}=await db.rpc("energy_get_mailbox_secrets",{p_mailbox_id:id,p_user_id:userId});if(error)throw error;const row=Array.isArray(data)?data[0]:data,password=row?.smtp_password||"";if(!password)throw new Error("SMTP-Passwort fehlt");return password}
function defaultDraft(lead:any,pageUrl:string){const first=firstName(lead.contact_name),greeting=first?`Guten Tag ${first},`:"Guten Tag,";const subject=first?`${first}, ich habe Ihnen zu ${lead.company_name} kurz etwas aufgenommen`:`Kurze Videoanalyse für ${lead.company_name}`;const body=`${greeting}\n\nich habe mir ${lead.company_name} kurz angesehen und Ihnen dazu ein persönliches Video aufgenommen.\n\nHier sind die 107 Sekunden:\n${pageUrl}\n\nIch zeige darin direkt an Ihrem Unternehmen, welche Punkte wir bei Energiekosten und PV zuerst prüfen würden. Wenn bei Ihnen bereits alles optimal gelöst ist, können wir das Thema danach direkt abhaken.\n\nViele Grüße\nAndreas Walkenhorst\nWalkenhorst Energie`;return{subject,body}}
function gateState(lead:any,page:any,draft:any){const ready=loomReady(page);const checks=[{key:"contact",label:"Ansprechpartner / Kontaktdaten",ok:Boolean(lead.contact_name&&lead.email)},{key:"video",label:"Persönlicher Loom bereit",ok:ready},{key:"draft",label:"E-Mail-Entwurf gespeichert",ok:Boolean(draft?.id)},{key:"review",label:"E-Mail geprüft und freigegeben",ok:draft?.status==="ready"},{key:"dnc",label:"Kontakt erlaubt",ok:!lead.do_not_contact},{key:"email",label:"E-Mail vorhanden",ok:Boolean(lead.email)}];return{checks,allPassed:checks.every(x=>x.ok),sendPassed:checks.filter(x=>["video","draft","review","dnc","email"].includes(x.key)).every(x=>x.ok)}}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:H});if(req.method!=="POST")return out({error:"Method not allowed"},405);const a=await actor(req);if(!a)return out({error:"Nicht autorisiert"},401);const db=admin();try{const body=await req.json().catch(()=>({})),action=String(body?.action||"status"),leadId=String(body?.leadId||"").trim();if(!leadId)return out({error:"leadId fehlt"},400);const lead=await leadRow(db,a.id,leadId),templateKey=lockedTemplate(lead);
 if(action==="enrich"){const r=await fetch(`${env().url}/functions/v1/lead-contact-enrich`,{method:"POST",headers:{"content-type":"application/json","authorization":`Bearer ${a.token}`},body:JSON.stringify({leadId})});const data=await r.json().catch(()=>({error:`Enrichment HTTP ${r.status}`}));if(!r.ok)return out(data,r.status);return out({ok:true,action,...data,workflow:await workflow(db,a.id,leadId),contacts:await contacts(db,a.id,leadId)})}
 if(action==="prepare_page"){const r=await fetch(`${env().url}/functions/v1/crm-video-publish`,{method:"POST",headers:{"content-type":"application/json","authorization":`Bearer ${a.token}`},body:JSON.stringify({leadId,templateKey,baseUrl:body?.baseUrl})});const data=await r.json().catch(()=>({error:`Publish HTTP ${r.status}`}));if(!r.ok)return out(data,r.status);return out({ok:true,action,...data,workflow:await workflow(db,a.id,leadId),page:await latestPage(db,a.id,leadId,templateKey)})}
 if(action==="create_draft"){if(!lead.email)return out({error:"Lead hat keine E-Mail-Adresse"},409);if(lead.do_not_contact)return out({error:"Lead ist auf Nicht kontaktieren gesetzt"},409);const page=await latestPage(db,a.id,leadId,templateKey);if(!loomReady(page))return out({error:"Persönlicher Loom muss zuerst erstellt werden"},409);const base=String(body?.baseUrl||"https://walkenhorst.vercel.app").replace(/\/$/,""),pageUrl=`${base}/v/${page.slug}`,copy=defaultDraft(lead,pageUrl),subject=String(body?.subject||copy.subject).trim(),text=String(body?.bodyText||copy.body).trim(),mailbox=await chooseMailbox(db,a.id);let draft=await latestDraft(db,a.id,leadId);if(draft){const{data,error}=await db.from("energy_messages").update({status:"draft",mailbox_id:mailbox.id,to_email:lead.email,from_email:mailbox.email_address,subject,body_text:text,body_html:null,error:null,metadata:{...(draft.metadata||{}),workflow:"crm_live_loom",video_page_id:page.id,video_url:pageUrl,video_delivery_mode:liveTimeline(page)?"live_timeline_v3":"rendered_mp4",reviewed_at:null},updated_at:new Date().toISOString()}).eq("id",draft.id).eq("user_id",a.id).select("*").single();if(error)throw error;draft=data}else{const{data,error}=await db.from("energy_messages").insert({user_id:a.id,lead_id:leadId,mailbox_id:mailbox.id,direction:"outbound",status:"draft",to_email:lead.email,from_email:mailbox.email_address,subject,body_text:text,metadata:{workflow:"crm_live_loom",video_page_id:page.id,video_url:pageUrl,video_delivery_mode:liveTimeline(page)?"live_timeline_v3":"rendered_mp4"}}).select("*").single();if(error)throw error;draft=data}await db.from("energy_activities").insert({user_id:a.id,lead_id:leadId,activity_type:"email_draft",title:"E-Mail-Entwurf erstellt",detail:subject,metadata:{message_id:draft.id}});return out({ok:true,action,draft,workflow:await workflow(db,a.id,leadId),gates:gateState(lead,page,draft)})}
 if(action==="save_draft"){const draft=await latestDraft(db,a.id,leadId);if(!draft)return out({error:"Kein Entwurf vorhanden"},404);if(draft.status==="ready")return out({error:"Freigegebenen Entwurf zuerst wieder auf Entwurf setzen"},409);const patch:any={updated_at:new Date().toISOString()};if(typeof body?.subject==="string")patch.subject=body.subject.trim();if(typeof body?.bodyText==="string")patch.body_text=body.bodyText.trim();const{data,error}=await db.from("energy_messages").update(patch).eq("id",draft.id).eq("user_id",a.id).select("*").single();if(error)throw error;return out({ok:true,action,draft:data})}
 if(action==="review_draft"){const page=await latestPage(db,a.id,leadId,templateKey),draft=await latestDraft(db,a.id,leadId);if(!draft)return out({error:"Kein Entwurf vorhanden"},404);const gates=gateState(lead,page,draft),blockers=gates.checks.filter(x=>["video","draft","dnc","email"].includes(x.key)&&!x.ok);if(blockers.length)return out({error:"Freigabe blockiert",blockers,gates},409);const metadata={...(draft.metadata||{}),reviewed_at:new Date().toISOString(),reviewed_by:a.id};const{data,error}=await db.from("energy_messages").update({status:"ready",metadata,updated_at:new Date().toISOString()}).eq("id",draft.id).eq("user_id",a.id).select("*").single();if(error)throw error;await db.from("energy_activities").insert({user_id:a.id,lead_id:leadId,activity_type:"email_reviewed",title:"E-Mail geprüft und freigegeben",detail:data.subject,metadata:{message_id:data.id}});return out({ok:true,action,draft:data,workflow:await workflow(db,a.id,leadId),gates:gateState(lead,page,data)})}
 if(action==="reopen_draft"){const draft=await latestDraft(db,a.id,leadId);if(!draft)return out({error:"Kein Entwurf vorhanden"},404);const metadata={...(draft.metadata||{})};delete metadata.reviewed_at;delete metadata.reviewed_by;const{data,error}=await db.from("energy_messages").update({status:"draft",metadata,updated_at:new Date().toISOString()}).eq("id",draft.id).eq("user_id",a.id).select("*").single();if(error)throw error;return out({ok:true,action,draft:data})}
 if(action==="send_reviewed"){const page=await latestPage(db,a.id,leadId,templateKey),draft=await latestDraft(db,a.id,leadId);if(!draft)return out({error:"Kein Entwurf vorhanden"},404);const gates=gateState(lead,page,draft);if(!gates.sendPassed)return out({error:"Versand durch Prüf-Gates blockiert",gates},409);const mailbox=await chooseMailbox(db,a.id);if(draft.mailbox_id&&draft.mailbox_id!==mailbox.id){const{data:preferred}=await db.from("energy_mailboxes").select("*").eq("id",draft.mailbox_id).eq("user_id",a.id).eq("status","ready").maybeSingle();if(preferred)Object.assign(mailbox,preferred)}const password=await mailboxSecret(db,a.id,mailbox.id);if(!mailbox.smtp_host||!mailbox.smtp_username)throw new Error("SMTP-Konfiguration unvollständig");const base=String(body?.baseUrl||"https://walkenhorst.vercel.app").replace(/\/$/,""),html=trackHtml(draft.body_text||"",base,draft.tracking_token,page);await db.from("energy_messages").update({status:"sending",body_html:html,mailbox_id:mailbox.id,updated_at:new Date().toISOString()}).eq("id",draft.id).eq("user_id",a.id);try{const transport=nodemailer.createTransport({host:mailbox.smtp_host,port:Number(mailbox.smtp_port)||587,secure:Boolean(mailbox.smtp_secure),auth:{user:mailbox.smtp_username,pass:password},connectionTimeout:12000,greetingTimeout:12000,socketTimeout:20000});const unsubscribeUrl=`${base}/u/${draft.tracking_token}`;const info=await transport.sendMail({from:mailbox.from_name?`"${String(mailbox.from_name).replace(/\"/g,"")}" <${mailbox.email_address}>`:mailbox.email_address,to:lead.email,replyTo:mailbox.reply_to||mailbox.email_address,subject:draft.subject||"Persönliche Energie-Analyse",text:draft.body_text||"",html,headers:{"X-Walkenhorst-Lead":leadId,"X-Walkenhorst-Message":draft.id,"List-Unsubscribe":`<${unsubscribeUrl}>`,"List-Unsubscribe-Post":"List-Unsubscribe=One-Click"}});const now=new Date().toISOString();await db.from("energy_messages").update({status:"sent",provider_message_id:info.messageId||null,sent_at:now,error:null,updated_at:now}).eq("id",draft.id).eq("user_id",a.id);await db.from("energy_leads").update({status:["new","research","ready"].includes(lead.status)?"contacted":lead.status,last_contact_at:now,updated_at:now}).eq("id",leadId).eq("user_id",a.id);await db.from("energy_activities").insert({user_id:a.id,lead_id:leadId,activity_type:"email_sent",title:"Freigegebene E-Mail versendet",detail:draft.subject,metadata:{message_id:draft.id,mailbox:mailbox.email_address,video_delivery_mode:liveTimeline(page)?"live_timeline_v3":"rendered_mp4"}});return out({ok:true,action,sent:true,messageId:draft.id,workflow:await workflow(db,a.id,leadId)})}catch(e){const message=e instanceof Error?e.message.slice(0,500):"SMTP-Versand fehlgeschlagen";await db.from("energy_messages").update({status:"failed",error:message,updated_at:new Date().toISOString()}).eq("id",draft.id).eq("user_id",a.id);return out({error:message},422)}}
 if(action==="status"||action==="preflight"){const[wf,cs,page,draft]=await Promise.all([workflow(db,a.id,leadId),contacts(db,a.id,leadId),latestPage(db,a.id,leadId,templateKey),latestDraft(db,a.id,leadId)]);return out({ok:true,action,lead:{id:lead.id,company_name:lead.company_name,contact_name:lead.contact_name,contact_title:lead.contact_title,email:lead.email,phone:lead.phone,website:lead.website,status:lead.status,customer_type:lead.customer_type,video_template_key:lead.video_template_key,do_not_contact:lead.do_not_contact,intent_score:lead.intent_score,total_score:lead.total_score},workflow:wf,contacts:cs,page,draft,gates:gateState(lead,page,draft)})}
 return out({error:"Unbekannte Aktion"},400)}catch(e){return out({error:e instanceof Error?e.message.slice(0,700):"Workflow error"},500)}});