import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { createRemoteJWKSet, jwtVerify } from "npm:jose@5";

const H={"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*","access-control-allow-headers":"authorization, content-type, x-capture-width, x-capture-height","access-control-allow-methods":"POST, OPTIONS"};
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
const REPOSITORY="ravoeee-droid/walkenhorst";
const ISSUER="https://token.actions.githubusercontent.com";
const AUDIENCE="walkenhorst-render";
const BUCKET="energy-media";
const JWKS=createRemoteJWKSet(new URL("https://token.actions.githubusercontent.com/.well-known/jwks"));

function admin(){const url=Deno.env.get("SUPABASE_URL")!;const secrets=Deno.env.get("SUPABASE_SECRET_KEYS");const key=secrets?JSON.parse(secrets)?.default:Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)throw new Error("Backend configuration missing");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function sha256(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes)).map(x=>x.toString(16).padStart(2,"0")).join("")}
async function authorize(req:Request){const header=req.headers.get("authorization")||"";const token=header.toLowerCase().startsWith("bearer ")?header.slice(7).trim():"";if(!token)throw new Error("GitHub OIDC token fehlt");const{payload}=await jwtVerify(token,JWKS,{issuer:ISSUER,audience:AUDIENCE});if(String(payload.repository||"")!==REPOSITORY)throw new Error("Falsches GitHub Repository");if(String(payload.ref||"")!=="refs/heads/main")throw new Error("Render ist nur von main erlaubt");return payload}
function cleanMeta(raw:any,extra:Record<string,unknown>={}){const next={...(raw&&typeof raw==="object"?raw:{}),...extra};delete next.render_token_hash;delete next.render_token_expires_at;return next}
function permanent(message:string){return /B2B-Talking-Head|B2B-Presenter|verbotene Layer|Finale Timeline fehlt|Video-Master ist veraltet|nicht veröffentlicht|nicht korrekt gebunden|erforderliches Asset fehlt|Golden Master|Website URL fehlt|private oder lokale Netzwerk/i.test(message)}
function isStaticCapture(url:unknown){const v=String(url||"");return v.includes("/storage/v1/object/public/")&&v.includes(`/${BUCKET}/`)}
function bindWebsiteSource(raw:any,url:string){const timeline=structuredClone(raw&&typeof raw==="object"?raw:{});for(const track of Array.isArray(timeline?.tracks)?timeline.tracks:[]){for(const item of Array.isArray(track?.items)?track.items:[]){if(String(item?.type||"")==="website"||String(item?.dynamicSource||"")==="website_capture")item.sourceUrl=url}}return timeline}

async function retryOrFail(db:ReturnType<typeof admin>,job:any,message:string,forcePermanent=false){const attempts=Number(job?.attempt_count||0);const maxAttempts=Math.max(1,Number(job?.max_attempts||4));const stop=forcePermanent||permanent(message)||attempts>=maxAttempts;const now=new Date();const meta=cleanMeta(job?.metadata,{last_worker_error:message.slice(0,700),last_worker_error_at:now.toISOString()});if(stop){const{error}=await db.from("energy_render_jobs").update({status:"failed",error:message.slice(0,700),completed_at:now.toISOString(),locked_at:null,locked_by:null,metadata:meta,updated_at:now.toISOString()}).eq("id",job.id);if(error)throw error;return{status:"failed",attempts,maxAttempts}}
 const backoffMinutes=Math.min(15,Math.max(1,Math.pow(2,Math.max(0,attempts-1))));const next=new Date(now.getTime()+backoffMinutes*60000).toISOString();const{error}=await db.from("energy_render_jobs").update({status:"queued",progress:0,error:message.slice(0,700),next_attempt_at:next,locked_at:null,locked_by:null,completed_at:null,metadata:meta,updated_at:now.toISOString()}).eq("id",job.id);if(error)throw error;return{status:"retrying",attempts,maxAttempts,nextAttemptAt:next}}

async function captureState(db:ReturnType<typeof admin>,job:any){const{data:page,error}=await db.from("energy_video_pages").select("id,slug,template_key,website_url,website_capture_url,website_capture_status,website_capture_width,website_capture_height,studio_revision,timeline_v3").eq("id",job.video_page_id).eq("user_id",job.user_id).maybeSingle();if(error||!page)throw error||new Error("Video-Seite fehlt");if(String(page.template_key)!=="energiekosten")throw new Error("Worker akzeptiert nur Energiekosten-Renderjobs");const ready=isStaticCapture(page.website_capture_url)&&["ready","verified"].includes(String(page.website_capture_status||""))&&Number(page.website_capture_width||0)>=1920&&Number(page.website_capture_height||0)>=1080;return{ready,websiteUrl:String(page.website_url||""),captureUrl:String(page.website_capture_url||""),width:Number(page.website_capture_width||0),height:Number(page.website_capture_height||0),studioRevision:Number(page.studio_revision||0),pageId:page.id,slug:page.slug,timeline:page.timeline_v3}}

async function issue(db:ReturnType<typeof admin>,job:any,claims:any,capture:any){const token=`${crypto.randomUUID()}.${crypto.randomUUID()}`;const hash=await sha256(token);const expires=new Date(Date.now()+45*60*1000).toISOString();const now=new Date().toISOString();const metadata={...(job.metadata&&typeof job.metadata==="object"?job.metadata:{}),render_token_hash:hash,render_token_expires_at:expires,render_ticket_source:"github_oidc",render_ticket_issued_at:now,github_run_id:String(claims.run_id||""),github_run_attempt:String(claims.run_attempt||""),render_mode:"final_mp4_only"};const{error}=await db.from("energy_render_jobs").update({status:"preparing",progress:Math.max(1,Number(job.progress||0)),error:null,render_engine:"github-actions-headless-mp4",metadata,updated_at:now}).eq("id",job.id);if(error)throw error;return{jobId:job.id,status:"claimed",token,expiresAt:expires,attempt:Number(job.attempt_count||0),maxAttempts:Number(job.max_attempts||4),capture:{ready:capture.ready,websiteUrl:capture.websiteUrl,captureUrl:capture.captureUrl,width:capture.width,height:capture.height,studioRevision:capture.studioRevision}}}

async function uploadCapture(req:Request,db:ReturnType<typeof admin>,jobId:string){if(!jobId)throw new Error("jobId fehlt");const{data:job,error}=await db.from("energy_render_jobs").select("*").eq("id",jobId).maybeSingle();if(error||!job)throw error||new Error("Render-Job nicht gefunden");if(["completed","cancelled"].includes(String(job.status||"")))throw new Error(`Render-Job ist bereits ${job.status}`);const capture=await captureState(db,job);const width=Number(req.headers.get("x-capture-width")||0);const height=Number(req.headers.get("x-capture-height")||0);if(width<1920||height<1080)throw new Error(`HD-Capture ist zu klein: ${width}x${height}`);const buffer=await req.arrayBuffer();if(buffer.byteLength<30000||buffer.byteLength>25*1024*1024)throw new Error(`Capture-Dateigröße ungültig: ${buffer.byteLength} Bytes`);const path=`${job.user_id}/captures/${job.lead_id}/${job.id}-a${Math.max(1,Number(job.attempt_count||1))}.webp`;const stored=await db.storage.from(BUCKET).upload(path,new Uint8Array(buffer),{contentType:"image/webp",cacheControl:"31536000",upsert:true});if(stored.error)throw stored.error;const publicUrl=db.storage.from(BUCKET).getPublicUrl(path).data.publicUrl;const timeline=bindWebsiteSource(capture.timeline,publicUrl);const now=new Date().toISOString();const first=await db.from("energy_video_pages").update({website_capture_url:publicUrl,timeline_v3:timeline,updated_at:now}).eq("id",job.video_page_id).eq("user_id",job.user_id);if(first.error)throw first.error;const second=await db.from("energy_video_pages").update({website_capture_status:"verified",website_capture_verified_at:now,website_capture_width:width,website_capture_height:height,website_capture_error:null,updated_at:now}).eq("id",job.video_page_id).eq("user_id",job.user_id);if(second.error)throw second.error;const meta={...(job.metadata&&typeof job.metadata==="object"?job.metadata:{}),static_capture_url:publicUrl,static_capture_width:width,static_capture_height:height,static_capture_at:now};await db.from("energy_render_jobs").update({metadata:meta,updated_at:now}).eq("id",job.id);return{ok:true,status:"capture_stored",captureUrl:publicUrl,width,height,bytes:buffer.byteLength}}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:H});if(req.method!=="POST")return out({error:"Method not allowed"},405);try{const claims=await authorize(req);const requestUrl=new URL(req.url);const queryAction=String(requestUrl.searchParams.get("action")||"");const db=admin();if(queryAction==="upload_capture"){const jobId=String(requestUrl.searchParams.get("jobId")||"").trim();return out(await uploadCapture(req,db,jobId))}
 const body=await req.json().catch(()=>({}));const action=String(body?.action||"claim");
 if(action==="peek"){await db.rpc("energy_recover_stale_render_jobs");const{data,error}=await db.from("energy_render_jobs").select("id").eq("status","queued").eq("render_engine","github-actions-headless-mp4").lte("next_attempt_at",new Date().toISOString()).limit(1);if(error)throw error;return out({ok:true,status:"ok",hasWork:Boolean(data?.length)})}
 if(action==="claim"){await db.rpc("energy_recover_stale_render_jobs");const worker=String(body?.worker||`gha-${claims.run_id||claims.jti||"run"}`).slice(0,120);const{data,error}=await db.rpc("energy_claim_render_job",{p_worker:worker});if(error)throw error;const job=Array.isArray(data)?data[0]:data;if(!job)return out({ok:true,status:"empty"});const capture=await captureState(db,job);if(!capture.ready&&!capture.websiteUrl){const message="Website URL fehlt";return out({ok:true,jobId:job.id,...await retryOrFail(db,job,message,true),reason:message})}return out({ok:true,...await issue(db,job,claims,capture),leadId:job.lead_id,videoPageId:job.video_page_id,repository:claims.repository})}
 if(action==="runner_fail"){const jobId=String(body?.jobId||"").trim();const message=String(body?.error||"GitHub Render-Worker fehlgeschlagen").slice(0,700);if(!jobId)return out({error:"jobId fehlt"},400);const{data:job,error}=await db.from("energy_render_jobs").select("*").eq("id",jobId).maybeSingle();if(error||!job)throw error||new Error("Render-Job nicht gefunden");if(String(job.status)==="completed")return out({ok:true,status:"completed"});return out({ok:true,jobId,...await retryOrFail(db,job,message)})}
 if(action==="ticket"){const jobId=String(body?.jobId||"").trim();if(!jobId)return out({error:"jobId fehlt"},400);const{data:job,error}=await db.from("energy_render_jobs").select("*").eq("id",jobId).maybeSingle();if(error||!job)throw error||new Error("Render-Job nicht gefunden");if(String(job.status)==="completed")return out({ok:true,status:"completed",jobId});const capture=await captureState(db,job);return out({ok:true,...await issue(db,job,claims,capture),repository:claims.repository})}
 return out({error:"Unbekannte Aktion"},400)}catch(error){return out({error:error instanceof Error?error.message.slice(0,700):"GitHub render auth failed"},403)}});