"use client";

import { ChangeEvent, ReactNode, useEffect, useMemo, useRef, useState } from "react";
import { STUDIO_V3_QUICK_ADD_EVENT } from "./studio-v3-timeline";
import styles from "./studio-v3-editor.module.css";

export type StudioV3Asset={id:string;filename:string;kind:string;mime_type:string;size_bytes:number;storage_bucket:string;storage_path:string;label:string|null;metadata:Record<string,unknown>;created_at:string;publicUrl?:string|null};
export type StudioV3Bindings={presenterAssetId?:string;websiteCaptureAssetId?:string;logoAssetId?:string;portraitAssetId?:string;mapAssetId?:string};
type QuickType="text"|"metric"|"shape"|"website"|"presenter"|"logo"|"map";
type UploadRole="presenter"|"main_video"|"proof"|"logo"|"portrait"|"image"|"audio";
type Props={assets:StudioV3Asset[];bindings:StudioV3Bindings;selectedAssetId:string|null;uploading:boolean;onSelect:(id:string|null)=>void;onUpload:(event:ChangeEvent<HTMLInputElement>)=>void;onBind:(key:keyof StudioV3Bindings,assetId:string)=>void;onInsert:(asset:StudioV3Asset)=>void;onDelete:(asset:StudioV3Asset)=>void;onCaptureWebsite:()=>void;onCreateMap:()=>void;captureBusy?:boolean;mapBusy?:boolean};
const readable=(bytes:number)=>bytes>=1024*1024?`${(bytes/1024/1024).toFixed(bytes>10*1024*1024?0:1)} MB`:`${Math.ceil(bytes/1024)} KB`;
const emit=(type:QuickType)=>window.dispatchEvent(new CustomEvent(STUDIO_V3_QUICK_ADD_EVENT,{detail:{type}}));
const UPLOAD_ROLES:Array<{key:UploadRole;label:string;hint:string;accept:string;icon:ReactNode}>=[
 {key:"presenter",label:"Talking Head",hint:"Sprecher automatisch",accept:"video/mp4,video/webm",icon:<PersonIcon/>},
 {key:"main_video",label:"Hauptvideo",hint:"direkt in Timeline",accept:"video/mp4,video/webm",icon:<VideoIcon/>},
 {key:"proof",label:"Proof",hint:"Video oder Bild",accept:"video/mp4,video/webm,image/jpeg,image/png,image/webp,image/gif",icon:<ProofIcon/>},
 {key:"logo",label:"Logo",hint:"Video-Logo binden",accept:"image/jpeg,image/png,image/webp,image/gif",icon:<LogoIcon/>},
 {key:"portrait",label:"Portrait",hint:"Ansprechpartner",accept:"image/jpeg,image/png,image/webp,image/gif",icon:<PersonImageIcon/>},
 {key:"image",label:"Bild",hint:"direkt in Timeline",accept:"image/jpeg,image/png,image/webp,image/gif",icon:<ImageIcon/>},
 {key:"audio",label:"Audio",hint:"Audio-Spur",accept:"audio/mpeg,audio/wav,audio/ogg",icon:<AudioIcon/>},
];

export function StudioV3AssetPanel({assets,bindings,selectedAssetId,uploading,onSelect,onUpload,onBind,onInsert,onDelete,onCaptureWebsite,onCreateMap,captureBusy,mapBusy}:Props){
 const byId=(id?:string)=>assets.find(asset=>asset.id===id);const websiteAsset=byId(bindings.websiteCaptureAssetId);
 const bindingsList:Array<[keyof StudioV3Bindings,string]>=[["presenterAssetId","Talking Head / Sprecher"],["websiteCaptureAssetId","Website-Capture"],["mapAssetId","Standort / Dach"],["logoAssetId","Video-Logo"],["portraitAssetId","Portrait"]];
 const[uploadRole,setUploadRole]=useState<UploadRole>("presenter");const pendingRole=useRef<UploadRole|null>(null);const beforeIds=useRef<Set<string>>(new Set());
 const role=UPLOAD_ROLES.find(item=>item.key===uploadRole)!;
 const bindingNames=useMemo(()=>new Map<string,string>([[bindings.presenterAssetId||"","Talking Head"],[bindings.logoAssetId||"","Logo"],[bindings.portraitAssetId||"","Portrait"],[bindings.websiteCaptureAssetId||"","Website"],[bindings.mapAssetId||"","Dach"]].filter(([id])=>Boolean(id)) as Array<[string,string]>),[bindings]);
 function startUpload(event:ChangeEvent<HTMLInputElement>){beforeIds.current=new Set(assets.map(asset=>asset.id));pendingRole.current=uploadRole;onUpload(event)}
 useEffect(()=>{if(uploading||!pendingRole.current)return;const fresh=assets.filter(asset=>!beforeIds.current.has(asset.id));if(!fresh.length)return;const nextRole=pendingRole.current;for(const asset of fresh){if(nextRole==="presenter")onBind("presenterAssetId",asset.id);else if(nextRole==="logo")onBind("logoAssetId",asset.id);else if(nextRole==="portrait")onBind("portraitAssetId",asset.id);else onInsert(asset);onSelect(asset.id)}pendingRole.current=null;beforeIds.current=new Set(assets.map(asset=>asset.id))},[assets,uploading,onBind,onInsert,onSelect]);
 return <div className={`${styles.panel} studio-media-panel`}><div className={styles.panelHead}><strong>Medien & Elemente</strong><small>{assets.length} Assets</small></div><div className={styles.scroll}>
  <section className={`${styles.section} studio-quick-tools`}><div className={styles.sectionTitle}><strong>Elemente</strong><small>am Playhead</small></div><div className="studio-tool-grid"><Tool label="Text" onClick={()=>emit("text")}><TextIcon/></Tool><Tool label="Zahl" onClick={()=>emit("metric")}><MetricIcon/></Tool><Tool label="Shape" onClick={()=>emit("shape")}><ShapeIcon/></Tool><Tool label="Website" onClick={()=>emit("website")}><WebsiteIcon/></Tool><Tool label="Sprecher" onClick={()=>emit("presenter")}><PersonIcon/></Tool><Tool label="Dach" onClick={()=>emit("map")}><MapIcon/></Tool><Tool label="Logo" onClick={()=>emit("logo")}><LogoIcon/></Tool></div></section>
  <section className={`${styles.section} studio-upload-routing`}><div className={styles.sectionTitle}><strong>Upload</strong><small>direkt zuordnen</small></div><div className="studio-upload-role-grid">{UPLOAD_ROLES.map(option=><button type="button" key={option.key} className={`studio-upload-role ${uploadRole===option.key?"is-active":""}`} onClick={()=>setUploadRole(option.key)}><span className="studio-upload-role-icon">{option.icon}</span><span><strong>{option.label}</strong><small>{option.hint}</small></span></button>)}</div><label className="studio-upload-drop"><input type="file" multiple={uploadRole==="proof"||uploadRole==="image"} accept={role.accept} onChange={startUpload} disabled={uploading}/><span className="studio-upload-drop-icon"><UploadIcon/></span><span><strong>{uploading?"Upload läuft …":`${role.label} hochladen`}</strong><small>{uploading?"Datei wird gespeichert und danach automatisch zugeordnet.":`${role.hint} · max. 50 MB`}</small></span></label><div className="studio-upload-note">Nach dem Upload wird das Medium automatisch als <strong>{role.label}</strong> verwendet. Kein nachträgliches Suchen oder Zuordnen nötig.</div></section>
  <section className={styles.section}><div className={styles.sectionTitle}><strong>Dynamische Quellen</strong><small>Master → Lead</small></div>{bindingsList.map(([key,label])=>{const asset=byId(bindings[key]);return <div className={styles.binding} key={key}><div><strong>{label}</strong><small>{asset?.filename||"noch nicht gesetzt"}</small></div><div className="studio-binding-actions">{asset?<button className={styles.mini} onClick={()=>onSelect(asset.id)}>anzeigen</button>:null}{key==="websiteCaptureAssetId"&&asset?.publicUrl?<a className={styles.mini} href={asset.publicUrl} target="_blank" rel="noreferrer">öffnen ↗</a>:null}</div></div>})}<div className={styles.grid2}><button className={styles.btn} onClick={onCaptureWebsite} disabled={captureBusy}>{captureBusy?"Aufnahme läuft …":websiteAsset?"Website neu aufnehmen":"Website aufnehmen"}</button><button className={styles.btn} onClick={onCreateMap} disabled={mapBusy}>{mapBusy?"Satellite lädt …":"Satellite / Dach"}</button></div></section>
  <section className={styles.section}><div className={styles.sectionTitle}><strong>Bibliothek</strong><small>{assets.length} Medien</small></div>{assets.length?<div className={styles.assetGrid}>{assets.map(asset=>{const selected=selectedAssetId===asset.id,media=asset.publicUrl,binding=bindingNames.get(asset.id);return <article key={asset.id} className={`${styles.asset} ${selected?styles.assetSelected:""}`} onClick={()=>onSelect(asset.id)}><div className={styles.assetPreview}>{media&&asset.mime_type.startsWith("image/")?<img src={media} alt=""/>:media&&asset.mime_type.startsWith("video/")?<video src={media} muted playsInline preload="metadata"/>:asset.mime_type.startsWith("audio/")?<AudioIcon/>:<FileIcon/>}{binding?<span className="studio-asset-role">{binding}</span>:null}</div><div className={styles.assetInfo}><strong>{asset.label||asset.filename}</strong><small>{asset.kind} · {readable(asset.size_bytes)}</small></div><div className={styles.assetButtons}><button className={styles.mini} onClick={event=>{event.stopPropagation();onInsert(asset)}}>Timeline</button>{asset.mime_type.startsWith("video/")?<button className={styles.mini} onClick={event=>{event.stopPropagation();onBind("presenterAssetId",asset.id)}}>Sprecher</button>:null}{asset.mime_type.startsWith("image/")?<button className={styles.mini} onClick={event=>{event.stopPropagation();onBind("logoAssetId",asset.id)}}>Logo</button>:null}<button aria-label="Medium löschen" className={`${styles.mini} ${styles.danger}`} onClick={event=>{event.stopPropagation();onDelete(asset)}}>×</button></div></article>})}</div>:<div className={styles.empty}>Noch keine Medien. Wähle oben zuerst, was du hochlädst – das Studio ordnet es anschließend automatisch zu.</div>}</section>
 </div></div>
}
function Tool({label,onClick,children}:{label:string;onClick:()=>void;children:ReactNode}){return <button type="button" onClick={onClick} className="studio-tool-button">{children}<span>{label}</span></button>}
const icon=(children:ReactNode)=><svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{children}</svg>;
const TextIcon=()=>icon(<><path d="M5 6h14M12 6v13M8.5 19h7"/></>);const MetricIcon=()=>icon(<><path d="M5 18V10M12 18V5M19 18v-6"/></>);const ShapeIcon=()=>icon(<><rect x="5" y="5" width="14" height="14" rx="3"/></>);const WebsiteIcon=()=>icon(<><rect x="3.5" y="5" width="17" height="14" rx="2"/><path d="M3.5 9h17M7 7h.1M10 7h.1"/></>);const PersonIcon=()=>icon(<><circle cx="12" cy="8" r="3"/><path d="M6 20c.5-4 2.5-6 6-6s5.5 2 6 6"/></>);const MapIcon=()=>icon(<><path d="m4 6 5-2 6 2 5-2v14l-5 2-6-2-5 2V6Z"/><path d="M9 4v14M15 6v14"/></>);const LogoIcon=()=>icon(<><path d="M5 18 12 5l7 13M8 14h8"/></>);const UploadIcon=()=>icon(<><path d="M12 17V5M7.5 9.5 12 5l4.5 4.5"/><path d="M5 19h14"/></>);const AudioIcon=()=>icon(<><path d="M9 18V6l9-2v12"/><circle cx="6.5" cy="18" r="2.5"/><circle cx="15.5" cy="16" r="2.5"/></>);const FileIcon=()=>icon(<><path d="M7 3h7l4 4v14H7V3Z"/><path d="M14 3v5h5"/></>);const VideoIcon=()=>icon(<><rect x="4" y="6" width="13" height="12" rx="2"/><path d="m17 10 4-2v8l-4-2"/></>);const ProofIcon=()=>icon(<><rect x="4" y="5" width="16" height="14" rx="2"/><path d="m7 15 3-3 2.5 2 2.5-3 3 4"/></>);const PersonImageIcon=()=>icon(<><rect x="4" y="4" width="16" height="16" rx="3"/><circle cx="12" cy="9" r="2.5"/><path d="M8 17c.5-2.5 1.8-3.7 4-3.7s3.5 1.2 4 3.7"/></>);const ImageIcon=()=>icon(<><rect x="4" y="5" width="16" height="14" rx="2"/><circle cx="9" cy="10" r="1.5"/><path d="m6 17 4-4 2.5 2.5L15 13l3 4"/></>);
