"use client";

import { PointerEvent as ReactPointerEvent, useMemo, useRef, useState } from "react";
import { StudioV3Item, StudioV3Timeline, StudioV3Track, studioV3Time } from "@/lib/studio-v3";

type Props={timeline:StudioV3Timeline;onChange:(next:StudioV3Timeline)=>void;timeMs:number;onTimeChange:(time:number)=>void;selectedItemId:string|null;onSelectItem:(id:string|null)=>void};
type Drag={mode:"move"|"start"|"end";itemId:string;trackId:string;startX:number;startMs:number;endMs:number};
const colors:Record<string,string>={website:"#2D7254",video:"#356D99",presenter:"#C69B2E",image:"#7A63AA",map:"#A16D35",text:"#3F3F46",metric:"#B87722",logo:"#111111",shape:"#777",audio:"#6D58A6"};
export function StudioV3TimelineEditor({timeline,onChange,timeMs,onTimeChange,selectedItemId,onSelectItem}:Props){const[pps,setPps]=useState(80);const[snapMs,setSnapMs]=useState(100);const drag=useRef<Drag|null>(null);const durationSec=Math.ceil(timeline.durationMs/1000);const contentWidth=Math.max(900,durationSec*pps);const majorStep=pps<45?5:pps<90?2:1;const marks=useMemo(()=>Array.from({length:Math.floor(durationSec/majorStep)+1},(_,i)=>i*majorStep),[durationSec,majorStep]);
 const snap=(value:number)=>snapMs?Math.round(value/snapMs)*snapMs:value;
 function patchTrack(trackId:string,patch:Partial<StudioV3Track>){onChange({...timeline,tracks:timeline.tracks.map(track=>track.id===trackId?{...track,...patch}:track)})}
 function patchItem(trackId:string,itemId:string,patch:Partial<StudioV3Item>){onChange({...timeline,tracks:timeline.tracks.map(track=>track.id===trackId?{...track,items:track.items.map(item=>item.id===itemId?{...item,...patch}:item)}:track)})}
 function startDrag(event:ReactPointerEvent,track:StudioV3Track,item:StudioV3Item,mode:Drag["mode"]){if(track.locked||item.locked)return;event.stopPropagation();event.preventDefault();onSelectItem(item.id);drag.current={mode,itemId:item.id,trackId:track.id,startX:event.clientX,startMs:item.startMs,endMs:item.endMs};const move=(native:PointerEvent)=>{const d=drag.current;if(!d)return;const delta=(native.clientX-d.startX)/pps*1000;const minLength=100;let start=d.startMs,end=d.endMs;if(d.mode==="move"){const length=end-start;start=snap(Math.max(0,Math.min(timeline.durationMs-length,start+delta)));end=start+length}else if(d.mode==="start")start=snap(Math.max(0,Math.min(end-minLength,start+delta)));else end=snap(Math.min(timeline.durationMs,Math.max(start+minLength,end+delta)));patchItem(d.trackId,d.itemId,{startMs:start,endMs:end})};const up=()=>{drag.current=null;window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up,{once:true})}
 function seekFromPointer(event:ReactPointerEvent<HTMLDivElement>){const rect=event.currentTarget.getBoundingClientRect();const x=event.clientX-rect.left;onTimeChange(Math.min(timeline.durationMs,Math.max(0,x/pps*1000)))}
 return <section style={root}><div style={toolbar}><strong style={{fontSize:11}}>Timeline</strong><span style={muted}>{studioV3Time(timeMs)} / {studioV3Time(timeline.durationMs)}</span><label style={label}>Snap <select value={snapMs} onChange={e=>setSnapMs(Number(e.target.value))} style={select}><option value={0}>Aus</option><option value={50}>0,05 s</option><option value={100}>0,10 s</option><option value={250}>0,25 s</option><option value={500}>0,50 s</option><option value={1000}>1,00 s</option></select></label><label style={label}>Zoom <input type="range" min={25} max={180} value={pps} onChange={e=>setPps(Number(e.target.value))} style={{width:110}}/></label></div><div style={scroll}><div style={{display:"grid",gridTemplateColumns:"160px 1fr",minWidth:160+contentWidth}}><div style={corner}>SPUREN</div><div style={{...ruler,width:contentWidth}} onPointerDown={seekFromPointer}>{marks.map(mark=><div key={mark} style={{position:"absolute",left:mark*pps,top:0,bottom:0,borderLeft:"1px solid #D7DDD9"}}><span style={{position:"absolute",top:6,left:4,fontSize:8,color:"#758079"}}>{studioV3Time(mark*1000).slice(0,5)}</span></div>)}<div style={{...playhead,left:timeMs/1000*pps}}/></div>{timeline.tracks.map(track=><TrackRow key={track.id} track={track} pps={pps} width={contentWidth} selectedItemId={selectedItemId} timeMs={timeMs} onSelectItem={onSelectItem} onStartDrag={startDrag} onToggle={patch=>patchTrack(track.id,patch)} onSeek={seekFromPointer}/>)}</div></div></section>}

type TrackProps={track:StudioV3Track;pps:number;width:number;selectedItemId:string|null;timeMs:number;onSelectItem:(id:string|null)=>void;onStartDrag:(event:ReactPointerEvent,track:StudioV3Track,item:StudioV3Item,mode:Drag["mode"])=>void;onToggle:(patch:Partial<StudioV3Track>)=>void;onSeek:(event:ReactPointerEvent<HTMLDivElement>)=>void};
function TrackRow({track,pps,width,selectedItemId,timeMs,onSelectItem,onStartDrag,onToggle,onSeek}:TrackProps){return <><div style={trackHead}><button title={track.hidden?"Einblenden":"Ausblenden"} style={tiny} onClick={()=>onToggle({hidden:!track.hidden})}>{track.hidden?"○":"●"}</button><button title={track.locked?"Entsperren":"Sperren"} style={tiny} onClick={()=>onToggle({locked:!track.locked})}>{track.locked?"🔒":"⌁"}</button><div style={{minWidth:0}}><strong style={{display:"block",fontSize:9,overflow:"hidden",whiteSpace:"nowrap",textOverflow:"ellipsis"}}>{track.name}</strong><small style={{fontSize:7,color:"#859087"}}>{track.type}</small></div></div><div style={{...trackBody,width,opacity:track.hidden?.45:1}} onPointerDown={onSeek}>{Array.from({length:Math.ceil(width/pps)+1},(_,index)=><span key={index} style={{position:"absolute",left:index*pps,top:0,bottom:0,borderLeft:"1px solid rgba(20,30,24,.045)"}}/>)}{track.items.map(item=>{const left=item.startMs/1000*pps,w=Math.max(5,(item.endMs-item.startMs)/1000*pps),selected=selectedItemId===item.id;return <div key={item.id} title={`${item.label} · ${studioV3Time(item.startMs)} – ${studioV3Time(item.endMs)}`} onPointerDown={e=>onStartDrag(e,track,item,"move")} onClick={e=>{e.stopPropagation();onSelectItem(item.id)}} style={{position:"absolute",left,width:w,top:7,height:36,borderRadius:7,border:selected?"2px solid #F3C64B":"1px solid rgba(0,0,0,.13)",background:colors[item.type]||"#555",color:"#fff",boxSizing:"border-box",cursor:track.locked?"not-allowed":"grab",overflow:"hidden",boxShadow:selected?"0 0 0 2px rgba(243,198,75,.22)":"0 2px 5px rgba(0,0,0,.08)"}}><span onPointerDown={e=>onStartDrag(e,track,item,"start")} style={handle}/><div style={{padding:"6px 10px",pointerEvents:"none",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}><strong style={{display:"block",fontSize:8}}>{item.label}</strong><small style={{fontSize:6.5,opacity:.8}}>{((item.endMs-item.startMs)/1000).toFixed(2)} s</small></div><span onPointerDown={e=>onStartDrag(e,track,item,"end")} style={{...handle,left:"auto",right:0}}/></div>})}<div style={{...playhead,left:timeMs/1000*pps,pointerEvents:"none"}}/></div></>}
const root:React.CSSProperties={border:"1px solid #DCE2DE",borderRadius:12,background:"#fff",overflow:"hidden"};const toolbar:React.CSSProperties={display:"flex",alignItems:"center",gap:12,padding:"9px 12px",borderBottom:"1px solid #E7EBE8",background:"#FAFBFA"};const muted:React.CSSProperties={fontSize:8,color:"#7B8780",fontVariantNumeric:"tabular-nums",marginRight:"auto"};const label:React.CSSProperties={display:"flex",alignItems:"center",gap:5,fontSize:8,fontWeight:800,color:"#66736B"};const select:React.CSSProperties={border:"1px solid #DCE3DF",borderRadius:6,background:"#fff",padding:"4px 6px",fontSize:8};const scroll:React.CSSProperties={overflow:"auto",maxHeight:410};const corner:React.CSSProperties={position:"sticky",left:0,zIndex:8,height:34,borderRight:"1px solid #E1E6E3",borderBottom:"1px solid #E1E6E3",background:"#F6F8F6",padding:"11px 10px",boxSizing:"border-box",fontSize:7,fontWeight:900,letterSpacing:1.3,color:"#829087"};const ruler:React.CSSProperties={position:"relative",height:34,borderBottom:"1px solid #E1E6E3",background:"#F8FAF8",cursor:"crosshair"};const trackHead:React.CSSProperties={position:"sticky",left:0,zIndex:7,display:"grid",gridTemplateColumns:"24px 24px 1fr",gap:3,alignItems:"center",height:50,borderRight:"1px solid #E1E6E3",borderBottom:"1px solid #ECEFEC",background:"#FBFCFB",padding:"0 6px",boxSizing:"border-box"};const tiny:React.CSSProperties={display:"grid",width:22,height:22,placeItems:"center",border:"1px solid #E1E6E3",borderRadius:5,background:"#fff",fontSize:8,cursor:"pointer"};const trackBody:React.CSSProperties={position:"relative",height:50,borderBottom:"1px solid #ECEFEC",background:"#FEFFFE",cursor:"crosshair"};const handle:React.CSSProperties={position:"absolute",zIndex:3,left:0,top:0,bottom:0,width:7,background:"rgba(255,255,255,.42)",cursor:"ew-resize"};const playhead:React.CSSProperties={position:"absolute",zIndex:20,top:0,bottom:0,width:1.5,background:"#E4B326",boxShadow:"0 0 0 1px rgba(228,179,38,.14)"};
