"use client";

import { useEffect, useState } from "react";
import { StudioV3BrandKit, StudioV3Item, StudioV3LeadVariables, StudioV3Timeline } from "@/lib/studio-v3";
import { renderStudioV3Browser } from "@/lib/studio-v3-browser-render";
import styles from "./studio-v3-editor.module.css";

type Props={timeline:StudioV3Timeline;brand:StudioV3BrandKit;variables:StudioV3LeadVariables;resolveSource:(item:StudioV3Item)=>string|null;busy?:boolean;onRendered:(result:{blob:Blob;format:"mp4"|"webm";mimeType:string;warnings:string[];width:number;height:number})=>Promise<void>};
export function StudioV3RenderPanel({timeline,brand,variables,resolveSource,onRendered}:Props){const[progress,setProgress]=useState(0);const[rendering,setRendering]=useState(false);const[error,setError]=useState<string|null>(null);const[warnings,setWarnings]=useState<string[]>([]);const[resultUrl,setResultUrl]=useState<string|null>(null);const[format,setFormat]=useState<"mp4"|"webm"|null>(null);const controller=useState(()=>({current:null as AbortController|null}))[0];useEffect(()=>()=>{if(resultUrl)URL.revokeObjectURL(resultUrl);controller.current?.abort()},[controller,resultUrl]);
 async function render(){setRendering(true);setError(null);setWarnings([]);setProgress(0);if(resultUrl){URL.revokeObjectURL(resultUrl);setResultUrl(null)}controller.current=new AbortController();try{const result=await renderStudioV3Browser({timeline,brand,variables,resolveSource,onProgress:setProgress,signal:controller.current.signal,maxWidth:1920});const url=URL.createObjectURL(result.blob);setResultUrl(url);setFormat(result.format);setWarnings(result.warnings);await onRendered(result)}catch(e){if((e as DOMException)?.name!=="AbortError")setError(e instanceof Error?e.message:"Rendering fehlgeschlagen") }finally{setRendering(false);controller.current=null}}
 function download(){if(!resultUrl||!format)return;const a=document.createElement("a");a.href=resultUrl;a.download=`walkenhorst-video.${format}`;document.body.appendChild(a);a.click();a.remove()}
 return <div className={styles.renderPanel}><section className={styles.renderCard}><div className={styles.sectionTitle}><div><strong>Finales Endvideo rendern</strong><div style={{fontSize:8,color:"#79847d",marginTop:4}}>Canvas + Website + Presenter + Bilder + Overlays + Audio werden framegenau zusammengesetzt.</div></div><span className={styles.kbd}>{timeline.aspectRatio}</span></div><div className={styles.grid3}><div className={styles.field}><label>Auflösung</label><input readOnly value={`${timeline.width} × ${timeline.height}`}/></div><div className={styles.field}><label>FPS</label><input readOnly value={`${timeline.fps} fps`}/></div><div className={styles.field}><label>Länge</label><input readOnly value={`${(timeline.durationMs/1000).toFixed(2)} s`}/></div></div><div className={styles.progress}><span style={{width:`${progress}%`}}/></div><div style={{display:"flex",gap:7,marginTop:12}}><button className={`${styles.btn} ${styles.gold}`} onClick={()=>void render()} disabled={rendering}>{rendering?`Rendering ${progress}% …`:"Endvideo rendern"}</button>{rendering?<button className={styles.btn} onClick={()=>controller.current?.abort()}>Abbrechen</button>:null}{resultUrl?<button className={`${styles.btn} ${styles.primary}`} onClick={download}>Video speichern</button>:null}</div>{error?<div style={{marginTop:10,color:"#a43737",fontSize:9}}>{error}</div>:null}{warnings.length?<div style={{marginTop:10,border:"1px solid #ead9a8",borderRadius:8,background:"#fffaf0",padding:9,fontSize:8}}>{warnings.map((warning,index)=><div key={index}>• {warning}</div>)}</div>:null}{resultUrl?<div className={styles.renderPreview}><video src={resultUrl} controls style={{width:"100%",display:"block"}}/></div>:null}<p style={{fontSize:7.5,color:"#7b867f",lineHeight:1.5,marginTop:12}}>Der Renderer exportiert MP4, wenn der verwendete Browser H.264/MP4 via MediaRecorder anbietet; andernfalls wird verlustfrei auf WebM ausgewichen. Der exakte verwendete Dateityp wird nach dem Render angezeigt. Große Rohdateien bleiben auf dem aktuellen Storage-Plan auf 50 MB pro Datei begrenzt.</p>{format?<div style={{fontSize:8,marginTop:5,fontWeight:800}}>Letzter Render: {format.toUpperCase()}</div>:null}</section></div>}
