"use client";

import { CSSProperties, PointerEvent as ReactPointerEvent, useEffect, useMemo, useRef } from "react";
import { StudioV3BrandKit, StudioV3Item, StudioV3LeadVariables, StudioV3Timeline, StudioV3Transform, resolveStudioV3Text, studioV3ActiveItems } from "@/lib/studio-v3";

type Props={timeline:StudioV3Timeline;timeMs:number;playing:boolean;playbackRate?:number;brand:StudioV3BrandKit;variables:StudioV3LeadVariables;resolveSource?:(item:StudioV3Item)=>string|null;className?:string;onSelectItem?:(id:string)=>void;selectedItemId?:string|null;interactive?:boolean;onTransformItem?:(id:string,transform:StudioV3Transform)=>void};
type VisualState={x:number;y:number;scale:number;opacity:number;scrollY:number;cropX:number;cropY:number;cropWidth:number;cropHeight:number};
type ResizeMode="nw"|"ne"|"sw"|"se";
const clamp=(n:number,min=0,max=1)=>Math.min(Math.max(n,min),max);const clampPercent=(n:number,min=0,max=100)=>Math.min(Math.max(n,min),max);
function keyframeState(item:StudioV3Item,timeMs:number):VisualState{const base:VisualState={x:item.transform.x,y:item.transform.y,scale:item.transform.scale,opacity:item.transform.opacity,scrollY:0,cropX:0,cropY:0,cropWidth:100,cropHeight:100};const frames=[...(item.keyframes||[])].sort((a,b)=>a.atMs-b.atMs);if(!frames.length)return base;const relative=timeMs;let before=frames[0],after=frames[frames.length-1];for(let i=0;i<frames.length;i++){if(frames[i].atMs<=relative)before=frames[i];if(frames[i].atMs>=relative){after=frames[i];break}}const span=Math.max(1,after.atMs-before.atMs);const p=before===after?0:clamp((relative-before.atMs)/span);const value=(key:keyof VisualState,fallback:number)=>{const a=Number((before as any)[key]??fallback),b=Number((after as any)[key]??a);return a+(b-a)*p};return{x:value("x",base.x),y:value("y",base.y),scale:value("scale",base.scale),opacity:value("opacity",base.opacity),scrollY:value("scrollY",0),cropX:value("cropX",0),cropY:value("cropY",0),cropWidth:value("cropWidth",100),cropHeight:value("cropHeight",100)}}
function animatedStyle(item:StudioV3Item,timeMs:number){const duration=Math.max(1,item.endMs-item.startMs),local=timeMs-item.startMs,anim=Math.max(1,item.animationDurationMs||350),inP=clamp(local/anim),outP=clamp((item.endMs-timeMs)/anim);let opacity=1,tx=0,ty=0,scale=1;const apply=(kind:string,p:number,incoming:boolean)=>{const q=incoming?p:Math.min(1,p);if(kind==="fade")opacity*=q;if(kind==="slide-up")ty+=(1-q)*(incoming?28:-18);if(kind==="slide-left")tx+=(1-q)*(incoming?34:-22);if(kind==="zoom")scale*=.88+.12*q;if(kind==="pop")scale*=.72+.28*Math.min(1,q*1.25)};if(local<anim)apply(item.animationIn||"none",inP,true);if(duration-local<anim)apply(item.animationOut||"none",outP,false);return{opacity,transform:`translate(${tx}px,${ty}px) scale(${scale})`}}
function shadow(value:StudioV3Item["shadow"]){if(value==="strong")return"0 22px 60px rgba(0,0,0,.42)";if(value==="soft")return"0 12px 34px rgba(0,0,0,.22)";return"none"}
function box(item:StudioV3Item,state:VisualState,selected:boolean,interactive:boolean):CSSProperties{return{position:"absolute",left:`${state.x}%`,top:`${state.y}%`,width:`${item.transform.width}%`,height:`${item.transform.height}%`,opacity:state.opacity,transform:`rotate(${item.transform.rotation}deg) scale(${state.scale})`,transformOrigin:"center",borderRadius:item.transform.borderRadius,zIndex:item.zIndex,boxShadow:shadow(item.shadow),outline:selected?"1.5px solid #F1C54C":"none",outlineOffset:2,pointerEvents:"auto",cursor:interactive?selected?"move":"default":"default",touchAction:"none"}}
function MediaLayer({item,timeMs,playing,playbackRate,source,style,brand,variables}:{item:StudioV3Item;timeMs:number;playing:boolean;playbackRate:number;source:string|null;style:CSSProperties;brand:StudioV3BrandKit;variables:StudioV3LeadVariables}){const videoRef=useRef<HTMLVideoElement>(null);const localMs=Math.max(0,timeMs-item.startMs);useEffect(()=>{const video=videoRef.current;if(!video||!source)return;const desired=localMs/1000*(item.playbackRate||1);if(Number.isFinite(video.duration)&&Math.abs(video.currentTime-desired)>.28)try{video.currentTime=Math.min(Math.max(0,desired),Math.max(0,video.duration-.03))}catch{};video.playbackRate=(item.playbackRate||1)*playbackRate;video.muted=Boolean(item.muted)||(item.volume??1)<=0;if(playing)void video.play().catch(()=>undefined);else video.pause()},[item.muted,item.playbackRate,item.volume,localMs,playing,playbackRate,source]);
 if(item.type==="video"||item.type==="presenter")return source?<video ref={videoRef} src={source} crossOrigin="anonymous" playsInline preload="auto" style={{...style,width:"100%",height:"100%",objectFit:item.fit||"cover"}}/>:<div style={{...style,display:"grid",placeItems:"center",background:"#171717",color:"#fff",fontSize:18,fontWeight:800}}>Video/Presenter fehlt</div>;
 if(item.type==="image"||item.type==="logo"||item.type==="map")return source?<img src={source} crossOrigin="anonymous" alt="" draggable={false} style={{...style,width:"100%",height:"100%",objectFit:item.fit||"contain"}}/>:<div style={{...style,display:"grid",placeItems:"center",background:"#F3F1EA",color:"#111",fontSize:15,fontWeight:800}}>{item.type==="logo"?brand.name:"Asset fehlt"}</div>;
 if(item.type==="website"){const state=keyframeState(item,timeMs);return source?<div style={{...style,overflow:"hidden",background:"#fff"}}><img src={source} crossOrigin="anonymous" alt="" draggable={false} style={{width:`${100*state.scale}%`,maxWidth:"none",height:"auto",minHeight:"100%",display:"block",transform:`translate(${-(state.scale-1)*25}%, -${state.scrollY}%)`,transformOrigin:"top left"}}/></div>:<div style={{...style,background:`linear-gradient(145deg,${brand.primaryColor},#272727)`,color:"#fff",padding:"8%",display:"grid",alignContent:"center"}}><small style={{color:brand.accentColor,fontWeight:900,letterSpacing:2}}>UNTERNEHMENSWEBSITE</small><strong style={{fontSize:"clamp(24px,4vw,70px)",lineHeight:1,marginTop:12}}>{resolveStudioV3Text("{{company}}",variables)}</strong></div>}
 return null}
function CanvasHandles({onResize}:{onResize:(event:ReactPointerEvent,mode:ResizeMode)=>void}){const positions:Record<ResizeMode,CSSProperties>={nw:{left:-5,top:-5,cursor:"nwse-resize"},ne:{right:-5,top:-5,cursor:"nesw-resize"},sw:{left:-5,bottom:-5,cursor:"nesw-resize"},se:{right:-5,bottom:-5,cursor:"nwse-resize"}};return <>{(Object.keys(positions) as ResizeMode[]).map(mode=><span key={mode} onPointerDown={event=>onResize(event,mode)} style={{position:"absolute",zIndex:50,width:10,height:10,border:"1px solid rgba(0,0,0,.24)",borderRadius:3,background:"#fff",boxShadow:"0 1px 4px rgba(0,0,0,.18)",...positions[mode]}}/>)}</>}

export function StudioV3Canvas({timeline,timeMs,playing,playbackRate=1,brand,variables,resolveSource,className,onSelectItem,selectedItemId,interactive=false,onTransformItem}:Props){const active=useMemo(()=>studioV3ActiveItems(timeline,timeMs),[timeline,timeMs]);const rootRef=useRef<HTMLDivElement>(null);
 function beginMove(event:ReactPointerEvent,item:StudioV3Item){onSelectItem?.(item.id);if(!interactive||playing||!onTransformItem)return;event.preventDefault();event.stopPropagation();const rect=rootRef.current?.getBoundingClientRect();if(!rect)return;const start={x:event.clientX,y:event.clientY,transform:{...item.transform}};const move=(native:PointerEvent)=>{const dx=(native.clientX-start.x)/rect.width*100,dy=(native.clientY-start.y)/rect.height*100;const next={...start.transform,x:clampPercent(start.transform.x+dx,0,100-start.transform.width),y:clampPercent(start.transform.y+dy,0,100-start.transform.height)};onTransformItem(item.id,next)};const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up,{once:true})}
 function beginResize(event:ReactPointerEvent,item:StudioV3Item,mode:ResizeMode){if(!interactive||playing||!onTransformItem)return;event.preventDefault();event.stopPropagation();onSelectItem?.(item.id);const rect=rootRef.current?.getBoundingClientRect();if(!rect)return;const start={x:event.clientX,y:event.clientY,transform:{...item.transform}};const move=(native:PointerEvent)=>{const dx=(native.clientX-start.x)/rect.width*100,dy=(native.clientY-start.y)/rect.height*100;let{x,y,width,height}=start.transform;if(mode.includes("e"))width=clampPercent(start.transform.width+dx,2,100-start.transform.x);if(mode.includes("s"))height=clampPercent(start.transform.height+dy,2,100-start.transform.y);if(mode.includes("w")){const nx=clampPercent(start.transform.x+dx,0,start.transform.x+start.transform.width-2);width=start.transform.width+(start.transform.x-nx);x=nx}if(mode.includes("n")){const ny=clampPercent(start.transform.y+dy,0,start.transform.y+start.transform.height-2);height=start.transform.height+(start.transform.y-ny);y=ny}onTransformItem(item.id,{...start.transform,x,y,width,height})};const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up,{once:true})}
 return <div ref={rootRef} className={className} onPointerDown={()=>onSelectItem?.("")} style={{position:"relative",width:"100%",aspectRatio:`${timeline.width}/${timeline.height}`,overflow:"hidden",background:timeline.backgroundColor,borderRadius:12,isolation:"isolate",userSelect:"none"}}>{active.map(item=>{const state=keyframeState(item,timeMs);const animation=animatedStyle(item,timeMs);const selected=item.id===selectedItemId;const frame=box(item,state,selected,interactive);const source=resolveSource?.(item)||item.sourceUrl||null;const inner:CSSProperties={width:"100%",height:"100%",overflow:"hidden",borderRadius:"inherit",opacity:animation.opacity,transform:animation.transform,transformOrigin:"center",transition:playing?"none":"transform .12s ease,opacity .12s ease"};let content:React.ReactNode=null;if(["video","presenter","image","logo","map","website"].includes(item.type))content=<MediaLayer item={item} timeMs={timeMs} playing={playing} playbackRate={playbackRate} source={source} style={inner} brand={brand} variables={variables}/>;else if(item.type==="shape")content=<div style={{...inner,background:item.backgroundColor||brand.accentColor,border:`${item.borderWidth||0}px solid ${item.borderColor||"transparent"}`,borderRadius:item.shape==="circle"?"50%":item.transform.borderRadius}}/>;else if(item.type==="text"||item.type==="metric")content=<div style={{...inner,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:item.textAlign==="center"?"center":item.textAlign==="right"?"flex-end":"flex-start",padding:"4% 6%",background:item.backgroundColor||"transparent",color:item.color||brand.textColor,fontFamily:item.fontFamily||brand.fontHeading,textAlign:item.textAlign||"left",border:`${item.borderWidth||0}px solid ${item.borderColor||"transparent"}`}}><span style={{fontSize:`${item.fontSize||36}px`,fontWeight:item.fontWeight||800,lineHeight:item.lineHeight||1.06}}>{resolveStudioV3Text(item.text||"",variables)}</span>{item.subtext?<span style={{fontSize:`${Math.max(14,(item.fontSize||36)*.58)}px`,fontWeight:650,marginTop:"3%",opacity:.76}}>{resolveStudioV3Text(item.subtext,variables)}</span>:null}</div>;if(!content)return null;return <div key={item.id} style={frame} onPointerDown={event=>beginMove(event,item)}>{content}{selected&&interactive&&!playing?<CanvasHandles onResize={(event,mode)=>beginResize(event,item,mode)}/>:null}</div>})}</div>}
