import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const H={"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*","access-control-allow-headers":"authorization, content-type"};
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
function env(){const url=Deno.env.get("SUPABASE_URL")||"";const pubs=Deno.env.get("SUPABASE_PUBLISHABLE_KEYS");const secs=Deno.env.get("SUPABASE_SECRET_KEYS");const publicKey=pubs?JSON.parse(pubs)?.default:Deno.env.get("SUPABASE_ANON_KEY");const secretKey=secs?JSON.parse(secs)?.default:Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!publicKey||!secretKey)throw new Error("Backend configuration missing");return{url,publicKey,secretKey}}
function admin(){const e=env();return createClient(e.url,e.secretKey,{auth:{persistSession:false,autoRefreshToken:false}})}
async function user(req:Request){const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)return null;const e=env();const c=createClient(e.url,e.publicKey,{auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await c.auth.getUser(token);return error?null:data.user}
async function integration(db:any,userId:string){const {data}=await db.from("energy_integrations").select("*").eq("user_id",userId).eq("provider","chatwoot").neq("status","disabled").maybeSingle();if(!data)throw new Error("Chatwoot ist noch nicht verbunden");const {data:s}=await db.rpc("energy_get_integration_secret",{p_integration_id:data.id,p_user_id:userId});return{row:data,secret:String(s||"")}}
function apiHeaders(secret:string){return{"content-type":"application/json","api_access_token":secret,"user-agent":"Walkenhorst-Energy-Radar/1.0"}}

Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:H});if(req.method!=="POST")return out({error:"Method not allowed"},405);
 try{
  const u=await user(req);if(!u)return out({error:"Nicht autorisiert"},401);const b=await req.json().catch(()=>({}));const action=String(b?.action||"");if(action!=="sync_lead")return out({error:"Unbekannte Aktion"},400);const db=admin();const {data:lead}=await db.from("energy_leads").select("*").eq("id",String(b?.leadId||"")).eq("user_id",u.id).maybeSingle();if(!lead)return out({error:"Lead nicht gefunden"},404);if(!lead.email&&!lead.phone)return out({error:"Lead braucht E-Mail oder Telefon für Chatwoot"},400);
  const i=await integration(db,u.id);const accountId=String((i.row.config as any)?.account_id||"").trim();if(!accountId)throw new Error("Chatwoot account_id fehlt in der Integration-Konfiguration");const root=String(i.row.base_url||"").replace(/\/$/,"");const headers=apiHeaders(i.secret);const q=encodeURIComponent(lead.email||lead.phone||lead.company_name);let contact:any=null;
  const search=await fetch(`${root}/api/v1/accounts/${accountId}/contacts/search?q=${q}`,{headers});if(search.ok){const p=await search.json().catch(()=>({}));contact=Array.isArray(p?.payload)?p.payload[0]:Array.isArray(p)?p[0]:null}
  const payload={name:lead.contact_name||lead.company_name,email:lead.email||undefined,phone_number:lead.phone||undefined,company_name:lead.company_name,custom_attributes:{walkenhorst_lead_id:lead.id,opportunity_score:lead.total_score,intent_score:lead.intent_score,energy_score:lead.energy_score,pv_score:lead.pv_score,source:lead.source||"radar"}};
  let response:Response;
  if(contact?.id)response=await fetch(`${root}/api/v1/accounts/${accountId}/contacts/${contact.id}`,{method:"PUT",headers,body:JSON.stringify(payload)});else response=await fetch(`${root}/api/v1/accounts/${accountId}/contacts`,{method:"POST",headers,body:JSON.stringify(payload)});
  const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result?.message||`Chatwoot HTTP ${response.status}`);const saved=result?.payload||result;const contactId=String(saved?.id||contact?.id||"");const context={...(lead.research_context||{}),chatwoot:{contact_id:contactId,synced_at:new Date().toISOString()}};await db.from("energy_leads").update({research_context:context,updated_at:new Date().toISOString()}).eq("id",lead.id).eq("user_id",u.id);await db.from("energy_activities").insert({user_id:u.id,lead_id:lead.id,activity_type:"chatwoot_sync",title:"Lead mit Chatwoot synchronisiert",detail:contactId?`Kontakt ${contactId}`:null});return out({ok:true,contact_id:contactId,contact:saved});
 }catch(e){return out({error:e instanceof Error?e.message.slice(0,800):"Chatwoot Sync fehlgeschlagen"},500)}
});
