import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const H={"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*","access-control-allow-headers":"authorization, x-client-info, apikey, content-type, x-worker-key","access-control-allow-methods":"POST, OPTIONS"};
const MEDIA_BUCKET="energy-media";
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
function env(){const url=Deno.env.get("SUPABASE_URL");const pubs=Deno.env.get("SUPABASE_PUBLISHABLE_KEYS");const secs=Deno.env.get("SUPABASE_SECRET_KEYS");const pub=pubs?JSON.parse(pubs)?.default:Deno.env.get("SUPABASE_ANON_KEY");const secret=secs?JSON.parse(secs)?.default:Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!pub||!secret)throw new Error("Backend configuration missing");return{url,pub,secret}}
function db(){const{url,secret}=env();return createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}})}
type DB=ReturnType<typeof db>;
async function auth(req:Request,admin:DB){const authorization=req.headers.get("authorization")||"";const token=authorization.toLowerCase().startsWith("bearer ")?authorization.slice(7).trim():"";if(token){const{url,pub}=env();const scoped=createClient(url,pub,{auth:{persistSession:false,autoRefreshToken:false}});const{data,error}=await scoped.auth.getUser(token);if(!error&&data.user){const owner=typeof data.user.app_metadata?.workspace_owner_id==="string"?data.user.app_metadata.workspace_owner_id.trim():"";return{ok:true as const,userId:owner||data.user.id,worker:false}}}const supplied=req.headers.get("x-worker-key")||"";if(supplied){const{data}=await admin.rpc("energy_get_system_secret",{p_name:"energy_worker_key"});if(data&&String(data)===supplied)return{ok:true as const,userId:null,worker:true}}return{ok:false as const,userId:null,worker:false}}
function slug(v:string){return String(v||"analyse").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,46)||"analyse"}
const TITLE=/^(herr|frau|hr\.?|fr\.?|dr\.?|prof\.?|professor|dipl\.?-?ing\.?|dipl\.?|ing\.?|mag\.?|mba|m\.?sc\.?|b\.?sc\.?|ph\.?d\.?)$/i;
function first(v:unknown){let raw=String(v||"").replace(/\s+/g," ").trim();if(!raw)return"Sie";if(raw.includes(",")){const parts=raw.split(",").map(x=>x.trim()).filter(Boolean);if(parts.length>1)raw=parts.slice(1).join(" ")}const tokens=raw.split(/\s+/).filter(Boolean);while(tokens.length&&TITLE.test(tokens[0].replace(/[,:;]+$/g,"")))tokens.shift();const candidate=(tokens[0]||"").replace(/^[^A-Za-zÀ-ÖØ-öø-ÿÄÖÜäöüß-]+|[^A-Za-zÀ-ÖØ-öø-ÿÄÖÜäöüß'-]+$/g,"");return candidate||"Sie"}
function deep(v:any,values:Record<string,string>):any{if(typeof v==="string")return Object.entries(values).reduce((s,[k,x])=>s.replaceAll(`{{${k}}}`,x),v);if(Array.isArray(v))return v.map(x=>deep(x,values));if(v&&typeof v==="object")return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,deep(x,values)]));return v}
function assetUrl(base:string,a:any){if(!a?.storage_path)return null;const bucket=String(a.storage_bucket||MEDIA_BUCKET);const path=String(a.storage_path).split("/").map(encodeURIComponent).join("/");return`${base.replace(/\/$/,"")}/storage/v1/object/public/${encodeURIComponent(bucket)}/${path}`}
function brand(row:any){return row?{id:row.id,name:row.name,websiteUrl:row.website_url||"",logoUrl:row.logo_url||"",logoAssetId:row.logo_asset_id||undefined,faviconUrl:row.favicon_url||undefined,portraitUrl:row.portrait_url||"",portraitAssetId:row.portrait_asset_id||undefined,primaryColor:row.primary_color,secondaryColor:row.secondary_color,accentColor:row.accent_color,backgroundColor:row.background_color,surfaceColor:row.surface_color,textColor:row.text_color,mutedTextColor:row.muted_text_color,buttonTextColor:row.button_text_color,fontHeading:row.font_heading,fontBody:row.font_body,radiusPx:row.radius_px,shadowStyle:row.shadow_style,defaultCtaLabel:row.default_cta_label,defaultCtaUrl:row.default_cta_url,trustHeadline:row.trust_headline,trustBody:row.trust_body,contactName:row.contact_name,contactPhone:row.contact_phone||"",contactEmail:row.contact_email||"",metadata:row.metadata||{}}:{name:"Walkenhorst Energie",websiteUrl:"https://walkenhorst-energie.de/",logoUrl:"",portraitUrl:"",primaryColor:"#111111",secondaryColor:"#F4F1EA",accentColor:"#D5A62B",backgroundColor:"#FFFFFF",surfaceColor:"#F7F5F0",textColor:"#151515",mutedTextColor:"#6F716F",buttonTextColor:"#FFFFFF",fontHeading:"Arial, Helvetica, sans-serif",fontBody:"Arial, Helvetica, sans-serif",radiusPx:12,shadowStyle:"soft",defaultCtaLabel:"Termin über WhatsApp anfragen",defaultCtaUrl:"https://wa.me/4916092414766",trustHeadline:"Ihre Energiezukunft ist meine Expertise.",trustBody:"Persönliche Energieberatung.",contactName:"Andreas Walkenhorst",contactPhone:"",contactEmail:"",metadata:{}}}
function collectAssetIds(raw:any){const ids=new Set<string>();const bindings=raw?.bindings&&typeof raw.bindings==="object"?raw.bindings:{};for(const value of Object.values(bindings))if(typeof value==="string"&&value)ids.add(value);for(const track of raw?.timeline?.tracks||[])for(const item of track?.items||[])if(typeof item?.assetId==="string"&&item.assetId)ids.add(item.assetId);return ids}
async function globalMaster(admin:DB,userId:string,templateKey:string){const{data,error}=await admin.from("energy_studio_configs").select("id,config,brand_kit_id,autosave_revision,published_revision,template_key,name").eq("user_id",userId).eq("scope","global").is("lead_id",null).eq("template_key",templateKey).order("updated_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;if(!data?.config)throw new Error(`Globaler Studio-Master ${templateKey} fehlt.`);if(templateKey==="energiekosten"&&Number(data.published_revision||0)!==Number(data.autosave_revision||0))throw new Error(`Golden Master ${templateKey} Rev ${data.autosave_revision} ist noch nicht veröffentlicht.`);return data}
function sharpCapture(row:any){const meta=row?.metadata||{};const width=Number(meta.capture_width||meta?.dimensions?.width||0);return width>=1920||String(meta.capture_mode||"")==="viewport_1920x1080"||String(meta.capture_mode||"")==="fullpage_1920"}
async function staticWebsiteCapture(admin:DB,userId:string,leadId:string){const{data,error}=await admin.from("energy_media_assets").select("id,storage_bucket,storage_path,created_at,metadata").eq("user_id",userId).eq("kind","website_capture").contains("metadata",{lead_id:leadId}).order("created_at",{ascending:false}).limit(8);if(error)throw error;const best=(data||[]).find(sharpCapture);return best?assetUrl(env().url!,best):null}
function tr(x=0,y=0,width=100,height=100,borderRadius=0){return{x,y,width,height,rotation:0,opacity:1,borderRadius,scale:1}}
function enforceEnergiekostenLoom(timeline:any,captureUrl:string,presenterUrl:string){const duration=Math.max(1000,Number(timeline?.durationMs||107000));const bg={id:"track-bg",name:"Unternehmenswebsite",type:"background",zIndex:10,locked:false,hidden:false,color:"#0A2740",items:[{id:"website-personalized-master",type:"website",label:"Echte Unternehmenswebsite",trackId:"track-bg",startMs:0,endMs:duration,zIndex:10,dynamicSource:"website_capture",sourceUrl:captureUrl,fit:"cover",volume:1,playbackRate:1,shadow:"none",transition:"cut",animationIn:"none",animationOut:"none",animationDurationMs:0,transform:tr(),keyframes:[{atMs:0,scrollY:0,scale:1},{atMs:Math.round(duration*.15),scrollY:8,scale:1.015},{atMs:Math.round(duration*.32),scrollY:24,scale:1.025},{atMs:Math.round(duration*.49),scrollY:42,scale:1.03},{atMs:Math.round(duration*.66),scrollY:58,scale:1.025},{atMs:Math.round(duration*.82),scrollY:72,scale:1.015},{atMs:duration-100,scrollY:84,scale:1}]}]};const presenter={id:"track-presenter",name:"Andreas / Sprecher",type:"presenter",zIndex:70,locked:false,hidden:false,color:"#3BC9A6",items:[{id:"presenter-b2b-bubble",type:"presenter",label:"Andreas Walkenhorst · B2B",trackId:"track-presenter",startMs:0,endMs:duration,zIndex:72,dynamicSource:"presenter",sourceUrl:presenterUrl,fit:"cover",volume:1,playbackRate:1,shadow:"strong",transition:"cut",animationIn:"fade",animationOut:"fade",animationDurationMs:220,metadata:{mode:"bubble",audience:"b2b"},transform:tr(82.5,69,13.5,24,999)}]};const existing=Array.isArray(timeline?.tracks)?timeline.tracks:[];const overlay=existing.find((t:any)=>t?.id==="track-overlays"||t?.type==="overlay");const safeOverlay={...(overlay||{id:"track-overlays",name:"Kurze Analyse-Hinweise",type:"overlay",zIndex:60,locked:false,hidden:false,color:"#6B7280"}),items:(overlay?.items||[]).filter((i:any)=>["text","metric","shape"].includes(String(i?.type||"")))};const other=existing.filter((t:any)=>!["track-bg","track-presenter",safeOverlay.id].includes(String(t?.id||""))&&!["background","presenter"].includes(String(t?.type||""))).map((t:any)=>({...t,items:(t.items||[]).filter((i:any)=>!["image","video","website","presenter"].includes(String(i?.type||"")))}));return{...timeline,version:3,durationMs:duration,width:1920,height:1080,aspectRatio:"16:9",tracks:[bg,presenter,safeOverlay,...other]}}
async function prepare(admin:DB,userId:string,leadId:string,baseUrl:string,templateKey="energiekosten"){
 const{data:lead,error:le}=await admin.from("energy_leads").select("*").eq("id",leadId).eq("user_id",userId).maybeSingle();if(le||!lead)throw le||new Error("Lead nicht gefunden");if(templateKey==="energiekosten"&&!String(lead.website||"").trim())throw new Error("Website fehlt. Lead wird nicht veröffentlicht, weil kein personalisierter Website-Screenshot möglich ist.");
 const cfg=await globalMaster(admin,userId,templateKey);const raw:any=structuredClone(cfg.config);if(raw.version!==3||!raw.timeline?.tracks)throw new Error("Studio V3 Golden Master erforderlich");const rev=Number(cfg.autosave_revision||0);
 const[{data:site},{data:brandRow},staticCapture]=await Promise.all([admin.from("energy_site_intelligence").select("*").eq("lead_id",leadId).eq("user_id",userId).maybeSingle(),cfg.brand_kit_id?admin.from("energy_brand_kits").select("*").eq("id",cfg.brand_kit_id).eq("user_id",userId).maybeSingle():Promise.resolve({data:null}),staticWebsiteCapture(admin,userId,leadId)]);
 const b=brand(brandRow);const values={firstname:first(lead.contact_name),company:String(lead.company_name||"Unternehmen"),website:String(lead.website||"Unternehmenswebsite"),city:String(lead.city||"Ihrer Region"),industry:String(lead.industry||"Unternehmen"),problem:String(lead.next_action||lead.summary||"Energie- und PV-Potenzial"),opportunity:String(lead.total_score??"–"),roof_area:String(site?.roof_area_m2??lead.roof_area_m2??"–"),pv_kwp:String(site?.estimated_capacity_kwp??"–"),pv_yield:String(site?.estimated_annual_generation_kwh??"–"),energy_score:String(lead.energy_score??"–"),saving_estimate:"–",cta:String(b.defaultCtaLabel||"Termin über WhatsApp anfragen")};
 const ids=collectAssetIds(raw);const{data:assets,error:ae}=ids.size?await admin.from("energy_media_assets").select("id,storage_bucket,storage_path,mime_type,kind,metadata,label").eq("user_id",userId).in("id",Array.from(ids)):{data:[],error:null};if(ae)throw ae;const amap=new Map((assets||[]).map((a:any)=>[a.id,a]));const supabaseBase=env().url!;const bindings=raw.bindings&&typeof raw.bindings==="object"?raw.bindings:{};const bound=(k:string)=>assetUrl(supabaseBase,amap.get(bindings[k]));
 const presenter=amap.get(bindings.presenterAssetId);if(templateKey==="energiekosten"&&(!presenter||presenter.kind!=="video"||String(presenter?.metadata?.audience||"")!=="b2b"||presenter?.metadata?.approved===false))throw new Error("B2B-Presenter ist nicht freigegeben. Veröffentlichung blockiert.");
 const{data:existing}=await admin.from("energy_video_pages").select("id,slug,rendered_video_url,studio_revision,template_key").eq("user_id",userId).eq("lead_id",leadId).eq("template_key",templateKey).in("status",["ready","sent"]).order("updated_at",{ascending:false}).limit(1).maybeSingle();const pageSlug=existing?.slug||`${slug(lead.company_name)}-${crypto.randomUUID().slice(0,6)}`;const liveCapture=`${baseUrl}/api/public/studio-capture/${encodeURIComponent(pageSlug)}?v=${encodeURIComponent(String(rev||1))}`;const captureUrl=templateKey==="energiekosten"?liveCapture:(staticCapture||liveCapture);
 let timeline=deep(raw.timeline,values);timeline.tracks=(timeline.tracks||[]).map((t:any)=>({...t,items:(t.items||[]).map((i:any)=>{let source:string|null=i.sourceUrl||null;if(i.assetId)source=assetUrl(supabaseBase,amap.get(i.assetId))||source;if(i.dynamicSource==="presenter")source=bound("presenterAssetId")||source;if(i.dynamicSource==="website_capture"||i.type==="website")source=captureUrl;if(i.dynamicSource==="logo")source=bound("logoAssetId")||b.logoUrl||source;if(i.dynamicSource==="portrait")source=bound("portraitAssetId")||b.portraitUrl||source;if(i.dynamicSource==="map")source=bound("mapAssetId")||source;return{...i,...(source?{sourceUrl:source}:{})}})}));if(templateKey==="energiekosten")timeline=enforceEnergiekostenLoom(timeline,captureUrl,bound("presenterAssetId")||"");
 const unresolved=timeline.tracks.flatMap((t:any)=>t.items||[]).filter((i:any)=>["image","video","presenter","website"].includes(i.type)&&!i.sourceUrl);if(unresolved.length)throw new Error(`Golden Master enthält ${unresolved.length} nicht aufgelöste Pflicht-Assets.`);
 const landing=deep(raw.landing||{version:3,theme:"walkenhorst",showLogo:true,stickyCta:true,blocks:[]},values);const hero=(landing.blocks||[]).find((x:any)=>x.type==="hero");const signals=Array.isArray(lead?.research_context?.firecrawl?.signals)?lead.research_context.firecrawl.signals:[];const bullets=[`${lead.pv_score||0}/100 PV-Potenzial`,`${lead.energy_score||0}/100 Energieeffizienz-Potenzial`,...signals.slice(0,2),lead.summary||lead.next_action||"Individueller Energie-Potenzialcheck"].filter(Boolean).slice(0,5);
 const payload:any={company_name:lead.company_name,prospect_name:lead.contact_name,website_url:lead.website,presenter_video_url:bound("presenterAssetId"),website_capture_url:captureUrl,thumbnail_url:captureUrl,headline:hero?.headline||`Ihre persönliche Energieanalyse für ${lead.company_name}.`,intro_text:hero?.body||lead.summary,bullets,cta_label:b.defaultCtaLabel,cta_url:b.defaultCtaUrl,duration_seconds:Math.max(1,Math.round(Number(timeline.durationMs||107000)/1000)),status:"ready",is_public:true,studio_config:{...raw,version:3},timeline_v3:timeline,landing_config:landing,brand_kit_snapshot:b,accent_color:b.accentColor||"#D5A62B",template_key:templateKey,studio_revision:rev,updated_at:new Date().toISOString()};if(!existing?.rendered_video_url||Number(existing.studio_revision||0)!==rev)Object.assign(payload,{rendered_video_url:null,rendered_video_format:null,rendered_at:null});
 let pageId:string;if(existing){const r=await admin.from("energy_video_pages").update(payload).eq("id",existing.id).eq("user_id",userId).select("id").single();if(r.error)throw r.error;pageId=r.data.id}else{const r=await admin.from("energy_video_pages").insert({user_id:userId,lead_id:leadId,slug:pageSlug,...payload}).select("id").single();if(r.error)throw r.error;pageId=r.data.id}const usedStatic=captureUrl===staticCapture;return{leadId,pageId,slug:pageSlug,url:`${baseUrl}/v/${pageSlug}`,templateKey,studioRevision:rev,captureMode:usedStatic?"static_1080p":"live_1080p",presenterAudience:String(presenter?.metadata?.audience||"")}}
async function prepareCampaign(admin:DB,campaign:any,baseUrl:string,limit:number){const templateKey=String(campaign?.lead_filter?.studio_template_key||"energiekosten").trim()||"energiekosten";const{data:members,error}=await admin.from("energy_campaign_members").select("lead_id").eq("campaign_id",campaign.id).eq("status","queued").limit(limit);if(error)throw error;const results:any[]=[];const rows=members||[];for(let i=0;i<rows.length;i+=5){const batch=rows.slice(i,i+5);const settled=await Promise.all(batch.map(async(m:any)=>{try{return await prepare(admin,campaign.user_id,m.lead_id,baseUrl,templateKey)}catch(e){return{leadId:m.lead_id,error:e instanceof Error?e.message:"Fehler"}}}));results.push(...settled)}return{templateKey,prepared:results.filter(x=>!x.error).length,failed:results.filter(x=>x.error).length,staticCaptures:results.filter(x=>x.captureMode==="static_1080p").length,liveCaptures:results.filter(x=>x.captureMode==="live_1080p").length,results}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:H});if(req.method!=="POST")return reply({error:"Method not allowed"},405);const admin=db();try{const a=await auth(req,admin);if(!a.ok)return reply({error:"Nicht autorisiert"},401);const body=await req.json().catch(()=>({}));const action=String(body.action||"prepare_lead");const baseUrl=String(body.baseUrl||"https://walkenhorst.vercel.app").replace(/\/$/,"");if(!/^https:\/\//i.test(baseUrl))return reply({error:"Ungültige Base URL"},400);if(action==="prepare_campaign"){const campaignId=String(body.campaignId||"").trim();if(!campaignId)return reply({error:"campaignId fehlt"},400);const{data:campaign,error}=await admin.from("energy_campaigns").select("id,user_id,lead_filter,include_video").eq("id",campaignId).maybeSingle();if(error||!campaign)return reply({error:"Kampagne nicht gefunden"},404);if(a.userId&&a.userId!==campaign.user_id)return reply({error:"Nicht autorisiert"},403);const limit=Math.max(1,Math.min(500,Number(body.limit)||100));return reply({ok:true,...await prepareCampaign(admin,campaign,baseUrl,limit)})}const leadId=String(body.leadId||"").trim();if(!leadId)return reply({error:"leadId fehlt"},400);let userId=a.userId;if(!userId){const row=(await admin.from("energy_leads").select("user_id").eq("id",leadId).maybeSingle()).data;if(!row)return reply({error:"Lead nicht gefunden"},404);userId=row.user_id}const requested=String(body.templateKey||"energiekosten").trim()||"energiekosten";return reply({ok:true,...await prepare(admin,userId,leadId,baseUrl,requested)})}catch(e){return reply({error:e instanceof Error?e.message.slice(0,700):"Publish failed"},500)}});
