import { NextRequest, NextResponse } from "next/server";
import { lookup } from "node:dns/promises";
import net from "node:net";

export const runtime="nodejs";
export const dynamic="force-dynamic";
const MAX=2_000_000;

function normalize(input:string){const raw=input.trim();if(!raw)throw new Error("Bitte eine URL eingeben.");const url=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`);if(!["http:","https:"].includes(url.protocol))throw new Error("Nur HTTP/HTTPS ist erlaubt.");if(url.username||url.password)throw new Error("URLs mit Zugangsdaten sind nicht erlaubt.");url.hash="";return url;}
function private4(ip:string){const p=ip.split(".").map(Number);if(p.length!==4||p.some(Number.isNaN))return true;const[a,b]=p;return a===10||a===127||a===0||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===100&&b>=64&&b<=127)||a>=224;}
function private6(ip:string){const v=ip.toLowerCase();return v==="::1"||v==="::"||v.startsWith("fc")||v.startsWith("fd")||v.startsWith("fe8")||v.startsWith("fe9")||v.startsWith("fea")||v.startsWith("feb");}
async function publicUrl(url:URL){const host=url.hostname.toLowerCase();if(host==="localhost"||host.endsWith(".local")||host.endsWith(".internal"))throw new Error("Interne Ziele sind nicht erlaubt.");const literal=net.isIP(host);if(literal===4&&private4(host))throw new Error("Private IP nicht erlaubt.");if(literal===6&&private6(host))throw new Error("Private IP nicht erlaubt.");if(!literal){const records=await lookup(host,{all:true,verbatim:true}).catch(()=>[]);if(!records.length)throw new Error("Domain konnte nicht aufgelöst werden.");for(const r of records){if(r.family===4&&private4(r.address))throw new Error("Interne Zieladresse blockiert.");if(r.family===6&&private6(r.address))throw new Error("Interne Zieladresse blockiert.");}}}
async function safeFetch(start:URL){let current=new URL(start);for(let i=0;i<5;i++){await publicUrl(current);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);let r:Response;try{r=await fetch(current,{redirect:"manual",cache:"no-store",signal:controller.signal,headers:{"user-agent":"Walkenhorst-Radar-Audit/1.0","accept":"text/html,application/xhtml+xml"}});}finally{clearTimeout(timer);}if([301,302,303,307,308].includes(r.status)){const loc=r.headers.get("location");if(!loc) return {r,url:current};current=new URL(loc,current);continue;}return{r,url:current};}throw new Error("Zu viele Weiterleitungen.");}
const has=(html:string,re:RegExp)=>re.test(html);
const count=(html:string,re:RegExp)=>html.match(re)?.length??0;
function score(base:number,tests:{ok:boolean,weight:number}[]){let s=base;for(const t of tests)s+=t.ok?t.weight:-Math.round(t.weight*.55);return Math.max(0,Math.min(100,Math.round(s)));}
export async function POST(req:NextRequest){try{const body=await req.json().catch(()=>({}));const requested=normalize(String(body?.url||""));const start=Date.now();const {r,url}=await safeFetch(requested);const ms=Date.now()-start;const type=r.headers.get("content-type")||"";if(!type.includes("text/html")&&!type.includes("application/xhtml+xml"))throw new Error("Ziel liefert keine HTML-Webseite.");const declared=Number(r.headers.get("content-length")||0);if(declared>MAX)throw new Error("Seite ist für den Schnell-Audit zu groß.");const html=await r.text();if(Buffer.byteLength(html,"utf8")>MAX)throw new Error("Seite ist für den Schnell-Audit zu groß.");
const title=(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"").replace(/<[^>]+>/g,"").trim();const desc=html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)/i)?.[1]||html.match(/<meta[^>]+content=["']([^"']*)["'][^>]+name=["']description["']/i)?.[1]||"";const h1=count(html,/<h1\b/gi);const imgs=count(html,/<img\b/gi);const alt=count(html,/<img\b[^>]*\balt=["'][^"']*["']/gi);const forms=count(html,/<form\b/gi);const buttons=count(html,/<button\b|class=["'][^"']*(?:btn|button|cta)[^"']*["']/gi);const schema=has(html,/application\/ld\+json/i);const canonical=has(html,/rel=["']canonical["']/i);const viewport=has(html,/name=["']viewport["']/i);const lang=has(html,/<html[^>]+lang=/i);const og=has(html,/property=["']og:(?:title|description|image)["']/i);const phone=has(html,/(tel:|\+49|0\d{2,5}[\s/-]\d+)/i);const email=has(html,/mailto:/i);const trust=has(html,/(bewertung|referenz|kundenstimme|zertifikat|tüv|google.{0,20}review|erfahrung)/i);const privacy=has(html,/(datenschutz|privacy)/i);const imprint=has(html,/(impressum|legal notice)/i);const cta=has(html,/(angebot|termin|beratung|anfragen|kontakt|jetzt|kostenlos)/i);const https=url.protocol==="https:";const fast=ms<1200;const statusOk=r.ok;
const seo=score(55,[{ok:title.length>=25&&title.length<=65,weight:10},{ok:desc.length>=80&&desc.length<=170,weight:9},{ok:h1===1,weight:9},{ok:canonical,weight:6},{ok:schema,weight:6},{ok:og,weight:4},{ok:lang,weight:4}]);const conversion=score(48,[{ok:cta,weight:15},{ok:buttons>=2,weight:8},{ok:forms>=1,weight:9},{ok:phone||email,weight:8},{ok:trust,weight:12}]);const trustScore=score(52,[{ok:https,weight:12},{ok:trust,weight:12},{ok:privacy,weight:8},{ok:imprint,weight:8},{ok:phone||email,weight:6}]);const technical=score(55,[{ok:statusOk,weight:12},{ok:https,weight:8},{ok:viewport,weight:8},{ok:fast,weight:10},{ok:imgs===0||alt/imgs>=.8,weight:7}]);const total=Math.round(seo*.28+conversion*.3+trustScore*.2+technical*.22);
const findings:{severity:string;title:string;detail:string;recommendation:string}[]=[];const add=(severity:string,title:string,detail:string,recommendation:string)=>findings.push({severity,title,detail,recommendation});if(!title||title.length<25)add("high","Seitentitel zu schwach","Der Title ist leer oder sehr kurz.","Klaren, suchorientierten Title mit Leistung + Nutzen + Region formulieren.");if(!desc||desc.length<80)add("medium","Meta Description ausbaufähig","Die Suchergebnis-Vorschau kommuniziert den Nutzen nicht ausreichend.","80–170 Zeichen mit Nutzen, Differenzierung und Handlungsimpuls nutzen.");if(h1!==1)add("high","H1-Struktur nicht sauber",`Gefundene H1: ${h1}.`,"Genau eine klare Hauptüberschrift pro Seite verwenden.");if(!cta)add("high","Conversion-Signal fehlt","Kein klarer Handlungsimpuls wurde zuverlässig erkannt.","Primären CTA prominent Above-the-Fold und wiederholt im Seitenverlauf einsetzen.");if(!trust)add("high","Zu wenig sichtbarer Vertrauensbeweis","Referenzen, Bewertungen oder Zertifikate sind nicht deutlich erkennbar.","Social Proof, Referenzen und konkrete Ergebnisbelege näher an die Kaufentscheidung bringen.");if(!schema)add("medium","Keine strukturierten Daten erkannt","JSON-LD wurde nicht gefunden.","Passende Organization/LocalBusiness/Service-Schemata ergänzen.");if(imgs>0&&alt/imgs<.8)add("medium","Bild-SEO/Accessibility unvollständig",`${alt} von ${imgs} Bildern haben ein erkanntes Alt-Attribut.`,"Aussagekräftige Alt-Texte für informative Bilder ergänzen.");if(!fast)add("medium","Serverantwort langsam",`HTML-Antwort nach ca. ${ms} ms.`,"Hosting, Caching und Server-Rendering prüfen; anschließend Core Web Vitals messen.");if(!privacy||!imprint)add("medium","Rechtliche Trust-Signale prüfen","Datenschutz oder Impressum wurden nicht zuverlässig erkannt.","Rechtliche Pflichtseiten klar verlinken und technisch erreichbar halten.");if(findings.length===0)add("low","Solide Basis","Im Schnell-Audit wurden keine gravierenden Basisfehler erkannt.","Als Nächstes Conversion, Core Web Vitals und Wettbewerber im Detail benchmarken.");
const summary=total>=80?"Die Website hat eine solide digitale Basis. Die größten Hebel liegen voraussichtlich in Conversion-Optimierung und datenbasierter Wettbewerbsdifferenzierung.":total>=60?"Die Website funktioniert grundsätzlich, verschenkt aber an mehreren Stellen Sichtbarkeit, Vertrauen oder Conversion-Potenzial.":"Die Website weist mehrere klare Wachstumshebel auf. Besonders Struktur, Vertrauen, Conversion und technische Grundlagen sollten priorisiert verbessert werden.";return NextResponse.json({url:url.toString(),responseMs:ms,status:r.status,title,score:total,seo,conversion,trust:trustScore,technical,findings:findings.slice(0,10),summary},{headers:{"cache-control":"no-store"}});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Website-Audit fehlgeschlagen."},{status:400});}}
