"use client";

import { FormEvent, useCallback, useDeferredValue, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";
import { scoreEnergyLead } from "@/lib/energy-score";
import styles from "./lead-crm.module.css";

type CustomerType="commercial"|"private";type LeadStatus="new"|"research"|"ready"|"contacted"|"engaged"|"qualified"|"meeting"|"proposal"|"won"|"lost"|"nurture";
type Lead={id:string;company_name:string;contact_name:string|null;email:string|null;phone:string|null;website:string|null;city:string|null;postcode:string|null;address:string|null;industry:string|null;status:LeadStatus;customer_type:CustomerType;total_score:number;intent_score:number;next_action:string|null;next_action_at:string|null;do_not_contact:boolean;updated_at:string};
type Workflow={lead_id:string;contact_count:number;enrichment_status:string|null;page_ready:boolean;video_ready:boolean;email_draft_ready:boolean;email_reviewed:boolean;email_sent:boolean;email_opened:boolean;email_clicked:boolean;page_viewed:boolean;video_played:boolean;max_watch_percent:number;cta_clicked:boolean;replied:boolean;workflow_stage:number;workflow_stage_label:string;recommended_action:string|null;workflow_percent:number;video_page_slug:string|null;rendered_video_url:string|null};
type CrmRow=Lead&{workflow?:Workflow};type BulkState={label:string;done:number;total:number;failed:number};
const STATUS_LABEL:Record<LeadStatus,string>={new:"Neu",research:"Research",ready:"Bereit",contacted:"Kontaktiert",engaged:"Interessiert",qualified:"Qualifiziert",meeting:"Termin",proposal:"Angebot",won:"Gewonnen",lost:"Verloren",nurture:"Wiedervorlage"};
const STATUS_OPTIONS=Object.entries(STATUS_LABEL) as Array<[LeadStatus,string]>;const PAGE_SIZE=35;const LEAD_FIELDS="id,company_name,contact_name,email,phone,website,city,postcode,address,industry,status,customer_type,total_score,intent_score,next_action,next_action_at,do_not_contact,updated_at";const FLOW_FIELDS="lead_id,contact_count,enrichment_status,page_ready,video_ready,email_draft_ready,email_reviewed,email_sent,email_opened,email_clicked,page_viewed,video_played,max_watch_percent,cta_clicked,replied,workflow_stage,workflow_stage_label,recommended_action,workflow_percent,video_page_slug,rendered_video_url";const FLOW_STEPS=["Lead","Enrichment","Landingpage","Video","Entwurf","Prüfung","Versand","Engagement"];
function formatDate(value:string|null|undefined){if(!value)return"—";try{return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}catch{return"—"}}
function initials(value:string){return value.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]?.toUpperCase()).join("")||"WH"}
function searchable(row:CrmRow){return[row.company_name,row.contact_name,row.email,row.phone,row.website,row.city,row.postcode,row.address,row.industry,row.next_action,STATUS_LABEL[row.status],row.workflow?.workflow_stage_label,row.workflow?.recommended_action].filter(Boolean).join(" ").toLowerCase()}
function stageIndex(w?:Workflow){if(!w)return 0;return Math.max(0,Math.min(7,Number(w.workflow_stage||1)-1))}
function hasGateProblem(row:CrmRow){const w=row.workflow;return Boolean(w?.email_sent&&!w.video_ready)||Boolean(row.do_not_contact&&w?.email_sent)}
function engagement(row:CrmRow){const w=row.workflow;if(!w)return{label:"Noch kein Signal",tone:"muted",value:"—"};if(w.replied)return{label:"Antwort erhalten",tone:"hot",value:"Reply"};if(w.cta_clicked)return{label:"CTA geklickt",tone:"hot",value:"CTA"};if((w.max_watch_percent||0)>=90)return{label:"Video fast komplett",tone:"hot",value:`${w.max_watch_percent}%`};if((w.max_watch_percent||0)>=50)return{label:"Video angesehen",tone:"warm",value:`${w.max_watch_percent}%`};if(w.video_played)return{label:"Video gestartet",tone:"warm",value:"Play"};if(w.page_viewed)return{label:"Landingpage besucht",tone:"warm",value:"View"};if(w.email_clicked)return{label:"Mail-Link geklickt",tone:"warm",value:"Click"};if(w.email_opened)return{label:"E-Mail geöffnet",tone:"cool",value:"Open"};return{label:"Noch kein Signal",tone:"muted",value:"—"}}
function nextAction(row:CrmRow){if(hasGateProblem(row))return"Versand prüfen";return row.workflow?.recommended_action||row.next_action||"Lead prüfen"}
function SearchIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/></svg>}function PlusIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>}function ArrowIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 6 6 6-6 6"/></svg>}

export function LeadCrm({customerType}:{customerType:CustomerType}){
  const router=useRouter();const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const searchRef=useRef<HTMLInputElement|null>(null);const[userId,setUserId]=useState<string|null>(null);const[rows,setRows]=useState<CrmRow[]>([]);const[selected,setSelected]=useState<Set<string>>(new Set());const[search,setSearch]=useState("");const deferredSearch=useDeferredValue(search);const[statusFilter,setStatusFilter]=useState<"all"|LeadStatus>("all");const[stageFilter,setStageFilter]=useState("all");const[page,setPage]=useState(0);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[bulk,setBulk]=useState<BulkState|null>(null);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);const[createOpen,setCreateOpen]=useState(false);
  const isCommercial=customerType==="commercial";const label=isCommercial?"Gewerbe CRM":"Privatkunden CRM";const singular=isCommercial?"Gewerbe-Lead":"Privatkunden-Lead";
  const load=useCallback(async()=>{if(!supabase)return;setLoading(true);setError(null);try{const session=(await supabase.auth.getSession()).data.session;if(!session)throw new Error("Session abgelaufen. Bitte neu anmelden.");setUserId(session.user.id);const[leadResult,flowResult]=await Promise.all([supabase.from("energy_leads").select(LEAD_FIELDS).eq("user_id",session.user.id).eq("customer_type",customerType).order("updated_at",{ascending:false}).limit(1200),supabase.from("energy_crm_lead_workflow").select(FLOW_FIELDS).eq("user_id",session.user.id).limit(2500)]);if(leadResult.error)throw leadResult.error;const flowMap=new Map<string,Workflow>();if(!flowResult.error)for(const item of(flowResult.data||[]) as Workflow[])flowMap.set(item.lead_id,item);setRows(((leadResult.data||[]) as Lead[]).map(lead=>({...lead,workflow:flowMap.get(lead.id)})))}catch(e){setError(e instanceof Error?e.message:"CRM konnte nicht geladen werden.")}finally{setLoading(false)}},[customerType,supabase]);
  useEffect(()=>{void load()},[load]);useEffect(()=>setPage(0),[deferredSearch,statusFilter,stageFilter]);useEffect(()=>{const onKey=(event:KeyboardEvent)=>{const target=event.target as HTMLElement|null;if(event.key==="/"&&!event.metaKey&&!event.ctrlKey&&!event.altKey&&!['INPUT','TEXTAREA','SELECT'].includes(target?.tagName||"")){event.preventDefault();searchRef.current?.focus()}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);useEffect(()=>{const handler=(event:Event)=>{const d=(event as CustomEvent<{job?:{status?:string}}>).detail;if(d?.job&&["completed","failed"].includes(String(d.job.status)))void load()};window.addEventListener("walkenhorst:render-job",handler);return()=>window.removeEventListener("walkenhorst:render-job",handler)},[load]);
  const filtered=useMemo(()=>{const q=deferredSearch.trim().toLowerCase();return rows.filter(row=>{if(statusFilter!=="all"&&row.status!==statusFilter)return false;if(stageFilter!=="all"&&String(stageIndex(row.workflow))!==stageFilter)return false;return!q||searchable(row).includes(q)})},[rows,deferredSearch,statusFilter,stageFilter]);const sorted=useMemo(()=>[...filtered].sort((a,b)=>{const ah=hasGateProblem(a)?10000:0,bh=hasGateProblem(b)?10000:0;const ae=engagement(a).tone==="hot"?4000:engagement(a).tone==="warm"?2000:0;const be=engagement(b).tone==="hot"?4000:engagement(b).tone==="warm"?2000:0;return(bh+be+b.intent_score)-(ah+ae+a.intent_score)}),[filtered]);const pageCount=Math.max(1,Math.ceil(sorted.length/PAGE_SIZE)),safePage=Math.min(page,pageCount-1),visible=sorted.slice(safePage*PAGE_SIZE,safePage*PAGE_SIZE+PAGE_SIZE);const metrics=useMemo(()=>rows.reduce((a,row)=>{const w=row.workflow;a.enrichment+=!w||!w.enrichment_status||w.enrichment_status==="pending"?1:0;a.production+=w?.page_ready&&w?.video_ready?1:0;a.review+=w?.email_draft_ready&&!w?.email_reviewed?1:0;a.hot+=row.intent_score>=70||engagement(row).tone==="hot"?1:0;a.risk+=hasGateProblem(row)?1:0;return a},{enrichment:0,production:0,review:0,hot:0,risk:0}),[rows]);const priority=useMemo(()=>sorted.filter(r=>hasGateProblem(r)||engagement(r).tone==="hot"||r.intent_score>=70).slice(0,4),[sorted]);const allVisibleSelected=visible.length>0&&visible.every(row=>selected.has(row.id));function toggle(id:string){setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}function toggleVisible(){setSelected(current=>{const next=new Set(current);visible.forEach(row=>allVisibleSelected?next.delete(row.id):next.add(row.id));return next})}

  async function bulkAction(action:"enrich"|"prepare_page"|"render"|"create_draft"){if(!supabase||!selected.size||bulk)return;const ids=Array.from(selected),labels={enrich:"Enrichment",prepare_page:"Landingpages",render:"Videos",create_draft:"E-Mail-Entwürfe"};setBulk({label:labels[action],done:0,total:ids.length,failed:0});setError(null);setNotice(null);try{if(action==="render"){const result=await supabase.functions.invoke("crm-render-queue",{body:{action:"bulk_queue",leadIds:ids}});if(result.error)throw new Error(result.error.message||"Render-Queue fehlgeschlagen.");if((result.data as any)?.error)throw new Error((result.data as any).error);const data=result.data as any;const done=Number(data?.queued||0)+Number(data?.skipped||0)+Number(data?.failed||0),failed=Number(data?.failed||0);setBulk({label:labels[action],done,total:ids.length,failed});setNotice(`${data?.queued||0} Videos in die automatische Render-Queue gelegt · ${data?.skipped||0} bereits erledigt/eingeplant · ${failed} Fehler.`);window.dispatchEvent(new Event("walkenhorst:render-queue-kick"))}else{let done=0,failed=0;for(let i=0;i<ids.length;i+=4){const chunk=ids.slice(i,i+4);await Promise.all(chunk.map(async leadId=>{try{const result=await supabase.functions.invoke("crm-lead-workflow",{body:{action,leadId,baseUrl:window.location.origin}});if(result.error||(result.data as any)?.error)throw new Error(result.error?.message||(result.data as any)?.error||"Aktion fehlgeschlagen")}catch{failed++}finally{done++;setBulk({label:labels[action],done,total:ids.length,failed})}}))}setNotice(`${labels[action]} abgeschlossen: ${done-failed}/${ids.length} erfolgreich${failed?` · ${failed} mit Blocker`:""}.`)}await load();window.setTimeout(()=>setBulk(null),1800)}catch(e){setError(e instanceof Error?e.message:"Bulk-Aktion fehlgeschlagen.");setBulk(null)}}
  async function createLead(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!supabase||!userId)return;const f=new FormData(event.currentTarget);const company=String(f.get("company_name")||"").trim();const contact=String(f.get("contact_name")||"").trim();const displayName=isCommercial?company:contact;if(!displayName){setError(isCommercial?"Unternehmensname fehlt.":"Name fehlt.");return}const website=String(f.get("website")||"").trim()||null,city=String(f.get("city")||"").trim()||null,industry=isCommercial?(String(f.get("industry")||"").trim()||null):"Privathaushalt",email=String(f.get("email")||"").trim().toLowerCase()||null,phone=String(f.get("phone")||"").trim()||null;const scores=scoreEnergyLead({company_name:displayName,website,city,industry,employees:null,location_count:1,roof_area_m2:null,annual_energy_kwh:null,pv_present:null,contact_name:contact||null,phone,email});setBusy(true);setError(null);try{const insert=await supabase.from("energy_leads").insert({user_id:userId,customer_type:customerType,company_name:displayName,contact_name:contact||(isCommercial?null:displayName),email,phone,website,city,postcode:String(f.get("postcode")||"").trim()||null,address:String(f.get("address")||"").trim()||null,industry,source:"manual",pv_score:scores.pvScore,energy_score:scores.energyScore,intent_score:scores.intentScore,contactability_score:scores.contactabilityScore,total_score:scores.totalScore,summary:scores.summary,pitch:scores.pitch,next_action:scores.nextAction,status:"research"}).select("id").single();if(insert.error)throw insert.error;setCreateOpen(false);setNotice(`${singular} angelegt – nächster Schritt: Enrichment.`);router.push(`/leads/${insert.data.id}`)}catch(e){setError(e instanceof Error?e.message:"Lead konnte nicht angelegt werden.")}finally{setBusy(false)}}
  async function deleteSelected(){if(!supabase||!userId||!selected.size)return;if(!window.confirm(`${selected.size} Leads endgültig löschen?`))return;setBusy(true);try{const r=await supabase.from("energy_leads").delete().eq("user_id",userId).in("id",Array.from(selected));if(r.error)throw r.error;setNotice(`${selected.size} Leads gelöscht.`);setSelected(new Set());await load()}catch(e){setError(e instanceof Error?e.message:"Löschen fehlgeschlagen.")}finally{setBusy(false)}}

  if(loading)return <div className={styles.root}><div className={styles.loadingBar}/><div className={styles.loadingHero}/><div className={styles.loadingGrid}>{Array.from({length:9}).map((_,i)=><div key={i}/>)}</div></div>;
  return <div className={styles.root}>{busy?<div className={styles.loadingBar}/>:null}<header className={styles.hero}><div><div className={styles.eyebrow}>Walkenhorst · Energy Sales OS</div><h1>{label}</h1><p>{isCommercial?"Jeder Lead durchläuft einen klaren Produktions- und Vertriebsprozess – vom Enrichment bis zum Engagement.":"Private Kontakte mit klarer Priorität, nächster Aktion und vollständiger Kommunikationshistorie."}</p></div><button className={styles.primary} onClick={()=>setCreateOpen(true)}><PlusIcon/>Lead anlegen</button></header>
    <section className={styles.kpis}><article><span>Leads</span><strong>{rows.length}</strong><small>gesamt</small></article><article><span>Enrichment offen</span><strong>{metrics.enrichment}</strong><small>Recherche fehlt</small></article><article><span>Produktionsbereit</span><strong>{metrics.production}</strong><small>LP + Render</small></article><article><span>Prüfung offen</span><strong>{metrics.review}</strong><small>Entwürfe</small></article><article className={styles.hotKpi}><span>Hot / Signal</span><strong>{metrics.hot}</strong><small>priorisieren</small></article></section>
    {metrics.risk>0?<div className={styles.riskBanner}><strong>{metrics.risk} Prozessfehler erkannt</strong><span>Mindestens ein Lead wurde versendet, obwohl ein Produktions-Gate nicht grün war. Diese Fälle stehen ganz oben.</span></div>:null}{error?<div className={styles.error}>{error}</div>:null}{notice?<div className={styles.notice}>{notice}</div>:null}
    {priority.length?<section className={styles.priority}><div className={styles.sectionHead}><div><span>Smart Queue</span><h2>Heute zuerst bearbeiten</h2></div><small>sortiert nach Risiko, Engagement und Intent</small></div><div className={styles.priorityGrid}>{priority.map(row=>{const e=engagement(row);return <button key={row.id} onClick={()=>router.push(`/leads/${row.id}`)}><div className={styles.priorityTop}><span className={styles.avatar}>{initials(row.company_name)}</span><span className={`${styles.signal} ${styles[e.tone]}`}>{e.value}</span></div><strong>{row.company_name}</strong><small>{nextAction(row)}</small><div className={styles.priorityFoot}><span>{row.intent_score} Intent</span><ArrowIcon/></div></button>})}</div></section>:null}
    <section className={styles.card}><div className={styles.toolbar}><div className={styles.search}><SearchIcon/><input ref={searchRef} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Firma, Ansprechpartner, E-Mail, Ort, nächster Schritt …"/><kbd>/</kbd></div><select value={stageFilter} onChange={e=>setStageFilter(e.target.value)}><option value="all">Alle Prozessstufen</option>{FLOW_STEPS.map((step,i)=><option key={step} value={i}>{i+1}. {step}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value as "all"|LeadStatus)}><option value="all">Alle CRM-Status</option>{STATUS_OPTIONS.map(([v,n])=><option value={v} key={v}>{n}</option>)}</select><span className={styles.resultCount}>{filtered.length} Leads</span></div>
      {selected.size?<div className={styles.bulkBar} style={{background:"linear-gradient(135deg,#071a2b,#103853)",borderBottomColor:"rgba(94,234,212,.14)",color:"#fff",flexWrap:"wrap"}}><strong>{selected.size} Leads ausgewählt</strong><span style={{color:"#9fc1cc",minWidth:160}}>Serienaktion · jeder Lead wird einzeln geprüft</span><button disabled={Boolean(bulk)} onClick={()=>void bulkAction("enrich")}>Alle anreichern</button><button disabled={Boolean(bulk)} onClick={()=>void bulkAction("prepare_page")}>LPs erstellen</button><button disabled={Boolean(bulk)} onClick={()=>void bulkAction("render")} style={{background:"#14b8a6",borderColor:"#14b8a6",color:"#06221f",fontWeight:800}}>Videos rendern</button><button disabled={Boolean(bulk)} onClick={()=>void bulkAction("create_draft")}>Entwürfe erstellen</button><button disabled={Boolean(bulk)} onClick={()=>setSelected(new Set())}>Aufheben</button><button disabled={Boolean(bulk)} className={styles.danger} onClick={()=>void deleteSelected()}>Löschen</button>{bulk?<div style={{flexBasis:"100%",display:"grid",gridTemplateColumns:"1fr auto",alignItems:"center",gap:10,paddingTop:4}}><div style={{height:6,borderRadius:999,overflow:"hidden",background:"rgba(255,255,255,.1)"}}><span style={{display:"block",height:"100%",width:`${Math.round(bulk.done/Math.max(1,bulk.total)*100)}%`,borderRadius:999,background:"linear-gradient(90deg,#14b8a6,#5eead4)",transition:"width .2s ease"}}/></div><small style={{color:"#b8d6dd",fontSize:9}}>{bulk.label}: {bulk.done}/{bulk.total}{bulk.failed?` · ${bulk.failed} Blocker`:""}</small></div>:null}</div>:null}
      <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th className={styles.check}><input type="checkbox" checked={allVisibleSelected} onChange={toggleVisible}/></th><th>Lead</th><th>Prozess</th><th>Engagement</th><th>Intent</th><th>Nächste Aktion</th><th/></tr></thead><tbody>{visible.map(row=>{const w=row.workflow,e=engagement(row),stage=stageIndex(w),problem=hasGateProblem(row);return <tr key={row.id} className={problem?styles.problemRow:""} onClick={()=>router.push(`/leads/${row.id}`)}><td className={styles.check} onClick={event=>event.stopPropagation()}><input type="checkbox" checked={selected.has(row.id)} onChange={()=>toggle(row.id)}/></td><td><div className={styles.identity}><span className={styles.avatar}>{initials(row.company_name)}</span><div><strong>{row.company_name}</strong><small>{row.contact_name||"Ansprechpartner offen"}{row.city?` · ${row.city}`:""}</small></div></div></td><td><div className={styles.flowCell}><div className={styles.flowBar}>{FLOW_STEPS.map((_,i)=><i key={i} className={i<stage?styles.done:i===stage?styles.current:""}/>)}</div><div><strong>{problem?"Prüfung erforderlich":w?.workflow_stage_label||"Lead angelegt"}</strong><small>{Math.max(0,Math.min(100,w?.workflow_percent||12))}% · {w?.contact_count||0} Kontakt-Kandidaten</small></div></div></td><td><span className={`${styles.engagement} ${styles[e.tone]}`}><b>{e.value}</b><span>{e.label}</span></span></td><td><div className={styles.intent}><strong>{row.intent_score}</strong><span>/100</span></div></td><td><div className={styles.next}><strong>{nextAction(row)}</strong><small>{row.next_action_at?formatDate(row.next_action_at):problem?"Blocker zuerst beheben":"kein Termin gesetzt"}</small></div></td><td><span className={styles.rowArrow}><ArrowIcon/></span></td></tr>})}</tbody></table>{!visible.length?<div className={styles.empty}><strong>Keine Leads gefunden.</strong><span>Filter oder Suche anpassen.</span></div>:null}</div>
      {filtered.length?<footer className={styles.pagination}><span>{safePage*PAGE_SIZE+1}–{Math.min(filtered.length,safePage*PAGE_SIZE+PAGE_SIZE)} von {filtered.length}</span><div><button disabled={safePage===0} onClick={()=>setPage(v=>Math.max(0,v-1))}>Zurück</button><strong>{safePage+1} / {pageCount}</strong><button disabled={safePage>=pageCount-1} onClick={()=>setPage(v=>Math.min(pageCount-1,v+1))}>Weiter</button></div></footer>:null}
    </section>
    {createOpen?<div className={styles.modalBackdrop} onMouseDown={()=>setCreateOpen(false)}><section className={styles.modal} onMouseDown={e=>e.stopPropagation()}><div className={styles.modalHead}><div><span>Neuer Workflow</span><h2>{singular} anlegen</h2><p>Nach dem Anlegen landest du direkt im Lead-Cockpit beim Enrichment.</p></div><button onClick={()=>setCreateOpen(false)}>×</button></div><form onSubmit={createLead} className={styles.form}>{isCommercial?<label><span>Unternehmen *</span><input name="company_name" required autoFocus/></label>:null}<label><span>{isCommercial?"Ansprechpartner (optional)":"Vor- und Nachname *"}</span><input name="contact_name" required={!isCommercial} autoFocus={!isCommercial}/></label><div className={styles.formGrid}><label><span>E-Mail</span><input name="email" type="email"/></label><label><span>Telefon</span><input name="phone"/></label></div>{isCommercial?<div className={styles.formGrid}><label><span>Website</span><input name="website" placeholder="https://…"/></label><label><span>Branche</span><input name="industry"/></label></div>:null}<label><span>Adresse</span><input name="address"/></label><div className={styles.formGrid}><label><span>PLZ</span><input name="postcode"/></label><label><span>Ort</span><input name="city"/></label></div><div className={styles.modalActions}><button type="button" onClick={()=>setCreateOpen(false)}>Abbrechen</button><button className={styles.primary} disabled={busy}><PlusIcon/>{busy?"Wird angelegt …":"Lead anlegen"}</button></div></form></section></div>:null}
  </div>
}
