"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

type Alert={id:string;lead_id:string|null;alert_type:string;severity:string;title:string;detail:string|null;status:string;due_at:string|null;acknowledged_at:string|null;resolved_at:string|null;metadata:Record<string,unknown>;created_at:string;updated_at:string};
type Lead={id:string;company_name:string;phone:string|null;email:string|null;status:string;total_score:number;intent_score:number};
const ORDER:Record<string,number>={critical:4,hot:3,warn:2,info:1};
function fmt(v:string|null|undefined){if(!v)return"—";try{return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}catch{return"—"}}
function sla(v:string|null){if(!v)return"kein SLA";const ms=new Date(v).getTime()-Date.now();const mins=Math.round(Math.abs(ms)/60000);return ms<0?`${mins} Min. überfällig`:`noch ${mins} Min.`}

export function AlertCenter({user}:{user:User}){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const[alerts,setAlerts]=useState<Alert[]>([]);const[leads,setLeads]=useState<Lead[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);const[showDone,setShowDone]=useState(false);
 const load=useCallback(async()=>{if(!supabase)return;setBusy(true);setError(null);try{let q=supabase.from("energy_alerts").select("id,lead_id,alert_type,severity,title,detail,status,due_at,acknowledged_at,resolved_at,metadata,created_at,updated_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(3000);if(!showDone)q=q.neq("status","done");const[a,l]=await Promise.all([q,supabase.from("energy_leads").select("id,company_name,phone,email,status,total_score,intent_score").eq("user_id",user.id).limit(10000)]);if(a.error)throw a.error;setAlerts(((a.data||[]) as Alert[]).sort((x,y)=>(ORDER[y.severity]||0)-(ORDER[x.severity]||0)||(new Date(x.due_at||"9999-12-31").getTime()-new Date(y.due_at||"9999-12-31").getTime())));if(!l.error)setLeads((l.data||[]) as Lead[])}catch(x){setError(x instanceof Error?x.message:"Alerts konnten nicht geladen werden")}finally{setBusy(false)}},[supabase,user.id,showDone]);useEffect(()=>{void load()},[load]);
 async function action(id:string,a:"acknowledge"|"done"|"reopen"){if(!supabase)return;setBusy(true);setError(null);try{const{error:e}=await supabase.rpc("energy_alert_action",{p_alert_id:id,p_action:a});if(e)throw e;setNotice(a==="done"?"Alert erledigt.":a==="acknowledge"?"Alert quittiert.":"Alert wieder geöffnet.");await load()}catch(x){setError(x instanceof Error?x.message:"Alert konnte nicht aktualisiert werden")}finally{setBusy(false)}}
 const open=alerts.filter(a=>a.status==="open");const critical=open.filter(a=>a.severity==="critical").length;const overdue=open.filter(a=>a.due_at&&new Date(a.due_at).getTime()<Date.now()).length;const hot=open.filter(a=>["critical","hot"].includes(a.severity)).length;
 return <main className="os-root" style={{minHeight:"100vh"}}><div className="os-content" style={{maxWidth:1400,margin:"0 auto",paddingTop:28}}>
  <div className="os-section-head"><div><div className="os-kicker">Revenue SLA</div><h1 className="os-title">Alert Center</h1><p>Starke Kaufsignale und operative Fehler zuerst – mit klarer Reaktionszeit.</p></div><div className="os-toolbar"><a className="os-btn" href="/command">← Heute</a><a className="os-btn" href="/health-v2">System Health</a><button className="os-btn" onClick={()=>setShowDone(v=>!v)}>{showDone?"Erledigte ausblenden":"Erledigte anzeigen"}</button><button className="os-btn" disabled={busy} onClick={()=>void load()}>↻ Aktualisieren</button></div></div>{error?<div className="os-error">{error}</div>:null}{notice?<div className="os-success">{notice}</div>:null}
  <div className="os-grid os-kpis" style={{marginTop:18}}>{[[open.length,"Offen","aktive Alerts"],[critical,"Critical","sofort reagieren"],[hot,"Hot + Critical","Sales SLA"],[overdue,"Überfällig","SLA gerissen"],[alerts.filter(a=>a.status==="acknowledged").length,"Quittiert","in Bearbeitung"]].map(([v,l,s])=><div className="os-card os-kpi" key={String(l)}><div className="os-kpi-label">{l}</div><div className="os-kpi-value">{v}</div><div className="os-kpi-sub">{s}</div></div>)}</div>
  <section className="os-card os-section" style={{marginTop:18}}><div className="os-section-head"><div><div className="os-kicker">Priorisiert</div><h2>Sales & Operations Alerts</h2></div><span className={`os-pill ${overdue?"hot":"green"}`}>{overdue?`${overdue} überfällig`:"SLA sauber"}</span></div><div className="os-grid" style={{gap:10}}>{alerts.length?alerts.map(a=>{const l=leads.find(x=>x.id===a.lead_id);const isOver=Boolean(a.status==="open"&&a.due_at&&new Date(a.due_at).getTime()<Date.now());return <article className="os-callout" key={a.id} style={{borderColor:isOver?"rgba(255,80,80,.45)":undefined}}><div className="os-section-head"><div><div className="os-toolbar"><span className={`os-pill ${["critical","hot"].includes(a.severity)?"hot":a.severity==="info"?"green":""}`}>{a.severity}</span><span className="os-pill">{a.alert_type}</span><span className={`os-pill ${isOver?"hot":""}`}>{sla(a.due_at)}</span></div><h3 style={{margin:"8px 0 4px"}}>{a.title}</h3>{a.detail?<p style={{fontSize:10,color:"#69778d",margin:0}}>{a.detail}</p>:null}{l?<small style={{display:"block",marginTop:7}}>{l.company_name} · Score {l.total_score} · Intent {l.intent_score} · {l.status}</small>:null}<small style={{display:"block",marginTop:4}}>erstellt {fmt(a.created_at)}</small></div><div className="os-toolbar">{l?.phone&&a.status!=="done"?<a className="os-btn small primary" href={`tel:${l.phone}`}>📞 Anrufen</a>:null}{a.status==="open"?<button className="os-btn small" disabled={busy} onClick={()=>void action(a.id,"acknowledge")}>Quittieren</button>:null}{a.status!=="done"?<button className="os-btn small" disabled={busy} onClick={()=>void action(a.id,"done")}>Erledigt ✓</button>:<button className="os-btn small" disabled={busy} onClick={()=>void action(a.id,"reopen")}>Wieder öffnen</button>}</div></div></article>}):<div className="os-empty">Keine offenen Alerts. System und Sales-SLA sind sauber.</div>}</div></section>
  <div className="os-callout" style={{marginTop:16}}><strong>SLA-Regel:</strong> sehr starke Intent-Signale werden in 10–15 Minuten fällig; positive Call-Signale in 30 Minuten. Überfällige Hot-Follow-ups werden vom Alert Worker zusätzlich erkannt.</div>
  <div className="os-source" style={{marginTop:10}}>Nutzer: {user.email}</div>
 </div></main>;
}
