"use client";

import Link from "next/link";
import { useEffect, useMemo, useState, type MouseEvent, type ReactNode } from "react";
import { usePathname } from "next/navigation";
import type { User } from "@supabase/supabase-js";
import { AuthGate } from "@/components/auth-gate";
import { AppUserProvider } from "@/components/app-user-context";
import { FloatingAiAssistant } from "@/components/floating-ai-assistant";
import { LeadRowOpenBridge } from "@/components/lead-row-open-bridge";
import { LoginPersonalizationBridge } from "@/components/login-personalization-bridge";
import { NavigationProgress } from "@/components/navigation-progress";
import { StudioLivePageBridge } from "@/components/studio-live-page-bridge";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

type IconName="home"|"search"|"building"|"users"|"bolt"|"star"|"briefcase"|"phone"|"pipeline"|"calendar"|"document"|"play"|"send"|"inbox"|"check"|"template"|"shield"|"sun"|"chart"|"alert"|"rotate"|"database"|"plug"|"health"|"settings";
type NavItem={label:string;href:string;icon:IconName;badge?:string;section?:string};type NavGroup={label:string;items:NavItem[]};
const ICONS:Record<IconName,string>={home:"M4 11 12 4l8 7v9H5v-9Zm5 9v-6h6v6",search:"M4 11a7 7 0 1 0 14 0 7 7 0 0 0-14 0Zm12 5 5 5",building:"M4 21V5h10v16M14 9h6v12M8 9h2m-2 4h2m-2 4h2m10 0h-2",users:"M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm-6 8c0-4 3-6 6-6s6 2 6 6m1-9a3 3 0 1 0 0-6m1 9c3 0 6 2 6 6",bolt:"m13 2-8 12h6l-1 8 9-13h-6V2Z",star:"m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9L6.2 20l1-6.1-4.4-4.3 6.1-.9L12 3Z",briefcase:"M3 8h18v12H3V8Zm5 0V5h8v3m-5 5h2",phone:"M7 3h3l2 5-2 2c1 3 3 5 6 6l2-2 5 2v3c0 2-2 3-4 3C10 21 3 14 3 5c0-2 2-2 4-2",pipeline:"M4 5h6v5H4V5Zm10 0h6v5h-6V5ZM9 15h6v5H9v-5Zm-2-5v3h10v-3M12 13v2",calendar:"M4 6h16v14H4V6Zm0 4h16M8 3v5m8-5v5",document:"M6 3h9l3 3v15H6V3Zm9 0v4h4M9 12h6m-6 4h6",play:"M5 4h14v16H5V4Zm5 5 5 3-5 3V9Z",send:"m3 11 18-8-8 18-2-7-8-3Zm8 3 10-11",inbox:"M4 4h16v14H4V4Zm0 9h4l2 3h4l2-3h4",check:"m5 12 4 4L19 6",template:"M5 4h14v16H5V4Zm4 0v16M12 8h4m-4 4h4",shield:"M12 3 5 6v5c0 5 3 8 7 10 4-2 7-5 7-10V6l-7-3Zm-3 9 2 2 4-5",sun:"M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10Zm0-4v2m0 14v2M3 12h2m14 0h2M5.6 5.6 7 7m10 10 1.4 1.4M18.4 5.6 17 7M7 17l-1.4 1.4",chart:"M4 19V9m6 10V5m6 14v-7m4 7H2",alert:"M12 3 2 20h20L12 3Zm0 6v5m0 3v1",rotate:"M20 8V4l-3 3a8 8 0 1 0 2 9M4 16v4l3-3",database:"M4 6c0-2 4-3 8-3s8 1 8 3-4 3-8 3-8-1-8-3Zm0 0v6c0 2 4 3 8 3s8-1 8-3V6m-16 6v6c0 2 4 3 8 3s8-1 8-3v-6",plug:"M9 3v5m6-5v5m-8 0h10v3a5 5 0 0 1-10 0V8Zm5 8v5",health:"M4 12h4l2-5 4 10 2-5h4M12 3a9 9 0 1 0 9 9",settings:"M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm0-5 1 3 3 1 3-1 2 3-2 2v3l2 2-2 3-3-1-3 1-3-1-3 1-2-3 2-2v-3L3 9l2-3 3 1 3-1 1-3Z"};
function NavIcon({name}:{name:IconName}){return <svg className="wh-nav-svg" viewBox="0 0 24 24" aria-hidden="true"><path d={ICONS[name]}/></svg>}
const NAV_GROUPS:NavGroup[]=[{label:"Arbeitsbereich",items:[{label:"Übersicht",href:"/dashboard?section=overview",section:"overview",icon:"home"},{label:"Lead Finder",href:"/dashboard?section=finder",section:"finder",icon:"search"},{label:"Gewerbe CRM",href:"/crm/commercial",icon:"building",badge:"B2B"},{label:"Privatkunden CRM",href:"/crm/private",icon:"users",badge:"B2C"},{label:"Heute",href:"/command",icon:"bolt"}]},{label:"Sales",items:[{label:"Opportunities",href:"/opportunities",icon:"star"},{label:"Sales Brief",href:"/sales-brief",icon:"briefcase"},{label:"Caller Queue",href:"/calls",icon:"phone"},{label:"Pipeline",href:"/pipeline",icon:"pipeline"},{label:"Meetings",href:"/meetings",icon:"calendar"},{label:"Angebote",href:"/proposals",icon:"document"}]},{label:"Outbound",items:[{label:"Studio",href:"/studio",icon:"play",badge:"V3"},{label:"Kampagnen",href:"/campaign-lab",icon:"send"},{label:"Inbox",href:"/dashboard?section=inbox",section:"inbox",icon:"inbox"},{label:"Follow-ups",href:"/dashboard?section=followups",section:"followups",icon:"check"},{label:"Vorlagen",href:"/dashboard?section=templates",section:"templates",icon:"template"},{label:"Deliverability",href:"/deliverability",icon:"shield"}]},{label:"Intelligence",items:[{label:"PV Intelligence",href:"/pv-intelligence",icon:"sun"},{label:"Website Analyse",href:"/dashboard?section=audit",section:"audit",icon:"search"},{label:"SEO Radar",href:"/dashboard?section=seo",section:"seo",icon:"chart"},{label:"Revenue Analytics",href:"/analytics",icon:"chart"}]},{label:"Automation & System",items:[{label:"Alerts",href:"/alerts",icon:"alert"},{label:"Revival",href:"/revival",icon:"rotate"},{label:"Data Hygiene",href:"/data-hygiene",icon:"check"},{label:"Daten",href:"/data",icon:"database"},{label:"Integrationen",href:"/integrations",icon:"plug"},{label:"Go-Live",href:"/launch",icon:"send"},{label:"System Health",href:"/health",icon:"health"},{label:"Settings",href:"/settings",icon:"settings"}]}];
const PUBLIC_PREFIXES=["/v/","/offer/","/u/"];const DASHBOARD_PATHS=new Set(["/","/dashboard"]);const SECTION_LABELS:Record<string,string>={overview:"Übersicht",finder:"Lead Finder",leads:"Leads",inbox:"Inbox",followups:"Follow-ups",templates:"Vorlagen",audit:"Website Analyse",seo:"SEO Radar"};
function initials(user:User){const value=user.user_metadata?.full_name||user.email||"Walkenhorst";const parts=String(value).split(/[\s@._-]+/).filter(Boolean);return parts.slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"WH"}
function currentSectionFromLocation(){if(typeof window==="undefined")return"overview";return new URLSearchParams(window.location.search).get("section")||"overview"}
function clickLegacySection(section:string){const label=SECTION_LABELS[section];if(!label)return;const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>(".os-sidebar .os-navbtn"));buttons.find(candidate=>(candidate.textContent||"").replace(/\s+/g," ").trim().includes(label))?.click()}
function DashboardFrame({user,children}:{user:User;children:ReactNode}){const pathname=usePathname();const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const[collapsed,setCollapsed]=useState(false);const[mobileOpen,setMobileOpen]=useState(false);const[dashboardSection,setDashboardSection]=useState("overview");
 useEffect(()=>{const initial=currentSectionFromLocation();setDashboardSection(initial);if(DASHBOARD_PATHS.has(window.location.pathname))window.setTimeout(()=>clickLegacySection(initial),0);const handleNavigation=(event:Event)=>setDashboardSection((event as CustomEvent<string>).detail||currentSectionFromLocation());const handlePopState=()=>{const section=currentSectionFromLocation();setDashboardSection(section);if(DASHBOARD_PATHS.has(window.location.pathname))window.setTimeout(()=>clickLegacySection(section),0)};window.addEventListener("walkenhorst:section",handleNavigation);window.addEventListener("popstate",handlePopState);return()=>{window.removeEventListener("walkenhorst:section",handleNavigation);window.removeEventListener("popstate",handlePopState)}},[]);
 useEffect(()=>{setMobileOpen(false);const section=currentSectionFromLocation();setDashboardSection(section);if(DASHBOARD_PATHS.has(pathname))window.setTimeout(()=>clickLegacySection(section),0)},[pathname]);useEffect(()=>{setCollapsed(window.localStorage.getItem("walkenhorst.sidebar.collapsed")==="1")},[]);
 function toggleCollapsed(){setCollapsed(value=>{const next=!value;window.localStorage.setItem("walkenhorst.sidebar.collapsed",next?"1":"0");return next})}function isActive(item:NavItem){if(item.section)return DASHBOARD_PATHS.has(pathname)&&dashboardSection===item.section;return pathname===item.href||(item.href!=="/"&&pathname.startsWith(`${item.href}/`))}function openSection(event:MouseEvent<HTMLAnchorElement>,item:NavItem){setMobileOpen(false);if(!item.section)return;setDashboardSection(item.section);if(!DASHBOARD_PATHS.has(pathname))return;event.preventDefault();const next=`/dashboard?section=${encodeURIComponent(item.section)}`;window.history.pushState(window.history.state,"",next);clickLegacySection(item.section);window.dispatchEvent(new CustomEvent("walkenhorst:section",{detail:item.section}))}async function signOut(){if(supabase)await supabase.auth.signOut();window.location.assign("/dashboard")}
 return <AppUserProvider user={user}><div className={`wh-app-frame ${collapsed?"is-collapsed":""}`}><NavigationProgress/><LoginPersonalizationBridge user={user}/><div className={`wh-sidebar-backdrop ${mobileOpen?"is-open":""}`} onClick={()=>setMobileOpen(false)}/><aside className={`wh-app-sidebar ${mobileOpen?"is-mobile-open":""}`}><div className="wh-sidebar-brand"><Link className="wh-brand-lockup" href="/dashboard?section=overview" aria-label="Walkenhorst Übersicht"><span className="wh-brand-mark">W</span><span className="wh-brand-copy"><strong>Walkenhorst</strong><small>Energy Sales OS</small></span></Link><button className="wh-collapse-button" type="button" onClick={toggleCollapsed} title={collapsed?"Navigation ausklappen":"Navigation einklappen"}>{collapsed?"›":"‹"}</button></div><nav className="wh-sidebar-nav" aria-label="Walkenhorst Hauptnavigation">{NAV_GROUPS.map(group=><div className="wh-nav-group" key={group.label}><div className="wh-nav-label">{group.label}</div>{group.items.map(item=><Link key={`${group.label}-${item.label}`} className={`wh-nav-item ${isActive(item)?"is-active":""}`} href={item.href} prefetch title={collapsed?item.label:undefined} onClick={event=>openSection(event,item)}><span className="wh-nav-icon"><NavIcon name={item.icon}/></span><span className="wh-nav-text">{item.label}</span>{item.badge?<span className="wh-nav-badge">{item.badge}</span>:null}</Link>)}</div>)}</nav><div className="wh-sidebar-footer"><div className="wh-system-pill"><span/>System bereit</div><div className="wh-user-card"><div className="wh-user-avatar">{initials(user)}</div><div className="wh-user-copy"><strong>{user.user_metadata?.full_name||"Walkenhorst Admin"}</strong><small>{user.email}</small></div><button className="wh-signout" type="button" onClick={()=>void signOut()} title="Abmelden"><svg viewBox="0 0 24 24"><path d="M10 5H5v14h5m3-4 4-3-4-3m4 3H9"/></svg></button></div></div></aside><section className="wh-app-workspace"><header className="wh-mobile-bar"><button type="button" onClick={()=>setMobileOpen(true)} aria-label="Navigation öffnen"><span/><span/><span/></button><Link href="/dashboard?section=overview"><span className="wh-mobile-mark">W</span><strong>Walkenhorst</strong></Link><Link className="wh-mobile-studio" href="/studio" prefetch>Studio</Link></header><div className="wh-app-content">{children}</div></section><LeadRowOpenBridge user={user}/><StudioLivePageBridge user={user}/><FloatingAiAssistant user={user}/></div></AppUserProvider>}
export function ApplicationFrame({children}:{children:ReactNode}){const pathname=usePathname();if(PUBLIC_PREFIXES.some(prefix=>pathname.startsWith(prefix)))return <>{children}</>;return <AuthGate>{user=><DashboardFrame user={user}>{children}</DashboardFrame>}</AuthGate>}
