"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

type Lead={id:string;company_name:string;contact_name:string|null;email:string|null;phone:string|null;total_score:number;intent_score:number;status:string};
type Deal={id:string;lead_id:string;title:string;stage:string;value_eur:number|null;probability:number;expected_close_date:string|null;notes:string|null;created_at:string;updated_at:string};
type Document={id:string;lead_id:string;deal_id:string|null;provider:string;title:string;status:string;share_url:string|null;view_count:number;total_view_seconds:number;last_viewed_at:string|null};
type Intent={id:number;lead_id:string;source:string;event_type:string;weight:number;occurred_at:string};

const STAGES=[
 {id:"new",label:"Neu"},{id:"qualified",label:"Qualifiziert"},{id:"meeting",label:"Termin"},{id:"proposal",label:"Angebot"},{id:"negotiation",label:"Verhandlung"},{id:"won",label:"Gewonnen"},{id:"lost",label:"Verloren"},
];
const fmtMoney=(v:number|null)=>v==null?"—":new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(v);
const fmtDate=(v:string|null)=>v?new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",year:"2-digit"}).format(new Date(v)):"—";

export function CrmPipeline({user}:{user:User}){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
 const [leads,setLeads]=useState<Lead[]>([]);const [deals,setDeals]=useState<Deal[]>([]);const [documents,setDocuments]=useState<Document[]>([]);const [intents,setIntents]=useState<Intent[]>([]);const [selected,setSelected]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!supabase)return;const uid=user.id;const[d,l,doc,it]=await Promise.all([
   supabase.from("energy_deals").select("*").eq("user_id",uid).order("updated_at",{ascending:false}),
   supabase.from("energy_leads").select("id,company_name,contact_name,email,phone,total_score,intent_score,status").eq("user_id",uid).order("total_score",{ascending:false}).limit(3000),
   supabase.from("energy_documents").select("id,lead_id,deal_id,provider,title,status,share_url,view_count,total_view_seconds,last_viewed_at").eq("user_id",uid).order("updated_at",{ascending:false}).limit(1000),
   supabase.from("energy_intent_events").select("id,lead_id,source,event_type,weight,occurred_at").eq("user_id",uid).order("occurred_at",{ascending:false}).limit(1500),
  ]);if(d.error){setError(d.error.message);return}setDeals((d.data||[]) as Deal[]);setLeads((l.data||[]) as Lead[]);setDocuments((doc.data||[]) as Document[]);setIntents((it.data||[]) as Intent[]);if(!selected&&d.data?.length)setSelected(String(d.data[0].id));},[supabase,user.id,selected]);
 useEffect(()=>{void load()},[load]);
 const current=deals.find(d=>d.id===selected)||null;const currentLead=current?leads.find(l=>l.id===current.lead_id)||null:null;
 async function createDeal(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setError(null);try{const f=new FormData(e.currentTarget);const leadId=String(f.get("leadId")||"");const lead=leads.find(l=>l.id===leadId);if(!lead)throw new Error("Lead auswählen");const value=String(f.get("value")||"").trim();const{data,error}=await supabase.from("energy_deals").upsert({user_id:user.id,lead_id:lead.id,title:String(f.get("title")||`${lead.company_name} · Energieprojekt`),stage:"qualified",value_eur:value?Number(value):null,probability:30,updated_at:new Date().toISOString()},{onConflict:"user_id,lead_id"}).select("*").single();if(error)throw error;setSelected(data.id);setMessage("Deal angelegt.");e.currentTarget.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Deal konnte nicht angelegt werden")}finally{setBusy(false)}}
 async function moveDeal(dealId:string,stage:string){if(!supabase)return;const probability:Record<string,number>={new:10,qualified:30,meeting:50,proposal:65,negotiation:80,won:100,lost:0};const updates:any={stage,probability:probability[stage]??30,updated_at:new Date().toISOString()};if(stage==="won")updates.won_at=new Date().toISOString();if(stage==="lost")updates.lost_at=new Date().toISOString();await supabase.from("energy_deals").update(updates).eq("id",dealId).eq("user_id",user.id);const deal=deals.find(d=>d.id===dealId);if(deal){const statusMap:Record<string,string>={qualified:"qualified",meeting:"meeting",proposal:"proposal",negotiation:"proposal",won:"won",lost:"lost"};if(statusMap[stage])await supabase.from("energy_leads").update({status:statusMap[stage],updated_at:new Date().toISOString()}).eq("id",deal.lead_id).eq("user_id",user.id)}await load()}
 async function saveDeal(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase||!current)return;setBusy(true);try{const f=new FormData(e.currentTarget);const value=String(f.get("value")||"").trim();const{error}=await supabase.from("energy_deals").update({title:String(f.get("title")||current.title),value_eur:value?Number(value):null,probability:Number(f.get("probability")||current.probability),expected_close_date:String(f.get("close")||"")||null,notes:String(f.get("notes")||"")||null,updated_at:new Date().toISOString()}).eq("id",current.id).eq("user_id",user.id);if(error)throw error;setMessage("Deal gespeichert.");await load()}catch(x){setError(x instanceof Error?x.message:"Speichern fehlgeschlagen")}finally{setBusy(false)}}
 async function addDocument(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase||!current)return;setBusy(true);try{const f=new FormData(e.currentTarget);const{error}=await supabase.from("energy_documents").insert({user_id:user.id,lead_id:current.lead_id,deal_id:current.id,provider:"manual",title:String(f.get("title")||"Angebot"),share_url:String(f.get("url")||"")||null,status:"sent"});if(error)throw error;setMessage("Angebot/Dokument verknüpft.");e.currentTarget.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Dokument konnte nicht gespeichert werden")}finally{setBusy(false)}}
 const weighted=deals.filter(d=>!['won','lost'].includes(d.stage)).reduce((s,d)=>s+(Number(d.value_eur)||0)*(d.probability/100),0);const won=deals.filter(d=>d.stage==='won').reduce((s,d)=>s+(Number(d.value_eur)||0),0);
 return <div className="os-root" style={{minHeight:"100vh"}}><main className="os-main" style={{marginLeft:0}}><header className="os-topbar"><div><div className="os-kicker">Sales CRM</div><h1 className="os-title">Deal Pipeline</h1></div><div className="os-actions"><a className="os-btn" href="/dashboard">← Sales OS</a><span className="os-pill">Weighted {fmtMoney(weighted)}</span><span className="os-pill green">Won {fmtMoney(won)}</span></div></header><div className="os-content">{error?<div className="os-error">{error}</div>:null}{message?<div className="os-success">{message}</div>:null}
   <section className="os-card os-section"><div className="os-section-head"><div><div className="os-kicker">Pipeline</div><h2>{deals.length} Deals</h2></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(7,minmax(210px,1fr))",gap:10,overflowX:"auto",paddingBottom:8}}>{STAGES.map(stage=><div key={stage.id} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData("text/deal");if(id)void moveDeal(id,stage.id)}} style={{background:"#f7f8fa",border:"1px solid #e7eaf0",borderRadius:10,padding:10,minHeight:310}}><div className="os-section-head" style={{marginBottom:8}}><strong style={{fontSize:11}}>{stage.label}</strong><span className="os-pill">{deals.filter(d=>d.stage===stage.id).length}</span></div>{deals.filter(d=>d.stage===stage.id).map(d=>{const lead=leads.find(l=>l.id===d.lead_id);return <button draggable onDragStart={e=>e.dataTransfer.setData("text/deal",d.id)} onClick={()=>setSelected(d.id)} key={d.id} style={{display:"block",width:"100%",textAlign:"left",border:"1px solid #e3e7ed",background:selected===d.id?"#fff1e8":"#fff",borderRadius:9,padding:11,marginBottom:8,cursor:"grab"}}><strong style={{fontSize:10,color:"#172139"}}>{lead?.company_name||d.title}</strong><div style={{fontSize:9,color:"#8592a5",marginTop:5}}>{fmtMoney(Number(d.value_eur)||null)} · {d.probability}%</div><div style={{fontSize:8,color:"#9aa5b4",marginTop:4}}>Intent {lead?.intent_score??0} · Score {lead?.total_score??0}</div></button>})}</div>)}</div></section>
   <div className="os-columns" style={{marginTop:16}}><section className="os-card os-section"><div className="os-kicker">Neuer Deal</div><h2>Lead in Pipeline übernehmen</h2><form className="os-form" onSubmit={createDeal}><div className="os-field"><label>Lead</label><select name="leadId" required defaultValue=""><option value="" disabled>Lead auswählen</option>{leads.filter(l=>!deals.some(d=>d.lead_id===l.id)).map(l=><option value={l.id} key={l.id}>{l.company_name} · Score {l.total_score}</option>)}</select></div><div className="os-formgrid"><div className="os-field"><label>Deal-Titel</label><input name="title" placeholder="Energieprojekt / PV"/></div><div className="os-field"><label>Potenzialwert €</label><input name="value" type="number" min="0" step="100"/></div></div><button className="os-btn primary" disabled={busy}>Deal anlegen</button></form></section>
   {current&&currentLead?<section className="os-card os-section"><div className="os-section-head"><div><div className="os-kicker">Deal Detail</div><h2>{currentLead.company_name}</h2></div><span className="os-score">{currentLead.intent_score}</span></div><form className="os-form" onSubmit={saveDeal}><div className="os-field"><label>Titel</label><input name="title" defaultValue={current.title}/></div><div className="os-formgrid"><div className="os-field"><label>Wert €</label><input name="value" type="number" defaultValue={current.value_eur??""}/></div><div className="os-field"><label>Wahrscheinlichkeit %</label><input name="probability" type="number" min="0" max="100" defaultValue={current.probability}/></div><div className="os-field"><label>Expected Close</label><input name="close" type="date" defaultValue={current.expected_close_date??""}/></div></div><div className="os-field"><label>Notizen</label><textarea name="notes" defaultValue={current.notes??""}/></div><button className="os-btn primary" disabled={busy}>Deal speichern</button></form><div className="os-divider"/><div className="os-kicker">Angebote & Dokumente</div>{documents.filter(d=>d.lead_id===current.lead_id).map(d=><div className="os-checkrow" key={d.id}><span className={`os-pill ${d.view_count>1?"hot":""}`}>{d.provider}</span><div><strong>{d.title}</strong><small>{d.view_count} Views · {d.total_view_seconds}s · zuletzt {fmtDate(d.last_viewed_at)}</small></div>{d.share_url?<a className="os-btn small" target="_blank" href={d.share_url}>Öffnen ↗</a>:null}</div>)}<form className="os-inline-form" style={{display:"grid",gridTemplateColumns:"1fr 1.5fr auto",gap:7,marginTop:10}} onSubmit={addDocument}><input name="title" placeholder="Angebot #123" required/><input name="url" type="url" placeholder="https://..."/><button className="os-btn small" disabled={busy}>Verknüpfen</button></form><div className="os-divider"/><div className="os-kicker">Intent Timeline</div>{intents.filter(i=>i.lead_id===current.lead_id).slice(0,12).map(i=><div className="os-checkrow" key={i.id}><span className={`os-pill ${i.weight>=25?"hot":""}`}>+{i.weight}</span><div><strong>{i.event_type}</strong><small>{i.source} · {fmtDate(i.occurred_at)}</small></div></div>)}</section>:<section className="os-card os-section"><div className="os-empty">Deal auswählen, um Details zu sehen.</div></section>}</div>
  </div></main></div>
}
