"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

type Duplicate={lead_a:string;lead_b:string;company_a:string;company_b:string;city_a:string|null;city_b:string|null;email_a:string|null;email_b:string|null;phone_a:string|null;phone_b:string|null;website_a:string|null;website_b:string|null;score_a:number;score_b:number;confidence:number;reasons:string[]};
const REASON:Record<string,string>={same_email:"gleiche E-Mail",same_phone:"gleiche Telefonnummer",same_domain_city:"gleiche Domain + Ort",same_domain_postcode:"gleiche Domain + PLZ",same_company_postcode:"gleicher Firmenname + PLZ",same_company_city:"gleicher Firmenname + Ort"};

export function DataHygieneCenter({user}:{user:User}){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
  const [rows,setRows]=useState<Duplicate[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);const [minConfidence,setMinConfidence]=useState(50);const [primaryChoice,setPrimaryChoice]=useState<Record<string,"a"|"b">>({});
  const load=useCallback(async()=>{if(!supabase)return;setBusy(true);setError(null);try{const{data,error:e}=await supabase.rpc("energy_find_duplicate_leads",{p_limit:750});if(e)throw e;const next=(data||[]) as Duplicate[];setRows(next);setPrimaryChoice(Object.fromEntries(next.map(r=>[`${r.lead_a}:${r.lead_b}`,r.score_a>=r.score_b?"a":"b"])))}catch(x){setError(x instanceof Error?x.message:"Dubletten konnten nicht geladen werden")}finally{setBusy(false)}},[supabase]);
  useEffect(()=>{void load()},[load]);
  const visible=rows.filter(r=>r.confidence>=minConfidence);const high=rows.filter(r=>r.confidence>=80).length;const medium=rows.filter(r=>r.confidence>=50&&r.confidence<80).length;
  async function merge(row:Duplicate){if(!supabase)return;const key=`${row.lead_a}:${row.lead_b}`;const choice=primaryChoice[key]||"a";const primary=choice==="a"?row.lead_a:row.lead_b;const secondary=choice==="a"?row.lead_b:row.lead_a;const primaryName=choice==="a"?row.company_a:row.company_b;const secondaryName=choice==="a"?row.company_b:row.company_a;if(!window.confirm(`${secondaryName} wirklich in ${primaryName} zusammenführen? Der zweite Lead wird danach gelöscht, verknüpfte Historie wird auf den Hauptlead übertragen.`))return;setBusy(true);setError(null);setNotice(null);try{const{data,error:e}=await supabase.rpc("energy_merge_leads",{p_primary:primary,p_secondary:secondary});if(e)throw e;setNotice(`${secondaryName} wurde sicher in ${primaryName} zusammengeführt.`);await load();return data}catch(x){setError(x instanceof Error?x.message:"Merge wurde aus Sicherheitsgründen abgebrochen.")}finally{setBusy(false)}}
  function value(v:string|null){return v||"—"}
  return <main className="os-root" style={{minHeight:"100vh"}}><div className="os-content" style={{maxWidth:1400,margin:"0 auto",paddingTop:28}}>
    <div className="os-section-head"><div><div className="os-kicker">CRM Data Quality</div><h1 className="os-title">Data Hygiene</h1><p>Dubletten erkennen, prüfen und transaktional zusammenführen – ohne blindes Auto-Merge.</p></div><div className="os-toolbar"><a className="os-btn" href="/command">← Heute</a><button className="os-btn" disabled={busy} onClick={()=>void load()}>↻ Neu prüfen</button></div></div>
    {error?<div className="os-error">{error}</div>:null}{notice?<div className="os-success">{notice}</div>:null}
    <div className="os-grid os-kpis" style={{marginTop:18}}>{[[rows.length,"Verdächtige Paare","gesamt"],[high,"High Confidence","≥ 80"],[medium,"Review", "50–79"],[visible.length,"Aktueller Filter",`≥ ${minConfidence}`],[0,"Auto-Merges","bewusst deaktiviert"]].map(([v,l,s])=><div className="os-card os-kpi" key={String(l)}><div className="os-kpi-label">{l}</div><div className="os-kpi-value">{v}</div><div className="os-kpi-sub">{s}</div></div>)}</div>
    <section className="os-card os-section" style={{marginTop:18}}><div className="os-section-head"><div><div className="os-kicker">Review Queue</div><h2>Duplicate Suggestions</h2></div><div className="os-toolbar"><label style={{fontSize:10,fontWeight:800}}>Minimum</label><select className="os-search" style={{width:115}} value={minConfidence} onChange={e=>setMinConfidence(Number(e.target.value))}><option value={50}>50+</option><option value={65}>65+</option><option value={80}>80+</option><option value={95}>95+</option></select></div></div>
      <div className="os-grid" style={{gap:12}}>{visible.length?visible.map(r=>{const key=`${r.lead_a}:${r.lead_b}`;const choice=primaryChoice[key]||"a";return <article className="os-callout" key={key} style={{padding:14}}><div className="os-section-head"><div><div className="os-toolbar"><span className={`os-pill ${r.confidence>=80?"hot":"green"}`}>{r.confidence}% Match</span>{r.reasons.map(x=><span className="os-pill" key={x}>{REASON[x]||x}</span>)}</div></div><button className="os-btn primary" disabled={busy} onClick={()=>void merge(r)}>Auswahl zusammenführen</button></div><div className="os-columns" style={{gridTemplateColumns:"1fr 1fr",gap:10}}>{(["a","b"] as const).map(side=>{const name=side==="a"?r.company_a:r.company_b;const score=side==="a"?r.score_a:r.score_b;const city=side==="a"?r.city_a:r.city_b;const email=side==="a"?r.email_a:r.email_b;const phone=side==="a"?r.phone_a:r.phone_b;const website=side==="a"?r.website_a:r.website_b;return <label key={side} style={{display:"block",padding:12,border:`2px solid ${choice===side?"#ff6b16":"#e3e7ed"}`,borderRadius:10,background:"#fff",cursor:"pointer"}}><div className="os-toolbar"><input type="radio" checked={choice===side} onChange={()=>setPrimaryChoice(v=>({...v,[key]:side}))}/><strong>{choice===side?"HAUPTLEAD":"Zusammenführen"}</strong><span className="os-score">{score}</span></div><h3 style={{margin:"10px 0 7px"}}>{name}</h3><div className="os-detail-row"><span>Ort</span><strong>{value(city)}</strong></div><div className="os-detail-row"><span>E-Mail</span><strong>{value(email)}</strong></div><div className="os-detail-row"><span>Telefon</span><strong>{value(phone)}</strong></div><div className="os-detail-row"><span>Website</span><strong style={{maxWidth:260,overflow:"hidden",textOverflow:"ellipsis"}}>{value(website)}</strong></div></label>})}</div></article>}):<div className="os-empty">Keine Dubletten oberhalb des gewählten Confidence-Werts gefunden.</div>}</div>
    </section>
    <div className="os-callout" style={{marginTop:16}}><strong>Sicherheitsregeln:</strong> Deals mit Konflikten, identische Kampagnenmitgliedschaften oder widersprüchliche geschlossene Zustände werden nicht automatisch gemerged. In solchen Fällen bricht die Datenbank die Transaktion vollständig ab.</div>
    <div className="os-source" style={{marginTop:10}}>Nutzer: {user.email} · Matching über E-Mail, E.164-Telefon, Domain+Ort/PLZ und normalisierten Firmennamen.</div>
  </div></main>;
}
