"use client";

import { ChangeEvent, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";
import { scoreEnergyLead } from "@/lib/energy-score";

type CsvLead={company_name:string;website:string|null;city:string|null;industry:string|null;email:string|null;phone:string|null;contact_name:string|null;address:string|null;postcode:string|null};
function key(v:string){return v.toLowerCase().trim().replace(/[ä]/g,"ae").replace(/[ö]/g,"oe").replace(/[ü]/g,"ue").replace(/[ß]/g,"ss").replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"")}
function parseCsv(text:string){const first=(text.split(/\r?\n/,1)[0]||"");const delimiter=(first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?";":",";const rows:string[][]=[];let row:string[]=[];let cell="";let quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted;continue}if(ch===delimiter&&!quoted){row.push(cell);cell="";continue}if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell="";if(row.some(x=>x.trim()!==""))rows.push(row);row=[];continue}cell+=ch}row.push(cell);if(row.some(x=>x.trim()!==""))rows.push(row);return rows}
function pick(obj:Record<string,string>,aliases:string[]){for(const a of aliases){const v=obj[a];if(v?.trim())return v.trim()}return null}
function toLead(obj:Record<string,string>):CsvLead|null{const company=pick(obj,["company_name","company","firma","unternehmen","firmenname","name"]);if(!company)return null;return{company_name:company,website:pick(obj,["website","webseite","url","domain"]),city:pick(obj,["city","stadt","ort"]),industry:pick(obj,["industry","branche","segment"]),email:pick(obj,["email","e_mail","mail"]),phone:pick(obj,["phone","telefon","telephone","mobile","mobil"]),contact_name:pick(obj,["contact_name","contact","ansprechpartner","kontakt"]),address:pick(obj,["address","adresse","strasse","street"]),postcode:pick(obj,["postcode","plz","zip","postal_code"])}}
function emailNorm(v:string|null){return v?.trim().toLowerCase()||""}
function phoneNorm(v:string|null){const raw=(v||"").trim();const d=raw.replace(/\D/g,"");if(!d)return"";if(raw.startsWith("+"))return`+${d}`;if(d.startsWith("00"))return`+${d.slice(2)}`;if(d.startsWith("0"))return`+49${d.slice(1)}`;return`+${d}`}
function domainNorm(v:string|null){return(v||"").trim().toLowerCase().replace(/^https?:\/\//,"" ).replace(/^www\./,"").split(/[/?#]/)[0].replace(/:\d+$/,"")}
function esc(v:unknown){const s=v==null?"":typeof v==="object"?JSON.stringify(v):String(v);return/[";,\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function makeCsv(rows:Record<string,unknown>[]){if(!rows.length)return"";const headers=Array.from(new Set(rows.flatMap(r=>Object.keys(r))));return [headers.join(";"),...rows.map(r=>headers.map(h=>esc(r[h])).join(";"))].join("\r\n")}
function download(name:string,text:string){const blob=new Blob(["\ufeff",text],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

export function DataTransferCenter({user}:{user:User}){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const[fileName,setFileName]=useState("");const[parsed,setParsed]=useState<CsvLead[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);const[stats,setStats]=useState<{imported:number;skipped:number;failed:number}|null>(null);
 async function file(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setFileName(f.name);setError(null);setNotice(null);try{const text=await f.text();const rows=parseCsv(text);if(rows.length<2)throw new Error("CSV enthält keine Datenzeilen.");const headers=rows[0].map(h=>key(h));const leads=rows.slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||""]))).map(toLead).filter(Boolean) as CsvLead[];if(!leads.length)throw new Error("Keine Firmen erkannt. Benötigt wird mindestens eine Spalte Firma/Unternehmen/Company.");setParsed(leads);setNotice(`${leads.length} importierbare Firmen erkannt.`)}catch(x){setParsed([]);setError(x instanceof Error?x.message:"CSV konnte nicht gelesen werden")}}
 async function importRows(){if(!supabase||!parsed.length)return;setBusy(true);setError(null);setNotice(null);setStats(null);try{const{data:existing,error:e}=await supabase.from("energy_leads").select("email_norm,phone_e164,domain_norm,postcode").eq("user_id",user.id).limit(30000);if(e)throw e;const emails=new Set((existing||[]).map(x=>String(x.email_norm||"")).filter(Boolean));const phones=new Set((existing||[]).map(x=>String(x.phone_e164||"")).filter(Boolean));const domainPost=new Set((existing||[]).map(x=>`${x.domain_norm||""}|${x.postcode||""}`).filter(x=>!x.startsWith("|")));let imported=0,skipped=0,failed=0;const local=new Set<string>();const payloads:any[]=[];for(const r of parsed){const en=emailNorm(r.email),pn=phoneNorm(r.phone),dn=domainNorm(r.website),dp=dn&&r.postcode?`${dn}|${r.postcode}`:"";const localKey=en?`e:${en}`:pn?`p:${pn}`:dp?`d:${dp}`:`n:${r.company_name.toLowerCase()}|${r.city||""}`;if(local.has(localKey)||en&&emails.has(en)||pn&&phones.has(pn)||dp&&domainPost.has(dp)){skipped++;continue}local.add(localKey);const scores=scoreEnergyLead({company_name:r.company_name,website:r.website,city:r.city,industry:r.industry,employees:null,location_count:1,roof_area_m2:null,annual_energy_kwh:null,pv_present:null,contact_name:r.contact_name,phone:r.phone,email:r.email});payloads.push({user_id:user.id,company_name:r.company_name,website:r.website,city:r.city,industry:r.industry,email:r.email,phone:r.phone,contact_name:r.contact_name,address:r.address,postcode:r.postcode,source:"csv_import",pv_score:scores.pvScore,energy_score:scores.energyScore,intent_score:scores.intentScore,contactability_score:scores.contactabilityScore,total_score:scores.totalScore,summary:scores.summary,pitch:scores.pitch,next_action:scores.nextAction,status:scores.totalScore>=75?"ready":"research",metadata:{import_file:fileName||null,imported_at:new Date().toISOString()}})}for(let i=0;i<payloads.length;i+=200){const batch=payloads.slice(i,i+200);const{data,error:ins}=await supabase.from("energy_leads").insert(batch).select("id");if(ins){failed+=batch.length;continue}imported+=(data||[]).length}setStats({imported,skipped,failed});setNotice(`${imported} Leads importiert · ${skipped} exakte Dubletten übersprungen${failed?` · ${failed} Fehler`:""}.`)}catch(x){setError(x instanceof Error?x.message:"Import fehlgeschlagen")}finally{setBusy(false)}}
 async function exportTable(kind:"leads"|"deals"|"calls"|"suppressions"|"bounces"){if(!supabase)return;setBusy(true);setError(null);try{const cfg={leads:{table:"energy_leads",cols:"company_name,contact_name,contact_title,email,email_status,phone,website,address,postcode,city,industry,total_score,pv_score,energy_score,intent_score,status,source,created_at,updated_at"},deals:{table:"energy_deals",cols:"lead_id,title,stage,value_eur,probability,expected_close_date,lost_reason,won_at,lost_at,created_at,updated_at"},calls:{table:"energy_calls",cols:"lead_id,provider,external_call_id,direction,from_phone,to_phone,started_at,answered_at,ended_at,cause,sentiment,topics,ai_summary,created_at"},suppressions:{table:"energy_suppressions",cols:"kind,raw_value,value_norm,reason,source,block_all,active,created_at,updated_at"},bounces:{table:"energy_bounces",cols:"lead_id,bounced_email,bounce_type,diagnostic,occurred_at,created_at"}}[kind];const{data,error:e}=await supabase.from(cfg.table).select(cfg.cols).eq("user_id",user.id).limit(50000);if(e)throw e;const rows=(data||[]) as unknown as Record<string,unknown>[];download(`walkenhorst-${kind}-${new Date().toISOString().slice(0,10)}.csv`,makeCsv(rows));setNotice(`${rows.length} ${kind}-Datensätze exportiert.`)}catch(x){setError(x instanceof Error?x.message:"Export fehlgeschlagen")}finally{setBusy(false)}}
 return <main className="os-root" style={{minHeight:"100vh"}}><div className="os-content" style={{maxWidth:1400,margin:"0 auto",paddingTop:28}}>
  <div className="os-section-head"><div><div className="os-kicker">Data Operations</div><h1 className="os-title">Import & Export</h1><p>Bestandslisten sicher übernehmen und Walkenhorst-Daten jederzeit portabel halten.</p></div><div className="os-toolbar"><a className="os-btn" href="/launch">← Go-Live</a><a className="os-btn" href="/data-hygiene">Data Hygiene</a></div></div>{error?<div className="os-error">{error}</div>:null}{notice?<div className="os-success">{notice}</div>:null}
  <div className="os-columns" style={{marginTop:18}}><section className="os-card os-section"><div className="os-kicker">CSV Import</div><h2>Leadliste einlesen</h2><div className="os-field"><label>CSV-Datei</label><input type="file" accept=".csv,text/csv" onChange={file}/></div><div className="os-callout" style={{marginTop:12}}><strong>Erkannte Spalten:</strong><p style={{fontSize:10,margin:"6px 0 0"}}>Firma/Unternehmen, Website, Ort, Branche, E-Mail, Telefon, Ansprechpartner, Adresse, PLZ. Komma und Semikolon werden automatisch erkannt.</p></div>{parsed.length?<><div className="os-section-head" style={{marginTop:14}}><div><div className="os-kicker">Preview</div><h2>{parsed.length} Leads · {fileName}</h2></div><button className="os-btn primary" disabled={busy} onClick={()=>void importRows()}>{busy?"Import läuft …":"Sicher importieren"}</button></div><div className="os-tablewrap"><table className="os-table"><thead><tr><th>Firma</th><th>Ort</th><th>E-Mail</th><th>Telefon</th><th>Website</th></tr></thead><tbody>{parsed.slice(0,20).map((r,i)=><tr key={`${r.company_name}-${i}`}><td><strong>{r.company_name}</strong></td><td>{r.city||"—"}</td><td>{r.email||"—"}</td><td>{r.phone||"—"}</td><td>{r.website||"—"}</td></tr>)}</tbody></table></div>{parsed.length>20?<div className="os-source">Preview zeigt 20 von {parsed.length} Zeilen.</div>:null}</>:<div className="os-empty">CSV auswählen, um eine Vorschau zu sehen.</div>}{stats?<div className="os-grid" style={{gridTemplateColumns:"repeat(3,1fr)",gap:8,marginTop:12}}><div className="os-callout"><small>Importiert</small><strong style={{display:"block",fontSize:24}}>{stats.imported}</strong></div><div className="os-callout"><small>Übersprungen</small><strong style={{display:"block",fontSize:24}}>{stats.skipped}</strong></div><div className="os-callout"><small>Fehler</small><strong style={{display:"block",fontSize:24}}>{stats.failed}</strong></div></div>:null}</section>
  <section className="os-card os-section"><div className="os-kicker">Portable Daten</div><h2>CSV Export</h2><p style={{fontSize:11,color:"#738096"}}>Exports laufen direkt mit der aktuellen Nutzerberechtigung. Keine Secrets oder Mailbox-Passwörter werden exportiert.</p><div className="os-grid" style={{gap:9}}>{([['leads','Leads','Firmen, Kontakte, Scores, Status'],['deals','Pipeline','Dealwert, Stage, Forecast'],['calls','Calls','Rinkel-/Call-Historie und AI Summary'],['suppressions','Suppressions','persistente Kanal-/DNC-Sperren'],['bounces','Bounces','Hard/Soft Rückläufer']] as const).map(([id,title,text])=><div className="os-callout" key={id}><div className="os-section-head"><div><strong>{title}</strong><small style={{display:"block",marginTop:4}}>{text}</small></div><button className="os-btn small" disabled={busy} onClick={()=>void exportTable(id)}>CSV ↓</button></div></div>)}</div></section></div>
  <div className="os-callout" style={{marginTop:16}}><strong>Import-Schutz:</strong> Exakte E-Mail-, E.164-Telefon- und Domain+PLZ-Dubletten werden vor dem Insert übersprungen. Ähnliche Firmen landen anschließend zusätzlich in der Data-Hygiene-Review-Queue.</div><div className="os-source" style={{marginTop:10}}>Nutzer: {user.email}</div>
 </div></main>;
}
