"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

type Mailbox={id:string;email_address:string;status:string;daily_limit:number;sent_today:number;last_tested_at:string|null;last_sync_at:string|null;last_bounce_sync_at:string|null;last_error:string|null;last_bounce_error:string|null;ramp_enabled:boolean;ramp_start_limit:number;ramp_daily_increment:number;ramp_target_limit:number;created_at:string};
type Bounce={id:number;lead_id:string|null;mailbox_id:string;bounced_email:string;bounce_type:string;diagnostic:string|null;occurred_at:string;created_at:string};
type Message={id:string;mailbox_id:string|null;direction:string;status:string;created_at:string;sent_at:string|null};
type Lead={id:string;company_name:string;email:string|null;email_status:string;status:string};

function fmt(v:string|null|undefined){if(!v)return"—";try{return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}catch{return"—"}}
const pct=(a:number,b:number)=>b>0?Math.round((a/b)*1000)/10:0;

export function DeliverabilityCenter({user}:{user:User}){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
 const [mailboxes,setMailboxes]=useState<Mailbox[]>([]);const[bounces,setBounces]=useState<Bounce[]>([]);const[messages,setMessages]=useState<Message[]>([]);const[leads,setLeads]=useState<Lead[]>([]);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!supabase)return;setError(null);const since=new Date(Date.now()-7*86400_000).toISOString();const[mb,b,m,l]=await Promise.all([
  supabase.from("energy_mailboxes").select("id,email_address,status,daily_limit,sent_today,last_tested_at,last_sync_at,last_bounce_sync_at,last_error,last_bounce_error,ramp_enabled,ramp_start_limit,ramp_daily_increment,ramp_target_limit,created_at").eq("user_id",user.id).order("email_address"),
  supabase.from("energy_bounces").select("id,lead_id,mailbox_id,bounced_email,bounce_type,diagnostic,occurred_at,created_at").eq("user_id",user.id).gte("created_at",since).order("created_at",{ascending:false}).limit(3000),
  supabase.from("energy_messages").select("id,mailbox_id,direction,status,created_at,sent_at").eq("user_id",user.id).eq("direction","outbound").gte("created_at",since).limit(20000),
  supabase.from("energy_leads").select("id,company_name,email,email_status,status").eq("user_id",user.id).limit(10000),
 ]);if(mb.error){setError(mb.error.message);return}setMailboxes((mb.data||[]) as Mailbox[]);if(!b.error)setBounces((b.data||[]) as Bounce[]);if(!m.error)setMessages((m.data||[]) as Message[]);if(!l.error)setLeads((l.data||[]) as Lead[])},[supabase,user.id]);useEffect(()=>{void load()},[load]);
 const sent=messages.filter(m=>!["queued","sending","failed","skipped"].includes(m.status)).length;const hard=bounces.filter(b=>b.bounce_type==="hard").length;const soft=bounces.filter(b=>b.bounce_type==="soft").length;const unknown=bounces.filter(b=>b.bounce_type==="unknown").length;const bounceRate=pct(bounces.length,sent);const invalidLeads=leads.filter(l=>l.email_status==="invalid").length;const ready=mailboxes.filter(m=>m.status==="ready").length;
 const health=bounceRate<2?"Gesund":bounceRate<5?"Beobachten":"Kritisch";const healthTone=bounceRate<2?"green":"hot";
 const mailboxRows=useMemo(()=>mailboxes.map(m=>{const mbSent=messages.filter(x=>x.mailbox_id===m.id&&!["queued","sending","failed","skipped"].includes(x.status)).length;const mbBounces=bounces.filter(x=>x.mailbox_id===m.id);return{...m,weekSent:mbSent,weekBounces:mbBounces.length,weekRate:pct(mbBounces.length,mbSent),hard:mbBounces.filter(x=>x.bounce_type==="hard").length}}).sort((a,b)=>b.weekRate-a.weekRate),[mailboxes,messages,bounces]);
 return <main className="os-root" style={{minHeight:"100vh"}}><div className="os-content" style={{maxWidth:1400,margin:"0 auto",paddingTop:28}}>
  <div className="os-section-head"><div><div className="os-kicker">Email Operations</div><h1 className="os-title">Deliverability Center</h1><p>Bounces, Mailbox-Gesundheit und Versandrisiken der letzten 7 Tage.</p></div><div className="os-toolbar"><a className="os-btn" href="/command">← Heute</a><a className="os-btn" href="/campaign-lab">Domain Health</a><button className="os-btn" onClick={()=>void load()}>↻ Aktualisieren</button></div></div>{error?<div className="os-error">{error}</div>:null}
  <div className="os-grid os-kpis" style={{marginTop:18}}>{[[sent,"Versendet 7 Tage","Outbound Messages"],[`${bounceRate}%`,"Bounce Rate",health],[hard,"Hard Bounces",`${invalidLeads} ungültige Leads`],[soft,"Soft Bounces",`${unknown} unbekannt`],[ready,"Mailboxen bereit",`${mailboxes.length} gesamt`]].map(([v,l,s])=><div className="os-card os-kpi" key={String(l)}><div className="os-kpi-label">{l}</div><div className="os-kpi-value">{v}</div><div className="os-kpi-sub">{s}</div></div>)}</div>
  <section className="os-card os-section" style={{marginTop:18}}><div className="os-section-head"><div><div className="os-kicker">Sending Health</div><h2>Mailboxen</h2></div><span className={`os-pill ${healthTone}`}>{health}</span></div><div className="os-tablewrap"><table className="os-table"><thead><tr><th>Mailbox</th><th>Status</th><th>7T Versand</th><th>Bounces</th><th>Rate</th><th>Ramping</th><th>Letzter Bounce Sync</th></tr></thead><tbody>{mailboxRows.length?mailboxRows.map(m=><tr key={m.id}><td><strong>{m.email_address}</strong>{m.last_error||m.last_bounce_error?<small style={{display:"block",color:"#b54a0f"}}>{m.last_bounce_error||m.last_error}</small>:null}</td><td><span className={`os-pill ${m.status==="ready"?"green":m.status==="error"?"hot":""}`}>{m.status}</span></td><td>{m.weekSent}</td><td>{m.weekBounces} <small>({m.hard} hard)</small></td><td><strong>{m.weekRate}%</strong></td><td>{m.ramp_enabled?`${m.ramp_start_limit} → +${m.ramp_daily_increment}/Tag → ${m.ramp_target_limit}`:"aus"}</td><td>{fmt(m.last_bounce_sync_at)}</td></tr>):<tr><td colSpan={7}><div className="os-empty">Noch keine Mailboxen verbunden.</div></td></tr>}</tbody></table></div></section>
  <section className="os-card os-section" style={{marginTop:18}}><div className="os-section-head"><div><div className="os-kicker">Bounce Log</div><h2>Letzte Rückläufer</h2></div><span className="os-pill">{bounces.length} / 7 Tage</span></div><div className="os-tablewrap"><table className="os-table"><thead><tr><th>Zeit</th><th>Typ</th><th>Adresse</th><th>Lead</th><th>Mailbox</th><th>Diagnose</th></tr></thead><tbody>{bounces.length?bounces.slice(0,100).map(b=>{const lead=leads.find(l=>l.id===b.lead_id);const mb=mailboxes.find(m=>m.id===b.mailbox_id);return <tr key={b.id}><td>{fmt(b.occurred_at)}</td><td><span className={`os-pill ${b.bounce_type==="hard"?"hot":b.bounce_type==="soft"?"":"green"}`}>{b.bounce_type}</span></td><td><strong>{b.bounced_email}</strong></td><td>{lead?.company_name||"—"}</td><td>{mb?.email_address||"—"}</td><td><small>{b.diagnostic||"—"}</small></td></tr>}):<tr><td colSpan={6}><div className="os-empty">Keine Bounces in den letzten 7 Tagen.</div></td></tr>}</tbody></table></div></section>
  <div className="os-callout" style={{marginTop:16}}><strong>Radar-Regel:</strong> Hard Bounces setzen die E-Mail automatisch auf ungültig und stoppen offene Sequenzen. Soft/Unknown stoppen den betroffenen Kampagnenlauf, sperren die Adresse aber nicht dauerhaft.</div>
 </div></main>;
}
