"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";
import { scoreEnergyLead, slugifyCompany, type EnergyLeadInput } from "@/lib/energy-score";

type LeadStatus = "new"|"research"|"ready"|"contacted"|"engaged"|"qualified"|"meeting"|"proposal"|"won"|"lost"|"nurture";
type Lead = EnergyLeadInput & { id:string; user_id:string; pv_score:number; energy_score:number; intent_score:number; contactability_score:number; total_score:number; summary:string|null; pitch:string|null; next_action:string|null; status:LeadStatus; created_at:string };
type VideoPage = { id:string; lead_id:string; slug:string; company_name:string; prospect_name:string|null; website_url:string|null; presenter_video_url:string|null; headline:string; cta_url:string|null; duration_seconds:number; status:string; created_at:string };
type VideoEvent = { video_page_id:string; event_type:"view"|"play"|"progress"|"cta_click"; watch_percent:number|null; created_at:string };
type Mailbox = { id:string; email_address:string; from_name:string|null; provider:string; daily_limit:number; status:string };
type Campaign = { id:string; name:string; status:string; subject_template:string|null; body_template:string|null; daily_limit:number };
type Tab = "leads"|"video"|"mailboxes"|"campaigns"|"audit"|"seo";

type AuditResult = { url:string; score:number; seo:number; conversion:number; trust:number; technical:number; findings:{severity:string;title:string;detail:string;recommendation:string}[]; summary:string };
type KeywordIdea = { keyword:string; intent:string; opportunity:number };

const STATUS_LABELS: Record<LeadStatus,string> = {new:"Neu",research:"Research",ready:"Bereit",contacted:"Kontaktiert",engaged:"Interessiert",qualified:"Qualifiziert",meeting:"Termin",proposal:"Angebot",won:"Gewonnen",lost:"Verloren",nurture:"Wiedervorlage"};
const STATUSES = Object.keys(STATUS_LABELS) as LeadStatus[];
const text = (v:FormDataEntryValue|null) => String(v ?? "").trim() || null;
const num = (v:FormDataEntryValue|null) => { const n=Number(String(v ?? "").trim()); return Number.isFinite(n)&&n>0?n:null; };
const scoreClass=(n:number)=>n>=80?"score hot":n>=65?"score warm":"score";

function stats(events:VideoEvent[], id:string){const rows=events.filter(e=>e.video_page_id===id);return{views:rows.filter(e=>e.event_type==="view").length,watch:rows.reduce((m,e)=>Math.max(m,e.watch_percent??0),0),clicks:rows.filter(e=>e.event_type==="cta_click").length};}

export function EnergyRadarApp({user}:{user:User}){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
  const [tab,setTab]=useState<Tab>("leads");
  const [leads,setLeads]=useState<Lead[]>([]);
  const [videos,setVideos]=useState<VideoPage[]>([]);
  const [events,setEvents]=useState<VideoEvent[]>([]);
  const [mailboxes,setMailboxes]=useState<Mailbox[]>([]);
  const [campaigns,setCampaigns]=useState<Campaign[]>([]);
  const [selectedId,setSelectedId]=useState<string|null>(null);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState<string|null>(null);
  const [message,setMessage]=useState<string|null>(null);
  const [audit,setAudit]=useState<AuditResult|null>(null);
  const [keywords,setKeywords]=useState<KeywordIdea[]>([]);
  const selected=leads.find(l=>l.id===selectedId)??leads[0]??null;
  const selectedVideo=selected?videos.find(v=>v.lead_id===selected.id&&v.status!=="archived")??null:null;

  const load=useCallback(async()=>{
    if(!supabase)return;
    const [l,v,e,m,c]=await Promise.all([
      supabase.from("energy_leads").select("*").eq("user_id",user.id).order("total_score",{ascending:false}).limit(1000),
      supabase.from("energy_video_pages").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(1000),
      supabase.from("energy_video_events").select("video_page_id,event_type,watch_percent,created_at").order("created_at",{ascending:false}).limit(5000),
      supabase.from("energy_mailboxes").select("*").eq("user_id",user.id).order("created_at",{ascending:true}),
      supabase.from("energy_campaigns").select("*").eq("user_id",user.id).order("created_at",{ascending:false}),
    ]);
    if(l.error){setError(l.error.message);return;} setLeads((l.data??[]) as Lead[]); if(!selectedId&&l.data?.length)setSelectedId(String(l.data[0].id));
    if(!v.error)setVideos((v.data??[]) as VideoPage[]); if(!e.error)setEvents((e.data??[]) as VideoEvent[]); if(!m.error)setMailboxes((m.data??[]) as Mailbox[]); if(!c.error)setCampaigns((c.data??[]) as Campaign[]);
  },[selectedId,supabase,user.id]);
  useEffect(()=>{void load();},[load]);

  async function createLead(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!supabase)return;const f=new FormData(event.currentTarget);const input:EnergyLeadInput={company_name:String(f.get("company_name")??"").trim(),website:text(f.get("website")),city:text(f.get("city")),industry:text(f.get("industry")),employees:num(f.get("employees")),location_count:num(f.get("location_count"))??1,roof_area_m2:num(f.get("roof_area_m2")),annual_energy_kwh:num(f.get("annual_energy_kwh")),pv_present:f.get("pv_present")==="yes"?true:f.get("pv_present")==="no"?false:null,contact_name:text(f.get("contact_name")),phone:text(f.get("phone")),email:text(f.get("email"))};if(!input.company_name)return;const s=scoreEnergyLead(input);setBusy(true);setError(null);const r=await supabase.from("energy_leads").insert({user_id:user.id,...input,pv_score:s.pvScore,energy_score:s.energyScore,intent_score:s.intentScore,contactability_score:s.contactabilityScore,total_score:s.totalScore,summary:s.summary,pitch:s.pitch,next_action:s.nextAction,status:s.totalScore>=75?"ready":"research"}).select("*").single();setBusy(false);if(r.error){setError(r.error.message);return;}event.currentTarget.reset();setSelectedId(String(r.data.id));setMessage(`${input.company_name}: Opportunity Score ${s.totalScore}/100.`);await load();}
  async function updateStatus(status:LeadStatus){if(!supabase||!selected)return;setBusy(true);const r=await supabase.from("energy_leads").update({status,updated_at:new Date().toISOString()}).eq("id",selected.id).eq("user_id",user.id);setBusy(false);if(r.error)setError(r.error.message);else await load();}
  async function recalc(){if(!supabase||!selected)return;const s=scoreEnergyLead(selected);setBusy(true);const r=await supabase.from("energy_leads").update({pv_score:s.pvScore,energy_score:s.energyScore,intent_score:s.intentScore,contactability_score:s.contactabilityScore,total_score:s.totalScore,summary:s.summary,pitch:s.pitch,next_action:s.nextAction,updated_at:new Date().toISOString()}).eq("id",selected.id).eq("user_id",user.id);setBusy(false);if(r.error)setError(r.error.message);else{setMessage("Scores und Sales Angle neu berechnet.");await load();}}
  async function createVideo(){if(!supabase||!selected)return;if(selectedVideo){setTab("video");return;}const slug=slugifyCompany(selected.company_name);const bullets=[`${selected.pv_score}/100 PV-Potenzial`,`${selected.energy_score}/100 Energieeffizienz-Potenzial`,selected.roof_area_m2?`ca. ${selected.roof_area_m2} m² erfasste Dachfläche`:"Dach- und Verbrauchsdaten im Potenzialcheck konkretisieren"];setBusy(true);const r=await supabase.from("energy_video_pages").insert({user_id:user.id,lead_id:selected.id,slug,company_name:selected.company_name,prospect_name:selected.contact_name,website_url:selected.website,headline:`Kurze Energie-Analyse für ${selected.company_name}`,intro_text:selected.summary,bullets,cta_label:"Kostenlosen Potenzialcheck vereinbaren",cta_url:process.env.NEXT_PUBLIC_WALKENHORST_CALENDAR_URL||"https://www.walkenhorst-eko.de/",duration_seconds:97,status:"ready",is_public:true});setBusy(false);if(r.error)setError(r.error.message);else{setMessage("Personalisierte Video-Landingpage erstellt.");setTab("video");await load();}}
  async function createMailbox(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!supabase)return;const f=new FormData(event.currentTarget);const email=String(f.get("email")??"").trim().toLowerCase();if(!email)return;setBusy(true);const r=await supabase.from("energy_mailboxes").insert({user_id:user.id,email_address:email,from_name:text(f.get("from_name")),provider:"smtp",daily_limit:Math.min(30,num(f.get("daily_limit"))??30),status:"setup"});setBusy(false);if(r.error)setError(r.error.message);else{event.currentTarget.reset();await load();}}
  async function createCampaign(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!supabase)return;const f=new FormData(event.currentTarget);const name=String(f.get("name")??"").trim();if(!name)return;setBusy(true);const r=await supabase.from("energy_campaigns").insert({user_id:user.id,name,status:"draft",subject_template:text(f.get("subject")),body_template:text(f.get("body")),daily_limit:Math.min(150,num(f.get("daily_limit"))??30)});setBusy(false);if(r.error)setError(r.error.message);else{event.currentTarget.reset();await load();}}
  async function runAudit(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);setBusy(true);setAudit(null);const res=await fetch("/api/website-audit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url:String(f.get("url")??"")})});const data=await res.json();setBusy(false);if(!res.ok)setError(data.error||"Audit fehlgeschlagen");else setAudit(data);}
  async function runKeywords(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);setBusy(true);const res=await fetch("/api/keyword-research",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({keyword:String(f.get("keyword")??""),country:"DE",language:"de"})});const data=await res.json();setBusy(false);if(!res.ok)setError(data.error||"Keyword-Recherche fehlgeschlagen");else setKeywords(data.ideas??[]);}

  const hot=leads.filter(l=>l.total_score>=80).length;const videoViews=events.filter(e=>e.event_type==="view").length;const meetings=leads.filter(l=>l.status==="meeting"||l.status==="proposal"||l.status==="won").length;
  return <main className="shell">
    <header className="topbar"><div className="brand"><div className="logo">ER</div><div><div className="eyebrow">Walkenhorst</div><strong>Energy Sales Radar</strong></div></div><div className="actions"><span className="badge"><span className="dot"/>System aktiv</span><button className="button" onClick={()=>void supabase?.auth.signOut()}>Abmelden</button></div></header>
    <section className="card hero"><div className="eyebrow">Revenue Intelligence · PV · Energieberatung</div><h1>Die besten Energie-Leads zuerst.</h1><p className="muted">Unternehmen bewerten, den passenden Sales Angle erzeugen, personalisierte Video-Analysen senden und exakt sehen, welcher Prospect Interesse zeigt.</p></section>
    <section className="grid stats">{[[leads.length,"Leads"],[hot,"A-Leads ≥80"],[videos.length,"Video-Seiten"],[videoViews,"Video Views"],[meetings,"Termine+" ]].map(([v,l])=><article className="card stat" key={String(l)}><span className="muted">{l}</span><strong>{v}</strong></article>)}</section>
    {error&&<div className="error" style={{marginBottom:14}}>{error}<button style={{float:"right"}} onClick={()=>setError(null)}>×</button></div>}{message&&<div className="success" style={{marginBottom:14}}>{message}</div>}
    <div className="tabs">{(["leads","video","mailboxes","campaigns","audit","seo"] as Tab[]).map(t=><button className={`tab ${tab===t?"active":""}`} key={t} onClick={()=>setTab(t)}>{({leads:"Energy Radar",video:"Fake Loom",mailboxes:"Mailboxen",campaigns:"Kampagnen",audit:"Website Audit",seo:"SEO Radar"} as Record<Tab,string>)[t]}</button>)}</div>

    {tab==="leads"&&<section className="grid content-grid"><article className="card table-wrap"><div className="topbar"><div><div className="eyebrow">CRM + Opportunity Engine</div><h2>Priorisierte Unternehmen</h2></div></div>{leads.length===0?<p className="muted">Noch keine Leads. Lege rechts den ersten Gewerbekunden an.</p>:<table><thead><tr><th>Score</th><th>Unternehmen</th><th>Ort</th><th>Branche</th><th>PV</th><th>Energie</th><th>Status</th></tr></thead><tbody>{leads.map(l=><tr key={l.id} onClick={()=>setSelectedId(l.id)} style={{cursor:"pointer",opacity:selected?.id===l.id?1:.78}}><td><div className={scoreClass(l.total_score)}>{l.total_score}</div></td><td><strong>{l.company_name}</strong><div className="muted" style={{fontSize:12}}>{l.contact_name||l.email||l.phone||"Kontakt anreichern"}</div></td><td>{l.city||"–"}</td><td>{l.industry||"–"}</td><td>{l.pv_score}</td><td>{l.energy_score}</td><td><span className="status">{STATUS_LABELS[l.status]}</span></td></tr>)}</tbody></table>}</article><aside className="grid">
      <section className="card"><div className="eyebrow">Neuer Lead</div><h2 style={{marginTop:7}}>Unternehmen bewerten</h2><form className="form" onSubmit={createLead}><div className="form-grid"><div className="field"><label>Unternehmen *</label><input name="company_name" required/></div><div className="field"><label>Ort</label><input name="city"/></div><div className="field"><label>Website</label><input name="website" placeholder="https://…"/></div><div className="field"><label>Branche</label><input name="industry" placeholder="Produktion, Hotel, Logistik …"/></div><div className="field"><label>Mitarbeiter</label><input name="employees" type="number" min="1"/></div><div className="field"><label>Standorte</label><input name="location_count" type="number" min="1" defaultValue="1"/></div><div className="field"><label>Dachfläche m²</label><input name="roof_area_m2" type="number" min="1"/></div><div className="field"><label>Verbrauch kWh/Jahr</label><input name="annual_energy_kwh" type="number" min="1"/></div><div className="field"><label>PV vorhanden?</label><select name="pv_present" defaultValue="unknown"><option value="unknown">Unbekannt</option><option value="no">Nein</option><option value="yes">Ja</option></select></div><div className="field"><label>Ansprechpartner</label><input name="contact_name"/></div><div className="field"><label>Telefon</label><input name="phone"/></div><div className="field"><label>E-Mail</label><input name="email" type="email"/></div></div><button disabled={busy} className="button primary">{busy?"Berechne …":"Lead analysieren"}</button></form></section>
      {selected&&<section className="card"><div className="eyebrow">AI Sales Brain</div><h2 style={{marginTop:7}}>{selected.company_name}</h2><div className="grid stats" style={{gridTemplateColumns:"repeat(2,1fr)",margin:"12px 0"}}><div><span className="muted">PV</span><strong style={{fontSize:24}}>{selected.pv_score}</strong></div><div><span className="muted">Energie</span><strong style={{fontSize:24}}>{selected.energy_score}</strong></div><div><span className="muted">Intent</span><strong style={{fontSize:24}}>{selected.intent_score}</strong></div><div><span className="muted">Gesamt</span><strong style={{fontSize:24}}>{selected.total_score}</strong></div></div><div className="callout"><strong>Analyse</strong><p className="muted" style={{margin:"8px 0 0"}}>{selected.summary}</p></div><div className="divider"/><strong>Call-Einstieg</strong><p className="muted" style={{lineHeight:1.55,marginTop:8}}>{selected.pitch}</p><strong>Next Best Action</strong><p className="muted" style={{marginTop:8}}>{selected.next_action}</p><div className="actions"><button className="button primary" onClick={createVideo}>Fake Loom erstellen</button><button className="button" onClick={recalc}>Neu scoren</button></div><div className="field" style={{marginTop:12}}><label>CRM Status</label><select value={selected.status} onChange={e=>void updateStatus(e.target.value as LeadStatus)}>{STATUSES.map(s=><option key={s} value={s}>{STATUS_LABELS[s]}</option>)}</select></div></section>}
    </aside></section>}

    {tab==="video"&&<section className="grid content-grid"><article className="card"><div className="eyebrow">Personalized Video Outreach</div><h2>Fake-Loom Studio</h2>{!selected?<p className="muted">Wähle zuerst einen Lead.</p>:!selectedVideo?<><p className="muted">Erzeuge aus dem Lead eine individuelle Video-Landingpage mit Website-Simulation, Talking-Head-Platzhalter, Findings und CTA.</p><button className="button primary" onClick={createVideo}>Für {selected.company_name} erstellen</button></>:<><div className="callout"><strong>{selectedVideo.headline}</strong><p className="muted" style={{margin:"8px 0 0"}}>/v/{selectedVideo.slug}</p></div><div className="actions" style={{marginTop:12}}><a className="button primary" target="_blank" href={`/v/${selectedVideo.slug}`}>Landingpage öffnen</a><button className="button" onClick={()=>navigator.clipboard.writeText(`${location.origin}/v/${selectedVideo.slug}`)}>Link kopieren</button></div><div className="divider"/><div className="grid stats" style={{gridTemplateColumns:"repeat(3,1fr)"}}>{(()=>{const s=stats(events,selectedVideo.id);return [[s.views,"Views"],[`${s.watch}%`,"Max Watch"],[s.clicks,"CTA Klicks"]].map(([v,l])=><div key={String(l)}><span className="muted">{l}</span><strong style={{display:"block",fontSize:28}}>{v}</strong></div>)})()}</div><div className="field"><label>Presenter-Video URL (optional)</label><input value={selectedVideo.presenter_video_url||""} onChange={async e=>{if(!supabase)return;await supabase.from("energy_video_pages").update({presenter_video_url:e.target.value||null}).eq("id",selectedVideo.id).eq("user_id",user.id);await load();}} placeholder="https://…/intro.mp4"/></div></>}</article><aside className="card"><div className="eyebrow">Intent Tracking</div><h2>Hot-Lead-Logik</h2><div className="bullet"><span className="tick">1</span><div><strong>Video gestartet</strong><div className="muted">Lead bekommt erstes Intent-Signal.</div></div></div><div className="bullet"><span className="tick">2</span><div><strong>≥50 % gesehen</strong><div className="muted">Priorität für Follow-up steigt.</div></div></div><div className="bullet"><span className="tick">3</span><div><strong>≥90 % / CTA</strong><div className="muted">Sofortiger Call empfohlen.</div></div></div></aside></section>}

    {tab==="mailboxes"&&<section className="grid content-grid"><article className="card"><div className="eyebrow">Email Infrastructure</div><h2>Mailboxen</h2>{mailboxes.length===0?<p className="muted">Noch keine Mailbox hinterlegt.</p>:mailboxes.map(m=><div className="kv" key={m.id}><span><strong>{m.email_address}</strong><div className="muted">{m.from_name||"Walkenhorst"} · max. {m.daily_limit}/Tag</div></span><span className="status">{m.status}</span></div>)}</article><aside className="card"><h2>Mailbox anlegen</h2><form className="form" onSubmit={createMailbox}><div className="field"><label>E-Mail</label><input name="email" type="email" required/></div><div className="field"><label>Absendername</label><input name="from_name"/></div><div className="field"><label>Tageslimit</label><input name="daily_limit" type="number" min="1" max="30" defaultValue="30"/></div><button className="button primary" disabled={busy}>Hinterlegen</button></form><p className="muted" style={{marginTop:12,fontSize:12}}>V1 speichert nur Konfiguration und Limits. SMTP/OAuth-Zugangsdaten gehören später verschlüsselt in den Versand-Provider, nicht in die Browser-Datenbank.</p></aside></section>}

    {tab==="campaigns"&&<section className="grid content-grid"><article className="card"><div className="eyebrow">Outbound Sequences</div><h2>Kampagnen</h2>{campaigns.length===0?<p className="muted">Noch keine Kampagne.</p>:campaigns.map(c=><div className="kv" key={c.id}><span><strong>{c.name}</strong><div className="muted">{c.subject_template||"Kein Betreff"} · {c.daily_limit}/Tag</div></span><span className="status">{c.status}</span></div>)}</article><aside className="card"><h2>Kampagne erstellen</h2><form className="form" onSubmit={createCampaign}><div className="field"><label>Name</label><input name="name" required/></div><div className="field"><label>Betreff</label><input name="subject" placeholder="{{company}} – kurze Analyse"/></div><div className="field"><label>Mail</label><textarea name="body" placeholder="Hallo {{contact}}, ich habe mir {{company}} angesehen … {{video_url}}"/></div><div className="field"><label>Tageslimit gesamt</label><input name="daily_limit" type="number" min="1" max="150" defaultValue="30"/></div><button className="button primary" disabled={busy}>Kampagne speichern</button></form></aside></section>}

    {tab==="audit"&&<section className="grid content-grid"><article className="card"><div className="eyebrow">Website Intelligence</div><h2>High-End Schnell-Audit</h2><form className="form" onSubmit={runAudit}><div className="field"><label>Website</label><input name="url" defaultValue={selected?.website||""} placeholder="https://unternehmen.de" required/></div><button className="button primary" disabled={busy}>Website analysieren</button></form>{audit&&<><div className="divider"/><div className="grid stats" style={{gridTemplateColumns:"repeat(5,1fr)"}}>{[[audit.score,"Gesamt"],[audit.seo,"SEO"],[audit.conversion,"Conversion"],[audit.trust,"Trust"],[audit.technical,"Technik"]].map(([v,l])=><div key={String(l)}><span className="muted">{l}</span><strong style={{display:"block",fontSize:26}}>{v}</strong></div>)}</div><div className="callout"><strong>Executive Summary</strong><p className="muted" style={{margin:"8px 0 0"}}>{audit.summary}</p></div>{audit.findings.map((f,i)=><div className="bullet" key={`${f.title}-${i}`}><span className="tick">{i+1}</span><div><strong>{f.title}</strong><div className="muted">{f.detail}</div><div style={{marginTop:5}}>{f.recommendation}</div></div></div>)}</>}</article><aside className="card"><h2>Sales-Nutzung</h2><p className="muted">Nutze den Audit als Zusatzsignal: schwache Website + hohes Energiepotenzial = besonders guter Gesprächseinstieg für eine umfassende Digital-/Energieberatung.</p></aside></section>}

    {tab==="seo"&&<section className="grid content-grid"><article className="card"><div className="eyebrow">SEO Radar</div><h2>Keyword Opportunities</h2><form className="form" onSubmit={runKeywords}><div className="field"><label>Seed Keyword</label><input name="keyword" placeholder="energieberatung gewerbe" required/></div><button className="button primary" disabled={busy}>Keywords finden</button></form>{keywords.length>0&&<div className="table-wrap" style={{marginTop:16}}><table style={{minWidth:600}}><thead><tr><th>Keyword</th><th>Intent</th><th>Opportunity</th></tr></thead><tbody>{keywords.map(k=><tr key={k.keyword}><td><strong>{k.keyword}</strong></td><td>{k.intent}</td><td><div className={scoreClass(k.opportunity)}>{k.opportunity}</div></td></tr>)}</tbody></table></div>}</article><aside className="card"><h2>Kostenlose V1</h2><p className="muted">Die V1 nutzt Keyword-Vorschläge und Intent-Signale. Exaktes monatliches Suchvolumen wird nicht erfunden; dafür wird später der Google-Ads-Keyword-Planning-Connector ergänzt.</p></aside></section>}
  </main>;
}
