"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";
import styles from "./lead-detail-workspace.module.css";

type Lead = {
  id:string;user_id:string;company_name:string;website:string|null;city:string|null;industry:string|null;employees:number|null;location_count:number;
  roof_area_m2:number|null;annual_energy_kwh:number|null;pv_present:boolean|null;contact_name:string|null;phone:string|null;email:string|null;
  email_status:string|null;total_score:number;pv_score:number;energy_score:number;intent_score:number;contactability_score:number;summary:string|null;pitch:string|null;
  next_action:string|null;status:string;address:string|null;postcode:string|null;do_not_contact:boolean;next_action_at:string|null;updated_at:string;
};
type Followup={id:string;title:string;due_at:string;priority:string;status:string;reason:string|null};
type Activity={id:string;activity_type:string;title:string;detail:string|null;created_at:string};
type MessageRow={id:string;direction:string;status:string;subject:string|null;from_email:string|null;to_email:string|null;sent_at:string|null;replied_at:string|null;created_at:string};
type VideoPage={id:string;slug:string;status:string;is_public:boolean;headline:string|null;cta_label:string|null;rendered_video_url:string|null};

const STATUS_LABEL:Record<string,string>={new:"Neu",research:"Research",ready:"Bereit",contacted:"Kontaktiert",engaged:"Interessiert",qualified:"Qualifiziert",meeting:"Termin",proposal:"Angebot",won:"Gewonnen",lost:"Verloren",nurture:"Wiedervorlage"};
function fmt(value:string|null|undefined){if(!value)return"—";try{return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}catch{return"—"}}
function n(value:FormDataEntryValue|null){const raw=String(value||"").trim();if(!raw)return null;const parsed=Number(raw);return Number.isFinite(parsed)?parsed:null}
function s(value:FormDataEntryValue|null){const raw=String(value||"").trim();return raw||null}

export function LeadDetailWorkspace(){
  const params=useParams<{id:string}>();
  const leadId=Array.isArray(params.id)?params.id[0]:params.id;
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
  const[lead,setLead]=useState<Lead|null>(null);const[followups,setFollowups]=useState<Followup[]>([]);const[activities,setActivities]=useState<Activity[]>([]);const[messages,setMessages]=useState<MessageRow[]>([]);const[video,setVideo]=useState<VideoPage|null>(null);
  const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);

  const load=useCallback(async()=>{if(!supabase||!leadId)return;setLoading(true);setError(null);try{const session=(await supabase.auth.getSession()).data.session;if(!session)throw new Error("Session abgelaufen.");const uid=session.user.id;const[l,f,a,m,v]=await Promise.all([
    supabase.from("energy_leads").select("*").eq("id",leadId).eq("user_id",uid).single(),
    supabase.from("energy_followups").select("id,title,due_at,priority,status,reason").eq("lead_id",leadId).eq("user_id",uid).order("due_at",{ascending:true}),
    supabase.from("energy_activities").select("id,activity_type,title,detail,created_at").eq("lead_id",leadId).eq("user_id",uid).order("created_at",{ascending:false}).limit(100),
    supabase.from("energy_messages").select("id,direction,status,subject,from_email,to_email,sent_at,replied_at,created_at").eq("lead_id",leadId).eq("user_id",uid).order("created_at",{ascending:false}).limit(100),
    supabase.from("energy_video_pages").select("id,slug,status,is_public,headline,cta_label,rendered_video_url").eq("lead_id",leadId).eq("user_id",uid).neq("status","archived").order("updated_at",{ascending:false}).limit(1).maybeSingle(),
  ]);if(l.error)throw l.error;setLead(l.data as Lead);if(!f.error)setFollowups((f.data||[]) as Followup[]);if(!a.error)setActivities((a.data||[]) as Activity[]);if(!m.error)setMessages((m.data||[]) as MessageRow[]);if(!v.error)setVideo((v.data||null) as VideoPage|null)}catch(e){setError(e instanceof Error?e.message:"Lead konnte nicht geladen werden.")}finally{setLoading(false)}},[supabase,leadId]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<{table?:string;id?:string}>).detail;if(detail?.table==="energy_leads"&&(!detail.id||detail.id===leadId))void load()};window.addEventListener("walkenhorst:data-changed",handler);return()=>window.removeEventListener("walkenhorst:data-changed",handler)},[leadId,load]);

  async function saveLead(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!supabase||!lead)return;setBusy(true);setError(null);setNotice(null);try{const session=(await supabase.auth.getSession()).data.session;if(!session)throw new Error("Session abgelaufen.");const f=new FormData(event.currentTarget);const payload={company_name:String(f.get("company_name")||"").trim(),contact_name:s(f.get("contact_name")),email:s(f.get("email")),phone:s(f.get("phone")),website:s(f.get("website")),city:s(f.get("city")),industry:s(f.get("industry")),address:s(f.get("address")),postcode:s(f.get("postcode")),employees:n(f.get("employees")),location_count:n(f.get("location_count"))??1,roof_area_m2:n(f.get("roof_area_m2")),annual_energy_kwh:n(f.get("annual_energy_kwh")),pv_present:f.get("pv_present")==="unknown"?null:f.get("pv_present")==="yes",status:String(f.get("status")||"new"),summary:s(f.get("summary")),pitch:s(f.get("pitch")),next_action:s(f.get("next_action")),next_action_at:s(f.get("next_action_at")),do_not_contact:f.get("do_not_contact")==="on",updated_at:new Date().toISOString()};const result=await supabase.from("energy_leads").update(payload).eq("id",lead.id).eq("user_id",session.user.id);if(result.error)throw result.error;await supabase.from("energy_activities").insert({user_id:session.user.id,lead_id:lead.id,activity_type:"crm_updated",title:"Lead im CRM aktualisiert",detail:"Stammdaten und Vertriebsinformationen wurden angepasst."});setNotice("Lead gespeichert.");await load()}catch(e){setError(e instanceof Error?e.message:"Speichern fehlgeschlagen.")}finally{setBusy(false)}}
  async function createFollowup(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!supabase||!lead)return;setBusy(true);setError(null);try{const session=(await supabase.auth.getSession()).data.session;if(!session)throw new Error("Session abgelaufen.");const f=new FormData(event.currentTarget);const result=await supabase.from("energy_followups").insert({user_id:session.user.id,lead_id:lead.id,title:String(f.get("title")||"Follow-up").trim(),due_at:String(f.get("due_at")||new Date().toISOString()),priority:String(f.get("priority")||"normal"),reason:s(f.get("reason"))});if(result.error)throw result.error;event.currentTarget.reset();setNotice("Follow-up angelegt.");await load()}catch(e){setError(e instanceof Error?e.message:"Follow-up konnte nicht erstellt werden.")}finally{setBusy(false)}}
  async function finishFollowup(id:string){if(!supabase)return;const result=await supabase.from("energy_followups").update({status:"done",completed_at:new Date().toISOString()}).eq("id",id);if(result.error)setError(result.error.message);else await load()}
  async function createNote(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!supabase||!lead)return;const f=new FormData(event.currentTarget);const detail=String(f.get("note")||"").trim();if(!detail)return;setBusy(true);try{const session=(await supabase.auth.getSession()).data.session;if(!session)throw new Error("Session abgelaufen.");const result=await supabase.from("energy_activities").insert({user_id:session.user.id,lead_id:lead.id,activity_type:"note",title:"CRM-Notiz",detail});if(result.error)throw result.error;event.currentTarget.reset();await load()}catch(e){setError(e instanceof Error?e.message:"Notiz konnte nicht gespeichert werden.")}finally{setBusy(false)}}
  function openStudio(){if(!lead)return;window.localStorage.setItem("walkenhorst.assistant.studioAction",JSON.stringify({type:"studio",action:"select_lead",leadId:lead.id}));window.location.assign("/studio")}

  if(loading)return <div className={styles.loading}>Lead wird geladen …</div>;
  if(!lead)return <div className={styles.loading}>{error||"Lead nicht gefunden."}</div>;
  const inbound=messages.filter(m=>m.direction==="inbound").length;const sent=messages.filter(m=>m.direction==="outbound").length;const openFollowups=followups.filter(f=>f.status==="open");
  return <div className={styles.root}>
    <div className={styles.topbar}><div><a href="/dashboard?section=leads" className={styles.back}>← CRM</a><div className={styles.eyebrow}>Lead Workspace</div><h1>{lead.company_name}</h1><p>{[lead.contact_name,lead.city,lead.industry].filter(Boolean).join(" · ")||"Unternehmensprofil"}</p></div><div className={styles.actions}><button onClick={openStudio}>Studio öffnen</button>{video?<a href={`/v/${video.slug}`} target="_blank">Live-Seite ↗</a>:null}{lead.website?<a href={/^https?:\/\//.test(lead.website)?lead.website:`https://${lead.website}`} target="_blank">Website ↗</a>:null}</div></div>
    {error?<div className={styles.error}>{error}</div>:null}{notice?<div className={styles.success}>{notice}</div>:null}
    <div className={styles.kpis}><div><span>Opportunity</span><strong>{lead.total_score}</strong></div><div><span>Intent</span><strong>{lead.intent_score}</strong></div><div><span>PV / Energie</span><strong>{lead.pv_score} / {lead.energy_score}</strong></div><div><span>Nachrichten</span><strong>{sent} / {inbound}</strong><small>gesendet / Antworten</small></div><div><span>Follow-ups</span><strong>{openFollowups.length}</strong><small>offen</small></div></div>
    <div className={styles.layout}><main className={styles.main}><form className={styles.card} onSubmit={saveLead} key={lead.updated_at}><div className={styles.cardHead}><div><span>CRM-Daten</span><h2>Lead bearbeiten</h2></div><button className={styles.primary} disabled={busy}>{busy?"Speichert …":"Änderungen speichern"}</button></div><div className={styles.grid}>
      <label><span>Unternehmen *</span><input name="company_name" required defaultValue={lead.company_name}/></label><label><span>Status</span><select name="status" defaultValue={lead.status}>{Object.entries(STATUS_LABEL).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>
      <label><span>Ansprechpartner</span><input name="contact_name" defaultValue={lead.contact_name||""}/></label><label><span>E-Mail</span><input name="email" type="email" defaultValue={lead.email||""}/></label><label><span>Telefon</span><input name="phone" defaultValue={lead.phone||""}/></label><label><span>Website</span><input name="website" defaultValue={lead.website||""}/></label>
      <label><span>Ort</span><input name="city" defaultValue={lead.city||""}/></label><label><span>Branche</span><input name="industry" defaultValue={lead.industry||""}/></label><label><span>Adresse</span><input name="address" defaultValue={lead.address||""}/></label><label><span>PLZ</span><input name="postcode" defaultValue={lead.postcode||""}/></label>
      <label><span>Mitarbeiter</span><input name="employees" type="number" min="0" defaultValue={lead.employees??""}/></label><label><span>Standorte</span><input name="location_count" type="number" min="1" defaultValue={lead.location_count||1}/></label><label><span>Dachfläche m²</span><input name="roof_area_m2" type="number" min="0" step="1" defaultValue={lead.roof_area_m2??""}/></label><label><span>Verbrauch kWh/Jahr</span><input name="annual_energy_kwh" type="number" min="0" step="1" defaultValue={lead.annual_energy_kwh??""}/></label>
      <label><span>PV vorhanden?</span><select name="pv_present" defaultValue={lead.pv_present===null?"unknown":lead.pv_present?"yes":"no"}><option value="unknown">Unbekannt</option><option value="yes">Ja</option><option value="no">Nein</option></select></label><label><span>Nächste Aktion am</span><input name="next_action_at" type="datetime-local" defaultValue={lead.next_action_at?new Date(lead.next_action_at).toISOString().slice(0,16):""}/></label>
      <label className={styles.full}><span>Nächste Aktion</span><input name="next_action" defaultValue={lead.next_action||""}/></label><label className={styles.full}><span>Zusammenfassung / Opportunity</span><textarea name="summary" rows={4} defaultValue={lead.summary||""}/></label><label className={styles.full}><span>Sales Angle / Pitch</span><textarea name="pitch" rows={4} defaultValue={lead.pitch||""}/></label>
      <label className={`${styles.full} ${styles.check}`}><input name="do_not_contact" type="checkbox" defaultChecked={lead.do_not_contact}/><span>Nicht kontaktieren / DNC</span></label>
    </div></form>
    <section className={styles.card}><div className={styles.cardHead}><div><span>Kommunikation</span><h2>Nachrichten</h2></div></div><div className={styles.list}>{messages.length?messages.map(m=><div className={styles.row} key={m.id}><div className={`${styles.dot} ${m.direction==="inbound"?styles.inbound:""}`}/><div><strong>{m.subject||m.status}</strong><p>{m.direction==="inbound"?`Von ${m.from_email||"Kontakt"}`:`An ${m.to_email||"Kontakt"}`} · {m.status}</p></div><time>{fmt(m.replied_at||m.sent_at||m.created_at)}</time></div>):<div className={styles.empty}>Noch keine Nachrichten.</div>}</div></section>
    <section className={styles.card}><div className={styles.cardHead}><div><span>Historie</span><h2>Aktivitäten & Notizen</h2></div></div><form className={styles.note} onSubmit={createNote}><textarea name="note" placeholder="Notiz zum Lead hinzufügen …" required/><button disabled={busy}>Notiz speichern</button></form><div className={styles.timeline}>{activities.length?activities.map(a=><div key={a.id}><i/><section><strong>{a.title}</strong>{a.detail?<p>{a.detail}</p>:null}<small>{fmt(a.created_at)}</small></section></div>):<div className={styles.empty}>Noch keine Aktivität.</div>}</div></section></main>
    <aside className={styles.side}><section className={styles.card}><div className={styles.cardHead}><div><span>Nächste Schritte</span><h2>Follow-ups</h2></div></div><form className={styles.followForm} onSubmit={createFollowup}><input name="title" required placeholder="z. B. Nachfassen nach Video"/><input name="due_at" required type="datetime-local"/><select name="priority" defaultValue="normal"><option value="low">Niedrig</option><option value="normal">Normal</option><option value="high">Hoch</option><option value="hot">Hot</option></select><textarea name="reason" placeholder="Grund / Kontext"/><button className={styles.primary} disabled={busy}>Follow-up anlegen</button></form><div className={styles.followList}>{followups.length?followups.map(f=><div className={styles.follow} key={f.id}><div><span className={styles.badge}>{f.priority}</span><strong>{f.title}</strong><small>{fmt(f.due_at)} · {f.status}</small>{f.reason?<p>{f.reason}</p>:null}</div>{f.status==="open"?<button onClick={()=>void finishFollowup(f.id)}>✓</button>:null}</div>):<div className={styles.empty}>Keine Follow-ups.</div>}</div></section>
    <section className={styles.card}><div className={styles.cardHead}><div><span>Outbound</span><h2>Video & Landingpage</h2></div></div>{video?<div className={styles.video}><div>▶</div><strong>{video.headline||lead.company_name}</strong><p>Status: {video.status} · {video.is_public?"öffentlich":"privat"}</p><div className={styles.actions}><button onClick={openStudio}>Im Studio bearbeiten</button><a target="_blank" href={`/v/${video.slug}`}>Vorschau ↗</a></div></div>:<div className={styles.empty}>Noch keine personalisierte Video-Seite. <button onClick={openStudio}>Im Studio erstellen →</button></div>}</section>
    <section className={styles.card}><div className={styles.cardHead}><div><span>Kontakt</span><h2>Schnellaktionen</h2></div></div><div className={styles.quick}>{lead.phone?<a href={`tel:${lead.phone}`}>☎ {lead.phone}</a>:null}{lead.email?<a href={`mailto:${lead.email}`}>✉ {lead.email}</a>:null}<button onClick={()=>{navigator.clipboard?.writeText(`${lead.company_name}\n${lead.contact_name||""}\n${lead.email||""}\n${lead.phone||""}`);setNotice("Kontaktdaten kopiert.")}}>Kontaktdaten kopieren</button></div></section></aside></div>
  </div>
}
