"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

type Mailbox={id:string;email_address:string;from_name:string|null;status:string;daily_limit:number;sent_today:number;smtp_host:string|null;smtp_port:number|null;smtp_secure:boolean;imap_host:string|null;imap_port:number|null;imap_secure:boolean;last_tested_at:string|null;last_sync_at:string|null;last_error:string|null};
type Preset="custom"|"ionos"|"strato"|"gmail"|"microsoft";
const PRESETS:Record<Preset,{label:string;smtp:string;smtpPort:number;smtpSecure:boolean;imap:string;imapPort:number}>={
 custom:{label:"Eigener Provider",smtp:"",smtpPort:587,smtpSecure:false,imap:"",imapPort:993},
 ionos:{label:"IONOS",smtp:"smtp.ionos.de",smtpPort:587,smtpSecure:false,imap:"imap.ionos.de",imapPort:993},
 strato:{label:"STRATO",smtp:"smtp.strato.de",smtpPort:465,smtpSecure:true,imap:"imap.strato.de",imapPort:993},
 gmail:{label:"Google Workspace / Gmail",smtp:"smtp.gmail.com",smtpPort:587,smtpSecure:false,imap:"imap.gmail.com",imapPort:993},
 microsoft:{label:"Microsoft 365 / Outlook",smtp:"smtp.office365.com",smtpPort:587,smtpSecure:false,imap:"outlook.office365.com",imapPort:993},
};
function fmt(v:string|null){if(!v)return"—";try{return new Intl.DateTimeFormat("de-DE",{dateStyle:"short",timeStyle:"short"}).format(new Date(v))}catch{return"—"}}

export function MailboxManager({user}:{user:User}){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const[rows,setRows]=useState<Mailbox[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const[preset,setPreset]=useState<Preset>("custom");
 const load=useCallback(async()=>{if(!supabase)return;const{data,error}=await supabase.from("energy_mailboxes").select("id,email_address,from_name,status,daily_limit,sent_today,smtp_host,smtp_port,smtp_secure,imap_host,imap_port,imap_secure,last_tested_at,last_sync_at,last_error").eq("user_id",user.id).order("created_at");if(error)setError(error.message);else setRows((data||[]) as Mailbox[])},[supabase,user.id]);
 useEffect(()=>{void load()},[load]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setError(null);setMessage(null);try{const f=new FormData(e.currentTarget);const p=PRESETS[preset];const body={action:"save",emailAddress:f.get("email"),fromName:f.get("fromName"),dailyLimit:f.get("dailyLimit"),provider:preset,smtpHost:String(f.get("smtpHost")||p.smtp),smtpPort:Number(f.get("smtpPort")||p.smtpPort),smtpSecure:f.get("smtpSecure")==="on",smtpUsername:f.get("smtpUsername")||f.get("email"),smtpPassword:f.get("smtpPassword"),imapHost:String(f.get("imapHost")||p.imap),imapPort:Number(f.get("imapPort")||p.imapPort),imapSecure:true,imapUsername:f.get("imapUsername")||f.get("email"),imapPassword:f.get("imapPassword")||f.get("smtpPassword")};const{data,error}=await supabase.functions.invoke("mailbox-admin",{body});if(error||data?.error)throw new Error(data?.error||error?.message||"Mailbox konnte nicht gespeichert werden");setMessage(`${String(f.get("email"))} gespeichert. Jetzt Verbindung testen.`);e.currentTarget.reset();setPreset("custom");await load()}catch(x){setError(x instanceof Error?x.message:"Mailbox konnte nicht gespeichert werden")}finally{setBusy(false)}}
 async function action(id:string,kind:"test"|"sync"){if(!supabase)return;setBusy(true);setError(null);setMessage(null);try{const{data,error}=await supabase.functions.invoke("mailbox-admin",{body:{action:kind,id}});if(error||data?.error)throw new Error(data?.error||error?.message||`${kind} fehlgeschlagen`);setMessage(kind==="test"?(data.message||"SMTP-Verbindung erfolgreich"):`${data.synced||0} Antworten synchronisiert.`);await load()}catch(x){setError(x instanceof Error?x.message:"Mailbox-Aktion fehlgeschlagen")}finally{setBusy(false)}}
 async function pause(id:string,status:string){if(!supabase)return;setBusy(true);setError(null);try{const next=status==="paused"?"setup":"paused";const r=await supabase.from("energy_mailboxes").update({status:next,updated_at:new Date().toISOString()}).eq("id",id).eq("user_id",user.id);if(r.error)throw r.error;setMessage(next==="paused"?"Mailbox pausiert.":"Mailbox reaktiviert – bitte erneut testen.");await load()}catch(x){setError(x instanceof Error?x.message:"Status konnte nicht geändert werden")}finally{setBusy(false)}}
 const ready=rows.filter(r=>r.status==="ready").length;const p=PRESETS[preset];const defaultName=String(user.user_metadata?.full_name||user.user_metadata?.name||"Andreas Walkenhorst");
 return <section className="os-card os-section" style={{maxWidth:1480,margin:"0 auto 18px"}}>
  <div className="os-section-head"><div><div className="os-kicker">Sending Engine</div><h2>Versand-Mailboxen</h2><p>Hier hinterlegst du die 5 Absenderkonten. Erst erfolgreich getestete Mailboxen werden von Kampagnen verwendet.</p></div><div className="os-toolbar"><span className={`os-pill ${ready?"green":""}`}>{ready}/{rows.length||5} ready</span><span className="os-pill">Ziel: 5 Konten</span></div></div>
  {error?<div className="os-error">{error}</div>:null}{message?<div className="os-success">{message}</div>:null}
  <div className="os-columns" style={{alignItems:"start"}}>
   <form className="os-form" onSubmit={save}>
    <div className="os-formgrid"><div className="os-field"><label>E-Mail-Provider</label><select value={preset} onChange={e=>setPreset(e.target.value as Preset)}>{Object.entries(PRESETS).map(([id,x])=><option value={id} key={id}>{x.label}</option>)}</select></div><div className="os-field"><label>Absender E-Mail *</label><input name="email" type="email" required placeholder="andreas@deinedomain.de"/></div><div className="os-field"><label>Absendername</label><input name="fromName" defaultValue={defaultName}/></div><div className="os-field"><label>Tageslimit</label><input name="dailyLimit" type="number" min="1" max="50" defaultValue="30"/></div></div>
    <div className="os-kicker" style={{marginTop:8}}>SMTP · Versand</div><div className="os-formgrid"><div className="os-field"><label>SMTP Host *</label><input name="smtpHost" required={preset==="custom"} key={`smtp-${preset}`} defaultValue={p.smtp}/></div><div className="os-field"><label>Port</label><input name="smtpPort" type="number" key={`smtpport-${preset}`} defaultValue={p.smtpPort}/></div><div className="os-field"><label>SMTP Benutzer</label><input name="smtpUsername" placeholder="meist identisch mit E-Mail"/></div><div className="os-field"><label>SMTP Passwort / App-Passwort *</label><input name="smtpPassword" type="password" required/></div><div className="os-field"><label><input name="smtpSecure" type="checkbox" key={`secure-${preset}`} defaultChecked={p.smtpSecure}/> SSL/TLS direkt</label></div></div>
    <div className="os-kicker" style={{marginTop:8}}>IMAP · Antworten erkennen</div><div className="os-formgrid"><div className="os-field"><label>IMAP Host</label><input name="imapHost" key={`imap-${preset}`} defaultValue={p.imap}/></div><div className="os-field"><label>Port</label><input name="imapPort" type="number" key={`imapport-${preset}`} defaultValue={p.imapPort}/></div><div className="os-field"><label>IMAP Benutzer</label><input name="imapUsername" placeholder="meist identisch mit E-Mail"/></div><div className="os-field"><label>IMAP Passwort</label><input name="imapPassword" type="password" placeholder="leer = SMTP-Passwort verwenden"/></div></div>
    <div className="os-callout"><strong>Sicher:</strong> Passwörter werden serverseitig im Supabase Vault gespeichert und nicht wieder im Browser angezeigt.</div><button className="os-btn primary" disabled={busy||rows.length>=5}>{busy?"Speichert …":rows.length>=5?"5 Mailboxen bereits angelegt":"Mailbox hinzufügen"}</button>
   </form>
   <div><div className="os-kicker">Verbundene Konten</div>{rows.length?rows.map((m,i)=><div className="os-checkrow" key={m.id} style={{marginTop:8}}><span className={`os-pill ${m.status==="ready"?"green":m.status==="error"?"hot":""}`}>{i+1} · {m.status}</span><div style={{minWidth:0}}><strong>{m.email_address}</strong><small>{m.from_name||"—"} · {m.sent_today||0}/{m.daily_limit}/Tag<br/>{m.smtp_host||"SMTP fehlt"} · Test {fmt(m.last_tested_at)}{m.last_error?<><br/><span style={{color:"#d55"}}>{m.last_error}</span></>:null}</small></div><div className="os-toolbar"><button type="button" className="os-btn small" disabled={busy||m.status==="paused"} onClick={()=>void action(m.id,"test")}>Test</button><button type="button" className="os-btn small" disabled={busy||!m.imap_host||m.status==="paused"} onClick={()=>void action(m.id,"sync")}>Inbox Sync</button><button type="button" className="os-btn small" disabled={busy} onClick={()=>void pause(m.id,m.status)}>{m.status==="paused"?"Aktivieren":"Pausieren"}</button></div></div>):<div className="os-empty" style={{marginTop:8}}>Noch keine Mailbox. Links das erste Konto eintragen.</div>}</div>
  </div>
 </section>
}
