"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

type Opportunity={lead_id:string;company_name:string;contact_name:string|null;phone:string|null;email:string|null;city:string|null;status:string;total_score:number;intent_score:number;pv_score:number;site_status:string|null;estimated_capacity_kwp:number|null;estimated_annual_generation_kwh:number|null;pv_yield_kwh_per_kwp:number|null;open_hot_alerts:number;due_hot_followups:number;priority_index:number;priority_reason:string|null;next_action:string|null};
function num(v:number|null|undefined,digits=0){return v==null?"—":new Intl.NumberFormat("de-DE",{maximumFractionDigits:digits}).format(v)}

export function OpportunityCenter({user}:{user:User}){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const[rows,setRows]=useState<Opportunity[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[filter,setFilter]=useState<"all"|"hot"|"pv"|"unanalyzed">("all");
 const load=useCallback(async()=>{if(!supabase)return;setBusy(true);setError(null);try{const{data,error:e}=await supabase.rpc("energy_sales_priority_v2",{p_limit:1000});if(e)throw e;setRows((data||[]) as Opportunity[])}catch(x){setError(x instanceof Error?x.message:"Priorisierung konnte nicht geladen werden")}finally{setBusy(false)}},[supabase]);useEffect(()=>{void load()},[load]);
 const visible=rows.filter(r=>filter==="all"||filter==="hot"&&(r.open_hot_alerts>0||r.due_hot_followups>0||r.intent_score>=70)||filter==="pv"&&Number(r.estimated_capacity_kwp||0)>=100||filter==="unanalyzed"&&!r.site_status);
 const hot=rows.filter(r=>r.open_hot_alerts>0||r.due_hot_followups>0).length;const pv100=rows.filter(r=>Number(r.estimated_capacity_kwp||0)>=100).length;const unanalyzed=rows.filter(r=>!r.site_status).length;const callable=rows.filter(r=>r.phone).length;
 return <main className="os-root" style={{minHeight:"100vh"}}><div className="os-content" style={{maxWidth:1450,margin:"0 auto",paddingTop:28}}>
  <div className="os-section-head"><div><div className="os-kicker">Sales Priority V2</div><h1 className="os-title">Welche Firma zuerst?</h1><p>Live-Priorisierung aus CRM-Score, Intent, PV-Site-Evidence, Alerts und fälligen Follow-ups.</p></div><div className="os-toolbar"><a className="os-btn" href="/command">← Heute</a><a className="os-btn" href="/pv-intelligence">PV Intelligence</a><a className="os-btn" href="/alerts">Alerts</a><button className="os-btn" disabled={busy} onClick={()=>void load()}>↻ Neu ranken</button></div></div>{error?<div className="os-error">{error}</div>:null}
  <div className="os-grid os-kpis" style={{marginTop:18}}>{[[rows.length,"Kontaktierbare Chancen","ohne Won/Lost/DNC"],[hot,"SLA / Hot","Alert oder fällig"],[pv100,"PV ≥100 kWp","Flächenmodell vorhanden"],[unanalyzed,"PV noch offen","Standortanalyse fehlt"],[callable,"Telefonisch erreichbar","gültiger Kanal"]].map(([v,l,s])=><div className="os-card os-kpi" key={String(l)}><div className="os-kpi-label">{l}</div><div className="os-kpi-value">{v}</div><div className="os-kpi-sub">{s}</div></div>)}</div>
  <section className="os-card os-section" style={{marginTop:18}}><div className="os-section-head"><div><div className="os-kicker">Ranking</div><h2>Sales Priority Index</h2></div><div className="os-toolbar">{([['all','Alle'],['hot','Hot'],['pv','PV ≥100 kWp'],['unanalyzed','PV offen']] as const).map(([id,label])=><button key={id} className={`os-btn small ${filter===id?'primary':''}`} onClick={()=>setFilter(id)}>{label}</button>)}</div></div>
   <div className="os-tablewrap"><table className="os-table"><thead><tr><th>#</th><th>Unternehmen</th><th>Priority</th><th>CRM</th><th>Intent</th><th>PV Evidence</th><th>Warum jetzt?</th><th>Next Action</th><th></th></tr></thead><tbody>{visible.length?visible.map((r,i)=><tr key={r.lead_id}><td><strong>{i+1}</strong></td><td><strong>{r.company_name}</strong><small style={{display:"block"}}>{[r.contact_name,r.city,r.status].filter(Boolean).join(" · ")}</small></td><td><div className="os-score" style={{width:58}}>{r.priority_index}</div></td><td><strong>{r.total_score}</strong><small style={{display:"block"}}>PV {r.pv_score}</small></td><td><span className={`os-pill ${r.intent_score>=70?"hot":""}`}>{r.intent_score}</span></td><td>{r.estimated_capacity_kwp!=null?<><strong>{num(r.estimated_capacity_kwp,1)} kWp</strong><small style={{display:"block"}}>{num(r.estimated_annual_generation_kwh)} kWh/a</small></>:r.site_status?<span className="os-pill">Benchmark</span>:<a className="os-btn small" href="/pv-intelligence">analysieren</a>}</td><td><strong>{r.priority_reason||"Basis-Score"}</strong>{r.open_hot_alerts||r.due_hot_followups?<small style={{display:"block",color:"#b54a0f"}}>{r.open_hot_alerts} Alerts · {r.due_hot_followups} fällige Hot-Follow-ups</small>:null}</td><td><small>{r.next_action||"Kontakt aufnehmen"}</small></td><td><div className="os-toolbar">{r.phone?<a className="os-btn small primary" href={`tel:${r.phone}`}>📞</a>:null}{r.email?<a className="os-btn small" href={`mailto:${r.email}`}>✉</a>:null}</div></td></tr>):<tr><td colSpan={9}><div className="os-empty">Keine Chancen im gewählten Filter.</div></td></tr>}</tbody></table></div>
  </section>
  <div className="os-callout" style={{marginTop:16}}><strong>Wichtig:</strong> Der Priority Index ist kein Abschlusswahrscheinlichkeits-Prozentwert. Er dient nur der Reihenfolge im Vertrieb. PV-Boni entstehen ausschließlich aus bereits gespeicherten Standort-/Flächendaten.</div>
  <div className="os-source" style={{marginTop:10}}>Nutzer: {user.email}</div>
 </div></main>;
}
