"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

type Lead={id:string;company_name:string;contact_name:string|null;email:string|null;status:string;intent_score:number};
type Deal={id:string;lead_id:string;title:string;stage:string;value_eur:number|null};
type Doc={id:string;lead_id:string;deal_id:string|null;title:string;provider:string;share_url:string|null;status:string;tracking_token:string;view_count:number;total_view_seconds:number;first_viewed_at:string|null;last_viewed_at:string|null;created_at:string};
const dt=(v:string|null)=>v?new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"—";

export function ProposalCenter({user}:{user:User}){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const[leads,setLeads]=useState<Lead[]>([]);const[deals,setDeals]=useState<Deal[]>([]);const[docs,setDocs]=useState<Doc[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const[origin,setOrigin]=useState("");
 useEffect(()=>{setOrigin(window.location.origin)},[]);
 const load=useCallback(async()=>{if(!supabase)return;const[l,d,docs]=await Promise.all([supabase.from("energy_leads").select("id,company_name,contact_name,email,status,intent_score").eq("user_id",user.id).order("updated_at",{ascending:false}).limit(3000),supabase.from("energy_deals").select("id,lead_id,title,stage,value_eur").eq("user_id",user.id).order("updated_at",{ascending:false}),supabase.from("energy_documents").select("id,lead_id,deal_id,title,provider,share_url,status,tracking_token,view_count,total_view_seconds,first_viewed_at,last_viewed_at,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(1000)]);if(l.error){setError(l.error.message);return}setLeads((l.data||[]) as Lead[]);setDeals((d.data||[]) as Deal[]);setDocs((docs.data||[]) as Doc[])},[supabase,user.id]);useEffect(()=>{void load()},[load]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setError(null);try{const f=new FormData(e.currentTarget);const leadId=String(f.get("leadId")||"");const deal=deals.find(d=>d.lead_id===leadId);const{error}=await supabase.from("energy_documents").insert({user_id:user.id,lead_id:leadId,deal_id:deal?.id||null,title:String(f.get("title")||"Angebot"),provider:"native",share_url:String(f.get("url")||""),status:"sent"});if(error)throw error;setMessage("Tracking-Link erstellt.");e.currentTarget.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Link konnte nicht erstellt werden")}finally{setBusy(false)}}
 async function copy(doc:Doc){const link=`${origin}/offer/${doc.tracking_token}`;await navigator.clipboard.writeText(link);setMessage("Tracking-Link kopiert.")}
 async function archive(id:string){if(!supabase)return;await supabase.from("energy_documents").update({status:"archived",updated_at:new Date().toISOString()}).eq("id",id).eq("user_id",user.id);await load()}
 return <div className="os-root" style={{minHeight:"100vh"}}><main className="os-main" style={{marginLeft:0}}><header className="os-topbar"><div><div className="os-kicker">Proposal Intelligence</div><h1 className="os-title">Angebot-Tracking</h1></div><div className="os-actions"><a className="os-btn" href="/dashboard">← Sales OS</a><a className="os-btn" href="/pipeline">Pipeline</a></div></header><div className="os-content">{error?<div className="os-error">{error}</div>:null}{message?<div className="os-success">{message}</div>:null}<div className="os-columns"><section className="os-card os-section"><div className="os-section-head"><div><div className="os-kicker">Neuer Tracking-Link</div><h2>Angebot / PDF / Freigabelink</h2></div></div><form className="os-form" onSubmit={create}><div className="os-field"><label>Lead *</label><select name="leadId" required defaultValue=""><option value="" disabled>Lead auswählen</option>{leads.map(l=><option value={l.id} key={l.id}>{l.company_name} · Intent {l.intent_score}</option>)}</select></div><div className="os-field"><label>Titel *</label><input name="title" required placeholder="Angebot Müller Logistik · PV 2026"/></div><div className="os-field"><label>Ziel-URL *</label><input name="url" type="url" required placeholder="https://drive.google.com/... oder Papermark-Link"/></div><div className="os-callout"><strong>So funktioniert es:</strong><p style={{fontSize:9,margin:"5px 0 0"}}>Der Kunde erhält nicht die Ziel-URL, sondern den gebrandeten Walkenhorst-Link. Öffnung 1/2/3 wird dem Lead zugeordnet; bekannte Scanner werden nicht als echtes Kaufsignal gezählt.</p></div><button className="os-btn primary" disabled={busy}>Tracking-Link erzeugen</button></form></section><section className="os-card os-section"><div className="os-section-head"><div><div className="os-kicker">Live Tracking</div><h2>{docs.filter(d=>d.status!=="archived").length} Dokumente</h2></div></div>{docs.filter(d=>d.status!=="archived").length?docs.filter(d=>d.status!=="archived").map(d=>{const lead=leads.find(l=>l.id===d.lead_id);const hot=d.view_count>=3;const tracked=origin?`${origin}/offer/${d.tracking_token}`:`/offer/${d.tracking_token}`;return <div className="os-checkrow" key={d.id}><span className={`os-pill ${hot?"hot":d.view_count?"green":""}`}>{d.view_count} Views</span><div style={{minWidth:0}}><strong>{d.title}</strong><small>{lead?.company_name||"Lead"} · zuletzt {dt(d.last_viewed_at)} · {tracked}</small></div><div className="os-toolbar"><button className="os-btn small" onClick={()=>void copy(d)}>Kopieren</button><a className="os-btn small" href={tracked} target="_blank">Test ↗</a><button className="os-btn small" onClick={()=>void archive(d.id)}>Archiv</button></div></div>}):<div className="os-empty">Noch kein Angebot getrackt.</div>}</section></div></div></main></div>
}
