"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

type Candidate={lead_id:string;company_name:string;contact_name:string|null;phone:string|null;email:string|null;status:string;total_score:number;intent_score:number;last_contact_at:string|null;days_inactive:number;reason:string;suggested_action:string;priority:number};
function fmt(v:string|null|undefined){if(!v)return"—";try{return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",year:"2-digit"}).format(new Date(v))}catch{return"—"}}

export function RevivalCenter({user}:{user:User}){
  const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
  const [rows,setRows]=useState<Candidate[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);
  const load=useCallback(async()=>{if(!supabase)return;setBusy(true);setError(null);try{const{data,error:e}=await supabase.rpc("energy_revival_candidates",{p_limit:500});if(e)throw e;setRows((data||[]) as Candidate[])}catch(x){setError(x instanceof Error?x.message:"Revival-Kandidaten konnten nicht geladen werden")}finally{setBusy(false)}},[supabase]);
  useEffect(()=>{void load()},[load]);
  const hot=useMemo(()=>rows.filter(r=>r.intent_score>=70||r.priority>=450).length,[rows]);const avgDays=rows.length?Math.round(rows.reduce((s,r)=>s+r.days_inactive,0)/rows.length):0;const timing=rows.filter(r=>/Timing|Rückmeldung/i.test(r.reason)).length;
  async function revive(row:Candidate,days=0){if(!supabase)return;setBusy(true);setError(null);setNotice(null);try{const due=new Date(Date.now()+days*86400000).toISOString();const{data,error:e}=await supabase.rpc("energy_revive_lead",{p_lead_id:row.lead_id,p_due_at:due,p_note:`Revival: ${row.reason}`});if(e)throw e;setNotice(`${row.company_name}: Wiedervorlage ${days?`in ${days} Tagen`:"für jetzt"} erstellt.`);await load();return data}catch(x){setError(x instanceof Error?x.message:"Revival wurde abgebrochen")}finally{setBusy(false)}}
  return <main className="os-root" style={{minHeight:"100vh"}}><div className="os-content" style={{maxWidth:1400,margin:"0 auto",paddingTop:28}}>
    <div className="os-section-head"><div><div className="os-kicker">Pipeline Recovery</div><h1 className="os-title">Revival Center</h1><p>Gute Chancen wieder hochholen, bevor sie im CRM vergessen werden.</p></div><div className="os-toolbar"><a className="os-btn" href="/command">← Heute</a><a className="os-btn" href="/calls">Caller Queue</a><button className="os-btn" disabled={busy} onClick={()=>void load()}>↻ Aktualisieren</button></div></div>
    {error?<div className="os-error">{error}</div>:null}{notice?<div className="os-success">{notice}</div>:null}
    <div className="os-grid os-kpis" style={{marginTop:18}}>{[[rows.length,"Revival Chancen","ohne offene Wiedervorlage"],[hot,"High Priority","Intent / Score"],[avgDays,"Ø Tage inaktiv","seit letztem Kontakt"],[timing,"Timing-Revisits","alte Lost-Chancen"],[0,"Auto-Sends","bewusst deaktiviert"]].map(([v,l,s])=><div className="os-card os-kpi" key={String(l)}><div className="os-kpi-label">{l}</div><div className="os-kpi-value">{v}</div><div className="os-kpi-sub">{s}</div></div>)}</div>
    <section className="os-card os-section" style={{marginTop:18}}><div className="os-section-head"><div><div className="os-kicker">Priorisiert</div><h2>Wieder anfassbare Chancen</h2></div><span className="os-pill hot">{rows.length}</span></div><div className="os-tablewrap"><table className="os-table"><thead><tr><th>Unternehmen</th><th>Score</th><th>Intent</th><th>Inaktiv</th><th>Warum jetzt?</th><th>Kanal</th><th>Aktion</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.lead_id}><td><strong>{r.company_name}</strong><small style={{display:"block"}}>{r.contact_name||r.status} · letzter Kontakt {fmt(r.last_contact_at)}</small></td><td><div className="os-score">{r.total_score}</div></td><td><span className={`os-pill ${r.intent_score>=70?"hot":""}`}>{r.intent_score}</span></td><td><strong>{r.days_inactive} Tage</strong></td><td><strong>{r.reason}</strong><small style={{display:"block"}}>{r.suggested_action}</small></td><td>{r.phone?<span className="os-pill green">Telefon</span>:r.email?<span className="os-pill">E-Mail</span>:"—"}</td><td><div className="os-toolbar"><button className="os-btn small primary" disabled={busy} onClick={()=>void revive(r,0)}>Heute reaktivieren</button><button className="os-btn small" disabled={busy} onClick={()=>void revive(r,30)}>+30 Tage</button></div></td></tr>):<tr><td colSpan={7}><div className="os-empty">Keine geeigneten Stale Leads. Das ist ein gutes Zeichen.</div></td></tr>}</tbody></table></div></section>
    <div className="os-callout" style={{marginTop:16}}><strong>Schutzlogik:</strong> Do-not-contact, fehlende gültige Kontaktkanäle, laufende Sequenzen, offene Follow-ups sowie aktive Termin-/Angebots-/Won-Deals werden aus der Revival Queue ausgeschlossen.</div>
    <div className="os-source" style={{marginTop:10}}>Nutzer: {user.email}</div>
  </div></main>;
}
