"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

type Lead={id:string;company_name:string;contact_name:string|null;phone:string|null;email:string|null;city:string|null;status:string;total_score:number;intent_score:number;pv_score:number};
type Brief={lead_id:string;company_name:string;contact_name:string|null;phone:string|null;email:string|null;status:string;opener:string;next_best_action:string;questions:string[];evidence:Record<string,unknown>;latest_call:null|{sentiment:string|null;summary:string|null;topics:string[]|null;recording_url:string|null;ended_at:string|null};site:null|{yield_kwh_per_kwp:number|null;capacity_kwp:number|null;annual_generation_kwh:number|null;roof_area_m2:number|null;analyzed_at:string|null};deal:null|{stage:string|null;value_eur:number|null;probability:number|null;expected_close_date:string|null};disclaimer:string};
function val(v:unknown){if(v===null||v===undefined||v==="")return"—";if(typeof v==="number")return new Intl.NumberFormat("de-DE",{maximumFractionDigits:1}).format(v);return String(v)}

export function SalesBriefCenter({user}:{user:User}){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const[leads,setLeads]=useState<Lead[]>([]);const[selectedId,setSelectedId]=useState("");const[brief,setBrief]=useState<Brief|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);
 const loadLeads=useCallback(async()=>{if(!supabase)return;const{data,error:e}=await supabase.from("energy_leads").select("id,company_name,contact_name,phone,email,city,status,total_score,intent_score,pv_score").eq("user_id",user.id).not("status","in",'(won,lost)').order("intent_score",{ascending:false}).limit(3000);if(e){setError(e.message);return}setLeads((data||[]) as Lead[]);if(!selectedId&&data?.length)setSelectedId(String(data[0].id))},[supabase,user.id,selectedId]);useEffect(()=>{void loadLeads()},[loadLeads]);
 const selected=leads.find(l=>l.id===selectedId)||null;
 const build=useCallback(async(id:string)=>{if(!supabase||!id)return;setBusy(true);setError(null);setNotice(null);try{const{data,error:e}=await supabase.rpc("energy_sales_brief",{p_lead_id:id});if(e)throw e;setBrief(data as Brief)}catch(x){setError(x instanceof Error?x.message:"Sales Brief konnte nicht erstellt werden")}finally{setBusy(false)}},[supabase]);useEffect(()=>{if(selectedId)void build(selectedId)},[selectedId,build]);
 async function copy(text:string,label:string){try{await navigator.clipboard.writeText(text);setNotice(`${label} kopiert.`)}catch{setError("Kopieren wurde vom Browser blockiert.")}}
 const evidence=brief?Object.entries(brief.evidence||{}):[];
 return <main className="os-root" style={{minHeight:"100vh"}}><div className="os-content" style={{maxWidth:1400,margin:"0 auto",paddingTop:28}}>
  <div className="os-section-head"><div><div className="os-kicker">Evidence-Based Sales Brain</div><h1 className="os-title">Sales Brief</h1><p>Was wissen wir wirklich – und was soll der Verkäufer als Nächstes sagen?</p></div><div className="os-toolbar"><a className="os-btn" href="/opportunities">← Opportunities</a><a className="os-btn" href="/pv-intelligence">PV Intelligence</a><button className="os-btn" disabled={busy||!selectedId} onClick={()=>void build(selectedId)}>↻ Brief neu bauen</button></div></div>{error?<div className="os-error">{error}</div>:null}{notice?<div className="os-success">{notice}</div>:null}
  <div className="os-columns" style={{gridTemplateColumns:"minmax(320px,.55fr) minmax(0,1.45fr)",marginTop:18}}><section className="os-card os-section"><div className="os-kicker">Lead</div><h2>Verkaufsgespräch vorbereiten</h2><div className="os-field"><label>Unternehmen</label><select value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">Lead wählen</option>{leads.map(l=><option key={l.id} value={l.id}>{l.company_name} · Intent {l.intent_score}</option>)}</select></div>{selected?<div className="os-detail" style={{marginTop:12}}><div className="os-detail-row"><span>Status</span><strong>{selected.status}</strong></div><div className="os-detail-row"><span>Score / Intent</span><strong>{selected.total_score} / {selected.intent_score}</strong></div><div className="os-detail-row"><span>PV Score</span><strong>{selected.pv_score}</strong></div><div className="os-detail-row"><span>Kontakt</span><strong>{selected.contact_name||selected.phone||selected.email||"—"}</strong></div></div>:null}</section>
   <section className="os-grid" style={{gap:12}}>{brief?<><article className="os-card os-section"><div className="os-section-head"><div><div className="os-kicker">Call Opener</div><h2>{brief.company_name}</h2></div><button className="os-btn small" onClick={()=>void copy(brief.opener,"Opener")}>Kopieren</button></div><div className="os-script" style={{fontSize:12,lineHeight:1.7}}>{brief.opener}</div><div className="os-callout" style={{marginTop:12}}><strong>Next Best Action</strong><p style={{margin:"6px 0 0"}}>{brief.next_best_action}</p></div><div className="os-toolbar" style={{marginTop:12}}>{brief.phone?<a className="os-btn primary" href={`tel:${brief.phone}`}>📞 Jetzt anrufen</a>:null}{brief.email?<a className="os-btn" href={`mailto:${brief.email}`}>✉ E-Mail</a>:null}</div></article>
   <div className="os-columns"><article className="os-card os-section"><div className="os-kicker">Qualifizierung</div><h2>6 Fragen, die Zahlen aus Annahmen machen</h2><ol style={{paddingLeft:20,margin:0}}>{brief.questions.map((q,i)=><li key={i} style={{margin:"0 0 10px",fontSize:11,lineHeight:1.5}}>{q}</li>)}</ol></article><article className="os-card os-section"><div className="os-kicker">Evidence</div><h2>Gespeicherte Fakten & Signale</h2>{evidence.map(([k,v])=><div className="os-detail-row" key={k}><span>{k.replaceAll("_"," ")}</span><strong style={{maxWidth:260,textAlign:"right"}}>{val(v)}</strong></div>)}</article></div>
   {brief.latest_call?<article className="os-card os-section"><div className="os-section-head"><div><div className="os-kicker">Letzter Rinkel Call</div><h2>{brief.latest_call.sentiment||"Call"}</h2></div>{brief.latest_call.recording_url?<a className="os-btn small" target="_blank" rel="noreferrer" href={brief.latest_call.recording_url}>Recording ↗</a>:null}</div><p style={{fontSize:11,lineHeight:1.6}}>{brief.latest_call.summary||"Keine AI-Zusammenfassung verfügbar."}</p>{brief.latest_call.topics?.length?<div className="os-toolbar">{brief.latest_call.topics.map(t=><span className="os-pill" key={t}>{t}</span>)}</div>:null}</article>:null}
   <div className="os-error" style={{background:"#fff8ed",borderColor:"#f6d7a8",color:"#795018"}}>{brief.disclaimer}</div></>:<div className="os-card os-empty">Lead auswählen – der Brief wird automatisch aus vorhandener Evidenz gebaut.</div>}</section></div>
  <div className="os-source" style={{marginTop:10}}>Kein LLM erforderlich · Nutzer: {user.email}</div>
 </div></main>;
}
