"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

type Suppression={id:string;kind:string;raw_value:string;value_norm:string;reason:string;source:string;block_all:boolean;active:boolean;created_at:string;updated_at:string};
function fmt(v:string){try{return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",year:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}catch{return"—"}}

export function SuppressionCenter({user}:{user:User}){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const[rows,setRows]=useState<Suppression[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);const[showInactive,setShowInactive]=useState(false);
 const load=useCallback(async()=>{if(!supabase)return;setError(null);let q=supabase.from("energy_suppressions").select("id,kind,raw_value,value_norm,reason,source,block_all,active,created_at,updated_at").eq("user_id",user.id).order("updated_at",{ascending:false}).limit(5000);if(!showInactive)q=q.eq("active",true);const{data,error:e}=await q;if(e)setError(e.message);else setRows((data||[]) as Suppression[])},[supabase,user.id,showInactive]);useEffect(()=>{void load()},[load]);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setError(null);setNotice(null);try{const f=new FormData(e.currentTarget);const{data,error:e2}=await supabase.rpc("energy_add_suppression",{p_kind:String(f.get("kind")||"email"),p_value:String(f.get("value")||""),p_reason:String(f.get("reason")||"manual"),p_block_all:f.get("blockAll")==="on"});if(e2)throw e2;setNotice("Suppression gespeichert und auf bestehende Leads angewendet.");e.currentTarget.reset();await load();return data}catch(x){setError(x instanceof Error?x.message:"Suppression konnte nicht gespeichert werden")}finally{setBusy(false)}}
 async function disable(id:string){if(!supabase)return;if(!window.confirm("Suppression deaktivieren? Bestehende Lead-Status werden aus Sicherheitsgründen nicht automatisch wieder freigeschaltet."))return;setBusy(true);setError(null);try{const{error:e}=await supabase.rpc("energy_disable_suppression",{p_id:id});if(e)throw e;setNotice("Suppression deaktiviert. Bestehende Leads bleiben unverändert, bis sie bewusst neu validiert werden.");await load()}catch(x){setError(x instanceof Error?x.message:"Deaktivieren fehlgeschlagen")}finally{setBusy(false)}}
 const active=rows.filter(r=>r.active);const email=active.filter(r=>r.kind==="email").length;const phone=active.filter(r=>r.kind==="phone").length;const domain=active.filter(r=>r.kind==="domain").length;const global=active.filter(r=>r.block_all).length;
 return <main className="os-root" style={{minHeight:"100vh"}}><div className="os-content" style={{maxWidth:1400,margin:"0 auto",paddingTop:28}}>
  <div className="os-section-head"><div><div className="os-kicker">Compliance & Deliverability</div><h1 className="os-title">Suppression Center</h1><p>Abmeldungen, ungültige Adressen und manuelle Sperren bleiben auch über Re-Imports hinweg erhalten.</p></div><div className="os-toolbar"><a className="os-btn" href="/deliverability">← Deliverability</a><button className="os-btn" onClick={()=>setShowInactive(v=>!v)}>{showInactive?"Nur aktive":"Inaktive anzeigen"}</button><button className="os-btn" onClick={()=>void load()}>↻ Aktualisieren</button></div></div>{error?<div className="os-error">{error}</div>:null}{notice?<div className="os-success">{notice}</div>:null}
  <div className="os-grid os-kpis" style={{marginTop:18}}>{[[active.length,"Aktive Sperren","gesamt"],[email,"E-Mail","kanalspezifisch / DNC"],[phone,"Telefon","kanalspezifisch / DNC"],[domain,"Domains","manuelle Domain-Sperren"],[global,"Block All","alle Kanäle"]].map(([v,l,s])=><div className="os-card os-kpi" key={String(l)}><div className="os-kpi-label">{l}</div><div className="os-kpi-value">{v}</div><div className="os-kpi-sub">{s}</div></div>)}</div>
  <div className="os-columns" style={{marginTop:18}}><section className="os-card os-section"><div className="os-kicker">Manuell sperren</div><h2>Adresse, Nummer oder Domain</h2><form className="os-form" onSubmit={add}><div className="os-formgrid"><div className="os-field"><label>Typ</label><select name="kind" defaultValue="email"><option value="email">E-Mail</option><option value="phone">Telefon</option><option value="domain">Domain</option></select></div><div className="os-field"><label>Wert</label><input name="value" required placeholder="name@firma.de / +49... / firma.de"/></div></div><div className="os-field"><label>Grund</label><input name="reason" defaultValue="manual" placeholder="z. B. Kunde wünscht keinen Kontakt"/></div><label className="os-checkrow" style={{cursor:"pointer"}}><input type="checkbox" name="blockAll"/><div><strong>Alle Kanäle sperren</strong><small>Nur aktivieren, wenn wirklich keinerlei weiterer Kontakt erfolgen soll.</small></div></label><button className="os-btn primary" disabled={busy}>Suppression speichern</button></form></section><section className="os-card os-section"><div className="os-kicker">Schutzlogik</div><h2>Was automatisch passiert</h2><div className="os-detail-row"><span>Hard Bounce / invalid</span><strong>E-Mail blockiert</strong></div><div className="os-detail-row"><span>Falsche Nummer</span><strong>Telefon blockiert</strong></div><div className="os-detail-row"><span>Do-not-contact</span><strong>Alle Kanäle blockiert</strong></div><div className="os-detail-row"><span>Re-Import</span><strong>Sperre wird erneut angewendet</strong></div></section></div>
  <section className="os-card os-section" style={{marginTop:18}}><div className="os-section-head"><div><div className="os-kicker">Registry</div><h2>{rows.length} Einträge</h2></div></div><div className="os-tablewrap"><table className="os-table"><thead><tr><th>Typ</th><th>Wert</th><th>Grund</th><th>Quelle</th><th>Scope</th><th>Status</th><th>Aktualisiert</th><th></th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td><span className="os-pill">{r.kind}</span></td><td><strong>{r.raw_value}</strong><small style={{display:"block"}}>{r.value_norm}</small></td><td>{r.reason}</td><td>{r.source}</td><td><span className={`os-pill ${r.block_all?"hot":"green"}`}>{r.block_all?"alle Kanäle":"nur Kanal"}</span></td><td><span className={`os-pill ${r.active?"green":""}`}>{r.active?"aktiv":"inaktiv"}</span></td><td>{fmt(r.updated_at)}</td><td>{r.active?<button className="os-btn small" disabled={busy} onClick={()=>void disable(r.id)}>Deaktivieren</button>:null}</td></tr>):<tr><td colSpan={8}><div className="os-empty">Keine Suppressions.</div></td></tr>}</tbody></table></div></section>
  <div className="os-callout" style={{marginTop:16}}><strong>Wichtig:</strong> Eine deaktivierte Suppression hebt vorhandene `email_status`, `phone_status` oder `do_not_contact` Werte nicht automatisch auf. Freigaben müssen bewusst am Lead neu validiert werden.</div>
 </div></main>;
}
