"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";

type Row={user_id:string;video_page_id:string;lead_id:string;company_name:string;contact_name:string|null;email:string|null;slug:string;template_key:string|null;emails_sent:number;emails_opened:number;emails_clicked:number;email_sent_at:string|null;email_opened_at:string|null;email_clicked_at:string|null;email_replied_at:string|null;page_views:number;video_starts:number;max_watch_percent:number;max_playback_seconds:number;max_watch_seconds:number;cta_clicks:number;last_video_event_at:string|null};
const pct=(a:number,b:number)=>b>0?Math.round(a/b*100):0;
const dt=(value:string|null)=>value?new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"–";
const time=(seconds:number)=>{const s=Math.max(0,Math.round(seconds||0));return s<60?`${s}s`:`${Math.floor(s/60)}:${String(s%60).padStart(2,"0")} min`};

export function VideoFunnelAnalytics({user}:{user:User}){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
 const[rows,setRows]=useState<Row[]>([]);const[error,setError]=useState<string|null>(null);const[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);const{data,error}=await supabase.from("energy_video_funnel_v").select("*").eq("user_id",user.id).order("last_video_event_at",{ascending:false,nullsFirst:false}).limit(500);if(error){setError(error.message);setLoading(false);return}setRows((data||[]) as Row[]);setError(null);setLoading(false)},[supabase,user.id]);
 useEffect(()=>{void load()},[load]);
 const sent=rows.reduce((s,r)=>s+Number(r.emails_sent||0),0);const opened=rows.reduce((s,r)=>s+Number(r.emails_opened||0),0);const clicked=rows.reduce((s,r)=>s+Number(r.emails_clicked||0),0);const viewed=rows.filter(r=>r.page_views>0).length;const started=rows.filter(r=>r.video_starts>0).length;const watched50=rows.filter(r=>r.max_watch_percent>=50).length;const ctas=rows.filter(r=>r.cta_clicks>0).length;
 const hot=[...rows].filter(r=>r.video_starts>0||r.cta_clicks>0).sort((a,b)=>(b.cta_clicks-a.cta_clicks)||(b.max_watch_percent-a.max_watch_percent)||(b.max_watch_seconds-a.max_watch_seconds));
 return <main className="os-root" style={{minHeight:"100vh"}}><div className="os-content" style={{maxWidth:1500,margin:"0 auto",paddingTop:28}}>
   <div className="os-section-head"><div><div className="os-kicker">Email → Landingpage → Video → CTA</div><h1 className="os-title">Video Engagement</h1><p>Jeder Lead vom Versand bis zum WhatsApp-/Rechner-Klick. Watchtime ist echte Sehzeit, Playback zeigt die erreichte Videoposition.</p></div><div className="os-toolbar"><a className="os-btn" href="/analytics">Revenue Analytics</a><button className="os-btn" onClick={()=>void load()}>↻ Aktualisieren</button></div></div>
   {error?<div className="os-error">{error}</div>:null}
   <div className="os-grid os-kpis" style={{marginTop:18}}>{[[sent,"E-Mails gesendet","Outbound"],[opened,"E-Mails geöffnet",`${pct(opened,sent)}% Open`],[clicked,"E-Mail-Link geklickt",`${pct(clicked,opened)}% der Opens`],[viewed,"LP besucht","attributiert + direkt"],[started,"Video gestartet",`${pct(started,viewed)}% der Besucher`],[watched50,"≥ 50% gesehen",`${pct(watched50,started)}% der Starter`],[ctas,"CTA-Leads","WhatsApp / Rechner"]].map(([v,l,s])=><div className="os-card os-kpi" key={String(l)}><div className="os-kpi-label">{l}</div><div className="os-kpi-value">{v}</div><div className="os-kpi-sub">{s}</div></div>)}</div>
   <section className="os-card os-section" style={{marginTop:18}}><div className="os-section-head"><div><div className="os-kicker">Hot Leads</div><h2>Wer zeigt echtes Kaufinteresse?</h2></div><span className="os-pill green">Watchtime + CTA</span></div><div className="os-tablewrap"><table className="os-table"><thead><tr><th>Unternehmen</th><th>E-Mail</th><th>LP</th><th>Video</th><th>Watchtime</th><th>Position</th><th>CTA</th><th>Letztes Signal</th></tr></thead><tbody>{hot.length?hot.slice(0,100).map(r=><tr key={r.video_page_id}><td><strong>{r.company_name}</strong><div style={{fontSize:10,color:"#8792a4"}}>{r.contact_name||r.email||""}</div></td><td><span className={`os-pill ${r.emails_opened?"green":""}`}>{r.emails_opened?"Geöffnet":r.emails_sent?"Gesendet":"–"}</span></td><td>{r.page_views}</td><td><strong>{r.video_starts}</strong></td><td><strong>{time(r.max_watch_seconds)}</strong></td><td><span className={`os-pill ${r.max_watch_percent>=50?"green":r.max_watch_percent>=25?"":"hot"}`}>{r.max_watch_percent}% · {time(r.max_playback_seconds)}</span></td><td><strong>{r.cta_clicks}</strong></td><td>{dt(r.last_video_event_at)}</td></tr>):<tr><td colSpan={8}><div className="os-empty">Noch keine neuen Video-Signale.</div></td></tr>}</tbody></table></div></section>
   <section className="os-card os-section" style={{marginTop:18,marginBottom:40}}><div className="os-section-head"><div><div className="os-kicker">Alle personalisierten LPs</div><h2>Lead-Funnel im Detail</h2></div><span className="os-pill">{rows.length} Seiten</span></div>{loading?<div className="os-empty">Engagement wird geladen …</div>:<div className="os-tablewrap"><table className="os-table"><thead><tr><th>Unternehmen</th><th>Versand</th><th>Open</th><th>Mail-Klick</th><th>LP</th><th>Play</th><th>Max %</th><th>Watchtime</th><th>CTA</th><th>Seite</th></tr></thead><tbody>{rows.map(r=><tr key={r.video_page_id}><td><strong>{r.company_name}</strong></td><td>{r.emails_sent}</td><td>{r.emails_opened}</td><td>{r.emails_clicked}</td><td>{r.page_views}</td><td>{r.video_starts}</td><td>{r.max_watch_percent}%</td><td>{time(r.max_watch_seconds)}</td><td>{r.cta_clicks}</td><td><a className="os-btn" href={`/v/${r.slug}`} target="_blank" rel="noreferrer">Öffnen ↗</a></td></tr>)}</tbody></table></div>}</section>
 </div></main>
}
