"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";
import { SegmentedEnergyVideoPlayer } from "@/components/segmented-energy-video-player";
import { EnergyStudioConfig, EnergyStudioSegment, makeDefaultStudioConfig, parseStudioConfig } from "@/lib/energy-studio";
import { StudioV3LandingPage } from "@/components/studio-v3/landing-page-renderer";
import { StudioV3PublicPlayer } from "@/components/studio-v3/studio-v3-public-player";
import { WALKENHORST_BRAND_DEFAULT, defaultStudioV3Landing, normalizeStudioV3Project, type StudioV3BrandKit, type StudioV3LandingConfig, type StudioV3LeadVariables, type StudioV3Timeline } from "@/lib/studio-v3";

type VideoPage={id:string;company_name:string;prospect_name:string|null;website_url:string|null;presenter_video_url:string|null;website_capture_url:string|null;headline:string;intro_text:string|null;bullets:string[];cta_label:string;cta_url:string|null;duration_seconds:number;status:string;studio_config:unknown;accent_color:string|null;template_key:string|null;timeline_v3:unknown;landing_config:unknown;brand_kit_snapshot:unknown;rendered_video_url:string|null;rendered_video_format:string|null};
function effectiveLegacyConfig(page:VideoPage):EnergyStudioConfig{const raw=page.studio_config&&typeof page.studio_config==="object"?page.studio_config as Record<string,unknown>:{};if(Array.isArray(raw.segments)&&raw.segments.length)return parseStudioConfig(raw,page.template_key||"pv-gewerbe");const fallback=makeDefaultStudioConfig(page.template_key||"pv-gewerbe");const segments:EnergyStudioSegment[]=[{id:"legacy-website",type:"website",role:"website",label:"Website-Analyse",duration:Math.max(8,Math.min(45,page.duration_seconds-(page.presenter_video_url?15:0)))}];if(page.presenter_video_url)segments.push({id:"legacy-presenter",type:"video",role:"speaker",label:"Persönliche Einordnung",mediaUrl:page.presenter_video_url,duration:15});return{...fallback,headline:page.headline,subtitle:page.intro_text||fallback.subtitle,ctaLabel:page.cta_label,ctaUrl:page.cta_url||fallback.ctaUrl,accentColor:page.accent_color||fallback.accentColor,segments}}
function brandFromSnapshot(raw:unknown,page:VideoPage):StudioV3BrandKit{if(!raw||typeof raw!=="object")return{...WALKENHORST_BRAND_DEFAULT,accentColor:page.accent_color||WALKENHORST_BRAND_DEFAULT.accentColor,defaultCtaLabel:page.cta_label,defaultCtaUrl:page.cta_url||WALKENHORST_BRAND_DEFAULT.defaultCtaUrl};const value=raw as Partial<StudioV3BrandKit>;return{...WALKENHORST_BRAND_DEFAULT,...value,metadata:{...WALKENHORST_BRAND_DEFAULT.metadata,...(value.metadata||{})},defaultCtaLabel:value.defaultCtaLabel||page.cta_label,defaultCtaUrl:value.defaultCtaUrl||page.cta_url||WALKENHORST_BRAND_DEFAULT.defaultCtaUrl}}
function landingFromPage(page:VideoPage):StudioV3LandingConfig{const raw=page.landing_config as Partial<StudioV3LandingConfig>|null;if(raw?.version===3&&Array.isArray(raw.blocks))return raw as StudioV3LandingConfig;const project=normalizeStudioV3Project(page.studio_config,page.template_key||"pv-gewerbe");return project.landing?.version===3?project.landing:defaultStudioV3Landing()}
function timelineFromPage(page:VideoPage):StudioV3Timeline|null{const raw=page.timeline_v3 as Partial<StudioV3Timeline>|null;if(raw?.version===3&&Array.isArray(raw.tracks))return raw as StudioV3Timeline;const project=normalizeStudioV3Project(page.studio_config,page.template_key||"pv-gewerbe");return project.version===3?project.timeline:null}

export function VideoLanding({slug}:{slug:string}){const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);const[page,setPage]=useState<VideoPage|null>(null);const[loading,setLoading]=useState(true);const[qualificationDone,setQualificationDone]=useState(false);const[qualificationError,setQualificationError]=useState<string|null>(null);const[qualificationBusy,setQualificationBusy]=useState(false);const sentMarks=useRef(new Set<number>());const sessionRef=useRef("");const latestWatch=useRef(0);
 function sessionId(){if(!sessionRef.current)sessionRef.current=crypto.randomUUID();return sessionRef.current}
 useEffect(()=>{if(!supabase){setLoading(false);return}void supabase.from("energy_video_pages").select("id,company_name,prospect_name,website_url,presenter_video_url,website_capture_url,headline,intro_text,bullets,cta_label,cta_url,duration_seconds,status,studio_config,accent_color,template_key,timeline_v3,landing_config,brand_kit_snapshot,rendered_video_url,rendered_video_format").eq("slug",slug).eq("is_public",true).single().then(async({data,error})=>{if(!error&&data){setPage(data as VideoPage);await supabase.from("energy_video_events").insert({video_page_id:data.id,event_type:"view",session_id:sessionId()})}setLoading(false)})},[slug,supabase]);
 async function playbackStart(){if(!page||!supabase)return;await supabase.from("energy_video_events").insert({video_page_id:page.id,event_type:"play",watch_percent:latestWatch.current,session_id:sessionId()})}
 async function progress(mark:number){if(!page||!supabase||sentMarks.current.has(mark))return;sentMarks.current.add(mark);latestWatch.current=Math.max(latestWatch.current,mark);await supabase.from("energy_video_events").insert({video_page_id:page.id,event_type:"progress",watch_percent:mark,session_id:sessionId()})}
 async function cta(){if(!page)return;await supabase?.from("energy_video_events").insert({video_page_id:page.id,event_type:"cta_click",watch_percent:latestWatch.current,session_id:sessionId()});const brand=brandFromSnapshot(page.brand_kit_snapshot,page);const target=brand.defaultCtaUrl||page.cta_url;if(target)window.location.href=target}
 async function trackAction(action:string,_target:string){if(!page||!supabase)return;const safe=action.toLowerCase().replace(/[^a-z0-9_-]+/g,"_").slice(0,48)||"action";await supabase.from("energy_video_events").insert([{video_page_id:page.id,event_type:"cta_click",watch_percent:latestWatch.current,session_id:sessionId()},{video_page_id:page.id,event_type:`cta_${safe}`,watch_percent:latestWatch.current,session_id:sessionId()}])}
 async function qualify(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!supabase)return;setQualificationBusy(true);setQualificationError(null);try{const f=new FormData(event.currentTarget);const{data,error}=await supabase.functions.invoke("qualification-submit",{body:{slug,sessionId:sessionId(),interest:f.get("interest"),timeline:f.get("timeline"),contactName:f.get("contactName"),email:f.get("email"),phone:f.get("phone"),notes:f.get("notes")}});if(error||data?.error)throw new Error(data?.error||error?.message||"Übermittlung fehlgeschlagen");setQualificationDone(true)}catch(e){setQualificationError(e instanceof Error?e.message:"Übermittlung fehlgeschlagen")}finally{setQualificationBusy(false)}}
 if(loading)return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#f5f5f7",fontFamily:"-apple-system,BlinkMacSystemFont,Helvetica Neue,Arial,sans-serif",color:"#6e6e73"}}>Persönliche Analyse wird geladen …</main>;
 if(!page)return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#f5f5f7",fontFamily:"-apple-system,BlinkMacSystemFont,Helvetica Neue,Arial,sans-serif"}}><section style={{maxWidth:520,padding:30,textAlign:"center"}}><h1 style={{fontSize:30,letterSpacing:-1}}>Analyse nicht verfügbar</h1><p style={{color:"#6e6e73",lineHeight:1.6}}>Dieser persönliche Link ist nicht mehr aktiv.</p></section></main>;
 const brand=brandFromSnapshot(page.brand_kit_snapshot,page);const landing=landingFromPage(page);const timeline=timelineFromPage(page);const variables:StudioV3LeadVariables={company:page.company_name,firstname:page.prospect_name,website:page.website_url,problem:page.intro_text,cta:brand.defaultCtaLabel};const qualification=<QualificationForm company={page.company_name} done={qualificationDone} busy={qualificationBusy} error={qualificationError} onSubmit={qualify}/>;const isEnergiekosten=page.template_key==="energiekosten";const liveStudio=timeline?<StudioV3PublicPlayer timeline={timeline} brand={brand} variables={variables} resolveSource={item=>item.sourceUrl||null} thumbnailWebsiteUrl={page.website_capture_url} thumbnailPresenterUrl={page.presenter_video_url} onPlaybackStart={()=>void playbackStart()} onProgress={mark=>void progress(mark)}/>:null;const video=isEnergiekosten&&liveStudio?liveStudio:page.rendered_video_url?<RenderedVideo url={page.rendered_video_url} brand={brand} onStart={()=>void playbackStart()} onProgress={mark=>void progress(mark)}/>:liveStudio||<LegacyVideo page={page} onStart={()=>void playbackStart()} onProgress={mark=>void progress(mark)}/>;const findings=(page.bullets||[]).slice(0,6);const metrics=[{label:"Persönliche Analyse",value:page.company_name},{label:"Video",value:`${Math.round(page.duration_seconds/60*10)/10} Min.`},{label:"Schwerpunkt",value:page.template_key||"Energie"},{label:"Status",value:isEnergiekosten&&timeline?"Persönlich bereit":page.rendered_video_url?"Final gerendert":"Live bereit"}];return <StudioV3LandingPage landing={landing} brand={brand} variables={variables} video={video} findings={findings} metrics={metrics} qualification={qualification} onCta={()=>void cta()} onAction={(action,target)=>void trackAction(action,target)}/>}

function RenderedVideo({url,brand,onStart,onProgress}:{url:string;brand:StudioV3BrandKit;onStart:()=>void;onProgress:(mark:number)=>void}){const started=useRef(false);const sent=useRef(new Set<number>());return <div style={{position:"relative",overflow:"hidden",borderRadius:18,background:"#090909",boxShadow:"0 20px 54px rgba(0,0,0,.18)"}}><video src={url} controls playsInline preload="auto" style={{display:"block",width:"100%",aspectRatio:"16/9",background:"#090909",accentColor:brand.accentColor}} onPlay={()=>{if(!started.current){started.current=true;onStart()}}} onTimeUpdate={event=>{const video=event.currentTarget;if(!video.duration)return;const percent=Math.round(video.currentTime/video.duration*100);for(const mark of[25,50,75,90,100])if(percent>=mark&&!sent.current.has(mark)){sent.current.add(mark);onProgress(mark)}}}/></div>}
function LegacyVideo({page,onStart,onProgress}:{page:VideoPage;onStart:()=>void;onProgress:(mark:number)=>void}){const config=effectiveLegacyConfig(page);return <SegmentedEnergyVideoPlayer segments={config.segments} websiteCaptureUrl={page.website_capture_url} presenterVideoUrl={page.presenter_video_url} presenterName={config.presenterName} company={page.company_name} accentColor={config.accentColor||page.accent_color||"#d5a62b"} onPlaybackStart={onStart} onProgress={onProgress}/>}
function QualificationForm({company,done,busy,error,onSubmit}:{company:string;done:boolean;busy:boolean;error:string|null;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){if(done)return <div style={{border:"1px solid rgba(58,142,78,.18)",borderRadius:14,background:"rgba(58,142,78,.07)",padding:18,color:"#246936",fontSize:13,lineHeight:1.55}}><strong>Vielen Dank.</strong><br/>Ihre Angaben sind angekommen. Walkenhorst kann sich jetzt gezielt mit einer konkreten Einschätzung melden.</div>;const input:React.CSSProperties={width:"100%",minHeight:42,border:"1px solid rgba(60,60,67,.14)",borderRadius:10,background:"#fff",padding:"0 11px",font:"inherit",fontSize:12,color:"#1d1d1f"};const label:React.CSSProperties={display:"grid",gap:6,fontSize:11,fontWeight:600,color:"#66676b"};return <form onSubmit={onSubmit}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:10}}><label style={label}>Größtes Interesse<select name="interest" required defaultValue="" style={input}><option value="" disabled>Bitte wählen</option><option value="stromkosten">Stromkosten senken</option><option value="photovoltaik">Photovoltaik / Eigenverbrauch</option><option value="energieeffizienz">Energieeffizienz</option><option value="foerderung">Förderung / Finanzierung</option><option value="analyse">Erst einmal Potenzial prüfen</option></select></label><label style={label}>Wann soll das Thema geprüft werden?<select name="timeline" defaultValue="1-3-monate" style={input}><option value="sofort">So schnell wie möglich</option><option value="1-3-monate">In den nächsten 1–3 Monaten</option><option value="3-6-monate">In 3–6 Monaten</option><option value="spaeter">Später / noch offen</option></select></label><label style={label}>Ansprechpartner<input name="contactName" placeholder="Vor- und Nachname" style={input}/></label><label style={label}>E-Mail<input name="email" type="email" placeholder="name@unternehmen.de" style={input}/></label><label style={label}>Telefon<input name="phone" placeholder="Telefonnummer" style={input}/></label><label style={label}>Kurzer Hinweis<input name="notes" placeholder={`z. B. 2 Standorte bei ${company}`} style={input}/></label></div>{error?<div style={{marginTop:10,color:"#b4231d",fontSize:11}}>{error}</div>:null}<button disabled={busy} style={{marginTop:14,minHeight:42,border:0,borderRadius:11,background:"#1d1d1f",color:"#fff",padding:"0 16px",font:"inherit",fontSize:12,fontWeight:650,cursor:"pointer"}}>{busy?"Wird übermittelt …":"Potenzialcheck absenden"}</button></form>}
