import { lookup } from "node:dns/promises";
import { isIP } from "node:net";
import chromium from "@sparticuz/chromium-min";
import puppeteer, { type Page } from "puppeteer-core";

const WIDTH=1280;
const HEIGHT=720;
const MAX_HEIGHT=16000;
const CHROMIUM_PACK_URL="https://github.com/Sparticuz/chromium/releases/download/v149.0.0/chromium-v149.0.0-pack.x64.tar";
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));

function normalized(value:string){return value.toLowerCase().replace(/^\[|\]$/g,"").replace(/\.$/,"")}
function privateAddress(address:string){const value=normalized(address);const version=isIP(value);if(version===4){const[a,b]=value.split(".").map(Number);return a===0||a===10||a===127||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===0)||(a===192&&b===168)||(a===198&&(b===18||b===19))||a>=224}if(version===6){if(value==="::"||value==="::1")return true;if(/^(fc|fd)/.test(value)||/^fe[89ab]/.test(value))return true;const mapped=value.match(/::ffff:(\d+\.\d+\.\d+\.\d+)$/)?.[1];return mapped?privateAddress(mapped):false}return false}
function blockedHostname(hostname:string){const value=normalized(hostname);return !value||value==="localhost"||value.endsWith(".localhost")||value.endsWith(".local")||value.endsWith(".internal")||value==="metadata.google.internal"||privateAddress(value)}
const hostnameCache=new Map<string,Promise<boolean>>();
async function hostnamePublic(hostname:string){const value=normalized(hostname);if(blockedHostname(value))return false;if(isIP(value))return !privateAddress(value);const cached=hostnameCache.get(value);if(cached)return cached;const result=lookup(value,{all:true,verbatim:true}).then(rows=>rows.length>0&&rows.every(row=>!privateAddress(row.address))).catch(()=>false);hostnameCache.set(value,result);return result}
export async function safeCaptureUrl(input:string){let url:URL;try{url=new URL(/^https?:\/\//i.test(input)?input:`https://${input}`)}catch{throw new Error("Die Website-Adresse ist ungültig.")}if(!["http:","https:"].includes(url.protocol))throw new Error("Es sind nur öffentliche HTTP- und HTTPS-Websites erlaubt.");if(!(await hostnamePublic(url.hostname)))throw new Error("Private oder lokale Netzwerkadressen dürfen nicht aufgenommen werden.");return url.toString()}

async function cleanConsent(page:Page){
  const selectors=["#onetrust-reject-all-handler","#onetrust-accept-btn-handler","#CybotCookiebotDialogBodyButtonDecline","#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll","[data-testid='uc-deny-all-button']","[data-testid='uc-accept-all-button']",".cmplz-deny",".cmplz-accept","[data-cookie-consent='reject']","[data-cookie-consent='accept']"];
  for(const selector of selectors){try{const element=await page.$(selector);if(element){await element.click().catch(()=>undefined);await sleep(350);break}}catch{}}
  await page.evaluate(()=>{
    const roots:Array<Document|ShadowRoot>=[document];
    for(let i=0;i<roots.length;i++)for(const element of Array.from(roots[i].querySelectorAll("*")))if(element.shadowRoot)roots.push(element.shadowRoot);
    const hide=(element:Element)=>{if(element instanceof HTMLElement)element.style.setProperty("display","none","important")};
    const known=["#onetrust-banner-sdk","#onetrust-consent-sdk","#CybotCookiebotDialog","#CybotCookiebotDialogBodyUnderlay","#usercentrics-root",".cmplz-cookiebanner","[id*='cookie-banner' i]","[class*='cookie-banner' i]","[class*='cookiebanner' i]","[id*='consent-banner' i]","[class*='consent-banner' i]"];
    for(const root of roots){for(const selector of known)for(const element of Array.from(root.querySelectorAll(selector)))hide(element);for(const element of Array.from(root.querySelectorAll("[role='dialog'],[aria-modal='true'],aside,section,div")).slice(0,5000)){if(!(element instanceof HTMLElement))continue;const style=getComputedStyle(element);if(style.position!=="fixed"&&style.position!=="sticky")continue;const rect=element.getBoundingClientRect();if(rect.width*rect.height<innerWidth*innerHeight*.08)continue;const signature=`${element.id} ${element.className} ${(element.textContent||"").slice(0,2200)}`;if(/(cookie|consent|datenschutz|einwilligung|privacy|tracking|cmp)/i.test(signature))hide(element)}}
    document.documentElement.style.setProperty("overflow","auto","important");document.body?.style.setProperty("overflow","auto","important");
  }).catch(()=>undefined);
}

async function primeLazy(page:Page){await page.evaluate(async(maximum)=>{const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));const height=Math.min(maximum,Math.max(document.body?.scrollHeight||0,document.documentElement.scrollHeight||0));for(let top=0;top<height;top+=650){window.scrollTo({top,behavior:"instant"});await wait(75)}window.scrollTo({top:0,behavior:"instant"})},MAX_HEIGHT);await sleep(400)}

export async function captureStudioWebsite(input:string){const websiteUrl=await safeCaptureUrl(input);const executablePath=process.env.CHROMIUM_EXECUTABLE_PATH||await chromium.executablePath(process.env.CHROMIUM_PACK_URL||CHROMIUM_PACK_URL);const args=await puppeteer.defaultArgs({args:chromium.args,headless:"shell"});const browser=await puppeteer.launch({args,executablePath,headless:"shell",defaultViewport:{width:WIDTH,height:HEIGHT,deviceScaleFactor:1,hasTouch:false,isLandscape:true,isMobile:false}});try{const page=await browser.newPage();await page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36");await page.setExtraHTTPHeaders({"accept-language":"de-DE,de;q=0.9,en;q=0.7"});await page.setRequestInterception(true);page.on("request",async request=>{try{const requestUrl=new URL(request.url());if(!["http:","https:","data:","blob:"].includes(requestUrl.protocol)){await request.abort("blockedbyclient");return}if(["http:","https:"].includes(requestUrl.protocol)&&!(await hostnamePublic(requestUrl.hostname))){await request.abort("blockedbyclient");return}await request.continue()}catch{await request.abort("blockedbyclient").catch(()=>undefined)}});const response=await page.goto(websiteUrl,{waitUntil:"domcontentloaded",timeout:40000});if(!response||response.status()>=400)throw new Error(`Die Website antwortet mit HTTP ${response?.status()||"unbekannt"}.`);await safeCaptureUrl(page.url());await page.waitForNetworkIdle({idleTime:650,timeout:7000}).catch(()=>undefined);await sleep(700);await cleanConsent(page);await primeLazy(page);await cleanConsent(page);await page.evaluate(()=>document.fonts?.ready).catch(()=>undefined);await page.evaluate(()=>window.scrollTo({top:0,behavior:"instant"}));await sleep(300);const height=await page.evaluate(maximum=>Math.min(maximum,Math.max(720,document.body?.scrollHeight||0,document.documentElement.scrollHeight||0)),MAX_HEIGHT);const image=await page.screenshot({type:"webp",quality:84,clip:{x:0,y:0,width:WIDTH,height},captureBeyondViewport:true,optimizeForSpeed:true});return{buffer:Buffer.from(image),height,finalUrl:page.url()}}finally{await browser.close().catch(()=>undefined)}}
