import chromium from "@sparticuz/chromium-min";
import puppeteer, { type Browser, type Page } from "puppeteer-core";
import { safeCaptureUrl } from "@/lib/studio-website-capture";

const CHROMIUM_PACK_URL="https://github.com/Sparticuz/chromium/releases/download/v149.0.0/chromium-v149.0.0-pack.x64.tar";
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));

async function browser(){const executablePath=process.env.CHROMIUM_EXECUTABLE_PATH||await chromium.executablePath(process.env.CHROMIUM_PACK_URL||CHROMIUM_PACK_URL);const args=await puppeteer.defaultArgs({args:chromium.args,headless:"shell"});return puppeteer.launch({args,executablePath,headless:"shell",defaultViewport:{width:1440,height:1000,deviceScaleFactor:1}})}
async function securePage(instance:Browser){const page=await instance.newPage();await page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36");await page.setExtraHTTPHeaders({"accept-language":"de-DE,de;q=0.9,en;q=0.7"});await page.setRequestInterception(true);page.on("request",async request=>{try{const url=new URL(request.url());if(["data:","blob:"].includes(url.protocol)){await request.continue();return}if(!["http:","https:"].includes(url.protocol)){await request.abort("blockedbyclient");return}await safeCaptureUrl(url.toString());await request.continue()}catch{await request.abort("blockedbyclient").catch(()=>undefined)}});return page}
function absolutize(base:string,value:string|null){if(!value)return null;try{return new URL(value,base).toString()}catch{return null}}

export type BrandScanResult={url:string;title:string;logoUrl:string|null;faviconUrl:string|null;portraitUrl:string|null;colors:string[];primaryColor:string;accentColor:string;backgroundColor:string;textColor:string;headingFont:string;bodyFont:string;buttonRadius:number;ctaText:string|null;heroHeadline:string|null};

export async function scanStudioBrand(input:string):Promise<BrandScanResult>{const target=await safeCaptureUrl(input);const instance=await browser();try{const page=await securePage(instance);const response=await page.goto(target,{waitUntil:"domcontentloaded",timeout:40000});if(!response||response.status()>=400)throw new Error(`Website antwortet mit HTTP ${response?.status()||"unbekannt"}.`);await safeCaptureUrl(page.url());await page.waitForNetworkIdle({idleTime:600,timeout:7000}).catch(()=>undefined);await sleep(450);const raw=await page.evaluate(()=>{
 const visible=(element:Element)=>{const r=(element as HTMLElement).getBoundingClientRect();const s=getComputedStyle(element);return r.width>10&&r.height>8&&s.display!=="none"&&s.visibility!=="hidden"&&Number(s.opacity||1)>.1};
 const rgbToHex=(value:string)=>{const m=value.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/i);if(!m)return null;return`#${[m[1],m[2],m[3]].map(v=>Number(v).toString(16).padStart(2,"0")).join("").toUpperCase()}`};
 const candidates=[...document.querySelectorAll("header,nav,main,section,article,h1,h2,h3,p,a,button,[role=button],footer")].filter(visible).slice(0,1200);const colorCounts=new Map<string,number>();for(const el of candidates){const s=getComputedStyle(el);for(const raw of[s.color,s.backgroundColor,s.borderColor]){const hex=rgbToHex(raw);if(!hex||hex==="#00000000")continue;colorCounts.set(hex,(colorCounts.get(hex)||0)+1)}}
 const images=[...document.images].filter(visible);const logo=images.find(img=>/logo/i.test(`${img.alt} ${img.id} ${img.className} ${img.currentSrc||img.src}`))||document.querySelector("header img") as HTMLImageElement|null;const portrait=images.find(img=>/(andreas|walkenhorst|portrait|person|startseite-andreas)/i.test(`${img.alt} ${img.title} ${img.currentSrc||img.src}`));const icon=document.querySelector("link[rel~='icon'],link[rel='shortcut icon']") as HTMLLinkElement|null;const h1=[...document.querySelectorAll("h1")].find(visible) as HTMLElement|undefined;const body=getComputedStyle(document.body);const heading=h1?getComputedStyle(h1):body;const button=[...document.querySelectorAll("button,a")].find(el=>visible(el)&&/(erstgespräch|beratung|kontakt|anfragen|vereinbaren)/i.test(el.textContent||"")) as HTMLElement|undefined;const bs=button?getComputedStyle(button):null;return{title:document.title,logo:logo?.currentSrc||logo?.src||null,portrait:portrait?.currentSrc||portrait?.src||null,icon:icon?.href||null,colors:[...colorCounts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,14).map(([color,count])=>({color,count})),headingFont:heading.fontFamily||"",bodyFont:body.fontFamily||"",buttonRadius:bs?parseFloat(bs.borderRadius)||0:0,buttonBg:bs?.backgroundColor||"",buttonColor:bs?.color||"",ctaText:button?.textContent?.trim()||null,heroHeadline:h1?.textContent?.trim()||null,bodyBg:body.backgroundColor,bodyColor:body.color};
 });const colors=raw.colors.map(entry=>entry.color);const usable=colors.filter(color=>!["#FFFFFF","#FDFDFD","#FAFAFA","#000000"].includes(color));const buttonHex=raw.buttonBg.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/i);const buttonColor=buttonHex?`#${[buttonHex[1],buttonHex[2],buttonHex[3]].map(v=>Number(v).toString(16).padStart(2,"0")).join("").toUpperCase()}`:null;const bodyBgMatch=raw.bodyBg.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/i);const backgroundColor=bodyBgMatch?`#${[bodyBgMatch[1],bodyBgMatch[2],bodyBgMatch[3]].map(v=>Number(v).toString(16).padStart(2,"0")).join("").toUpperCase()}`:"#FFFFFF";const bodyColorMatch=raw.bodyColor.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/i);const textColor=bodyColorMatch?`#${[bodyColorMatch[1],bodyColorMatch[2],bodyColorMatch[3]].map(v=>Number(v).toString(16).padStart(2,"0")).join("").toUpperCase()}`:"#151515";return{url:page.url(),title:raw.title,logoUrl:absolutize(page.url(),raw.logo),faviconUrl:absolutize(page.url(),raw.icon),portraitUrl:absolutize(page.url(),raw.portrait),colors,primaryColor:textColor,accentColor:buttonColor||usable[0]||"#D9A928",backgroundColor,textColor,headingFont:raw.headingFont||"Arial, Helvetica, sans-serif",bodyFont:raw.bodyFont||"Arial, Helvetica, sans-serif",buttonRadius:Math.round(raw.buttonRadius||12),ctaText:raw.ctaText,heroHeadline:raw.heroHeadline}}finally{await instance.close().catch(()=>undefined)}}

export async function rasterizeStudioAsset(input:string){const target=await safeCaptureUrl(input);const instance=await browser();try{const page=await securePage(instance);await page.setViewport({width:1800,height:1200,deviceScaleFactor:1});await page.setContent(`<html><head><style>html,body{margin:0;background:transparent;display:grid;place-items:center;width:100%;height:100%}img{display:block;max-width:1600px;max-height:1000px;object-fit:contain}</style></head><body><img id="asset" alt="brand asset"></body></html>`,{waitUntil:"domcontentloaded"});await page.evaluate(url=>{const img=document.getElementById("asset") as HTMLImageElement;img.src=url},target);await page.waitForFunction(()=>{const img=document.getElementById("asset") as HTMLImageElement;return img&&img.complete&&img.naturalWidth>0},{timeout:20000});const box=await page.$eval("#asset",element=>{const r=(element as HTMLElement).getBoundingClientRect();return{x:Math.max(0,r.x),y:Math.max(0,r.y),width:Math.max(1,r.width),height:Math.max(1,r.height)}});const image=await page.screenshot({type:"png",clip:{x:box.x,y:box.y,width:Math.min(1800,box.width),height:Math.min(1200,box.height)},omitBackground:true});return Buffer.from(image)}finally{await instance.close().catch(()=>undefined)}}
