import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const H={"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*","access-control-allow-headers":"authorization, x-client-info, apikey, content-type","access-control-allow-methods":"POST, OPTIONS"};
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
const FIRST_SUBJECT="Kurze Energieanalyse zu {{company}}";
const FIRST_BODY="Guten Tag,\n\nich habe für {{company}} eine kurze persönliche Energieanalyse vorbereitet.\n\nDer Hintergrund: Viele Gewerbebetriebe haben Strom- oder Gasverträge in einer völlig anderen Marktphase abgeschlossen. Was damals wirtschaftlich gut war, kann heute deutlich anders aussehen – ohne dass es im Tagesgeschäft auffällt.\n\nAndreas Walkenhorst zeigt Ihnen in 107 Sekunden, welche Punkte wir bei {{company}} zuerst prüfen würden:\n{{video_url}}\n\nWenn danach nichts zu optimieren ist, sagen wir das genauso. Wenn doch, reichen 15 Minuten für einen ersten Abgleich.\n\nFalls Sie dafür nicht selbst zuständig sind, würde ich mich über eine kurze Weiterleitung an die verantwortliche Person freuen.\n\nViele Grüße\nAndreas Walkenhorst\nWalkenhorst Energie";
const FOLLOW_SUBJECT="Energiekosten bei {{company}} – kurze Rückfrage";
const FOLLOW_BODY="Guten Tag,\n\nich wollte die kurze Analyse zu {{company}} noch einmal nach oben holen.\n\nWenn Ihre aktuellen Energieverträge bereits sauber geprüft sind, können wir das Thema direkt abhaken. Falls nicht, reichen 107 Sekunden, um zu sehen, ob ein genauerer Abgleich überhaupt sinnvoll ist:\n{{video_url}}\n\nWenn das Thema bei einer anderen Person im Haus liegt, freue ich mich über eine kurze Weiterleitung.\n\nViele Grüße\nAndreas Walkenhorst\nWalkenhorst Energie";

function env(){const url=Deno.env.get("SUPABASE_URL")!;const pubs=Deno.env.get("SUPABASE_PUBLISHABLE_KEYS");const secs=Deno.env.get("SUPABASE_SECRET_KEYS");const pub=pubs?JSON.parse(pubs)?.default:Deno.env.get("SUPABASE_ANON_KEY");const secret=secs?JSON.parse(secs)?.default:Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!pub||!secret)throw new Error("Backend configuration missing");return{url,pub,secret}}
function admin(){const e=env();return createClient(e.url,e.secret,{auth:{persistSession:false,autoRefreshToken:false}})}
type DB=ReturnType<typeof admin>;
async function user(req:Request){const auth=req.headers.get("authorization")||"";const token=auth.toLowerCase().startsWith("bearer ")?auth.slice(7).trim():"";if(!token)return null;const e=env();const c=createClient(e.url,e.pub,{auth:{persistSession:false,autoRefreshToken:false}});const{data,error}=await c.auth.getUser(token);if(error||!data.user)return null;const owner=typeof data.user.app_metadata?.workspace_owner_id==="string"?data.user.app_metadata.workspace_owner_id.trim():"";return{...data.user,id:owner||data.user.id}}

type Audience={customerType?:string;source?:string;minScore?:number;maxLeads?:number;onlyFresh?:boolean};
type StepInput={stepType?:string;delayHours?:number;subject?:string;body?:string;includeVideo?:boolean};
function cleanAudience(v:any){return{customerType:["commercial","private"].includes(String(v?.customerType))?String(v.customerType):"all",source:String(v?.source||"").trim(),minScore:Math.max(0,Math.min(100,Number(v?.minScore)||0)),maxLeads:Math.max(1,Math.min(500,Number(v?.maxLeads)||50)),onlyFresh:v?.onlyFresh!==false}}
function cleanSteps(v:any):StepInput[]{const raw=Array.isArray(v)?v.slice(0,10):[];const allowed=new Set(["email","video_email","manual_call","wait"]);return raw.map((s:any,i:number)=>({stepType:allowed.has(String(s?.stepType))?String(s.stepType):i===0?"video_email":"email",delayHours:Math.max(0,Math.min(8760,Number(s?.delayHours)||0)),subject:String(s?.subject||"").trim(),body:String(s?.body||"").trim(),includeVideo:Boolean(s?.includeVideo||s?.stepType==="video_email")}))}
function buildLeadQuery(db:DB,userId:string,a:any,count=false){let q:any=db.from("energy_leads").select("id,company_name,contact_name,email,city,source,total_score,status,customer_type",count?{count:"exact"}:undefined).eq("user_id",userId).not("email","is",null).neq("email","").eq("do_not_contact",false).is("unsubscribed_at",null).neq("email_status","invalid").gte("total_score",a.minScore);if(a.customerType!=="all")q=q.eq("customer_type",a.customerType);if(a.source)q=q.eq("source",a.source);if(a.onlyFresh)q=q.in("status",["new","research","ready"]);return q.order("total_score",{ascending:false}).order("created_at",{ascending:false}).limit(a.maxLeads)}
async function owned(db:DB,id:string,userId:string){const{data,error}=await db.from("energy_campaigns").select("*").eq("id",id).eq("user_id",userId).maybeSingle();if(error)throw error;return data}
function cleanFilter(c:any){const f={...(c?.lead_filter||{})};delete f.mailboxes_paused_by_campaign;return f}
async function restoreMailboxes(db:DB,c:any,userId:string){const ids=Array.isArray(c?.lead_filter?.mailboxes_paused_by_campaign)?c.lead_filter.mailboxes_paused_by_campaign.map(String).filter(Boolean):[];if(!ids.length)return;const{error}=await db.from("energy_mailboxes").update({status:"ready",updated_at:new Date().toISOString()}).eq("user_id",userId).eq("status","paused").in("id",ids);if(error)throw error}
async function videoReadiness(db:DB,campaign:any){if(!campaign?.include_video)return{required:0,ready:0,pending:0,templateKey:"energiekosten"};const{data,error}=await db.rpc("energy_campaign_video_readiness",{p_campaign_id:campaign.id});if(error)throw error;return data||{required:0,ready:0,pending:0,templateKey:"energiekosten"}}
async function snapshot(db:DB,c:any){const[{data:steps},{data:members},{data:messages},vr]=await Promise.all([db.from("energy_campaign_steps").select("*").eq("campaign_id",c.id).order("step_order"),db.from("energy_campaign_members").select("id,status,current_step,stopped_reason,reply_status").eq("campaign_id",c.id),db.from("energy_messages").select("id,status,to_email,from_email,subject,sent_at,opened_at,clicked_at,replied_at,error,step_order,created_at,energy_leads(company_name)").eq("campaign_id",c.id).eq("direction","outbound").order("created_at",{ascending:false}).limit(1000),videoReadiness(db,c)]);const mr=members||[],msg=messages||[];const sent=msg.filter((m:any)=>m.sent_at||["sent","delivered","opened","clicked","replied"].includes(m.status)).length;const opened=msg.filter((m:any)=>m.opened_at||["opened","clicked","replied"].includes(m.status)).length;const clicked=msg.filter((m:any)=>m.clicked_at||m.status==="clicked").length;const replied=msg.filter((m:any)=>m.replied_at||m.status==="replied").length;return{...c,steps:steps||[],videoReadiness:vr,metrics:{audience:mr.length,queued:mr.filter((m:any)=>m.status==="queued").length,completed:mr.filter((m:any)=>m.status==="completed").length,stopped:mr.filter((m:any)=>m.status==="stopped").length,sent,opened,clicked,replied,failed:msg.filter((m:any)=>m.status==="failed").length,bounced:msg.filter((m:any)=>m.status==="bounced").length},recentMessages:msg.slice(0,30)}}
async function loadAll(db:DB,userId:string){const[{data:campaigns,error:ce},{data:mailboxes,error:me},{count:leadCount}]=await Promise.all([db.from("energy_campaigns").select("*").eq("user_id",userId).order("created_at",{ascending:false}),db.from("energy_mailboxes").select("id,email_address,from_name,status,daily_limit,sent_today,last_tested_at,last_error").eq("user_id",userId).order("created_at"),db.from("energy_leads").select("id",{count:"exact",head:true}).eq("user_id",userId).not("email","is",null).eq("do_not_contact",false)]);if(ce)throw ce;if(me)throw me;return{campaigns:await Promise.all((campaigns||[]).map((c:any)=>snapshot(db,c))),mailboxes:mailboxes||[],leadCount:Number(leadCount||0)}}
async function preview(db:DB,userId:string,input:any){const audience=cleanAudience(input);const{data,error,count}=await buildLeadQuery(db,userId,audience,true);if(error)throw error;return{audience,matched:Number(count||0),selected:(data||[]).length,sample:(data||[]).slice(0,8)}}
async function createCampaign(db:DB,userId:string,b:any){const name=String(b?.name||"").trim();if(!name)throw new Error("Kampagnenname fehlt");const audience=cleanAudience(b?.audience||{});let steps=cleanSteps(b?.steps);if(!steps.length)steps=[{stepType:"video_email",delayHours:0,subject:FIRST_SUBJECT,body:FIRST_BODY,includeVideo:true},{stepType:"email",delayHours:72,subject:FOLLOW_SUBJECT,body:FOLLOW_BODY,includeVideo:false},{stepType:"manual_call",delayHours:48,subject:"",body:"",includeVideo:false}];const tracking=String(b?.trackingBaseUrl||"").replace(/\/$/,"");if(!/^https:\/\//i.test(tracking))throw new Error("Tracking-URL muss mit https:// beginnen");const requested=Array.isArray(b?.mailboxIds)?b.mailboxIds.map(String).filter(Boolean).slice(0,10):[];let mailboxIds:string[]=[];if(requested.length){const{data,error}=await db.from("energy_mailboxes").select("id").eq("user_id",userId).in("id",requested);if(error)throw error;mailboxIds=(data||[]).map((x:any)=>x.id)}const includeVideo=b?.includeVideo!==false;const firstMail=steps.find(s=>["email","video_email"].includes(String(s.stepType)));const subject=String(b?.subject||firstMail?.subject||FIRST_SUBJECT).trim();const body=String(b?.body||firstMail?.body||FIRST_BODY).trim();const{data:c,error}=await db.from("energy_campaigns").insert({user_id:userId,name,status:"draft",subject_template:subject,body_template:body,daily_limit:Math.max(1,Math.min(150,Number(b?.dailyLimit)||30)),tracking_base_url:tracking,include_video:includeVideo,auto_personalize:b?.autoPersonalize!==false,reply_stops_sequence:true,send_window_start:String(b?.sendWindowStart||"08:30"),send_window_end:String(b?.sendWindowEnd||"17:30"),timezone:"Europe/Berlin",send_interval_minutes:Math.max(5,Math.min(60,Number(b?.sendIntervalMinutes)||5)),mailbox_ids:mailboxIds,lead_filter:{...audience,studio_template_key:includeVideo?"energiekosten":String(b?.studioTemplateKey||"energiekosten"),created_via:"campaign_command_center"},updated_at:new Date().toISOString()}).select("*").single();if(error||!c)throw error||new Error("Kampagne konnte nicht erstellt werden");const rows=steps.map((s,i)=>({campaign_id:c.id,step_order:i+1,step_type:s.stepType,delay_hours:i===0?0:s.delayHours,subject_template:s.subject||null,body_template:s.body||null,include_video:Boolean(s.includeVideo),active:true}));const sr=await db.from("energy_campaign_steps").insert(rows);if(sr.error)throw sr.error;const{data:leads,error:le}=await buildLeadQuery(db,userId,audience,false);if(le)throw le;const members=(leads||[]).map((l:any)=>({campaign_id:c.id,lead_id:l.id,status:"queued",current_step:1,next_step_at:null}));if(members.length){const mr=await db.from("energy_campaign_members").insert(members);if(mr.error)throw mr.error}return{campaignId:c.id,audienceCount:members.length}}
async function kick(db:DB,base:string|null){const e=env();const{data:key}=await db.rpc("energy_get_system_secret",{p_name:"energy_worker_key"});if(!key)return{ok:false,reason:"Worker-Key fehlt"};try{const r=await fetch(`${e.url}/functions/v1/campaign-worker`,{method:"POST",headers:{"content-type":"application/json","x-worker-key":String(key)},body:JSON.stringify({limit:1,...(base?{baseUrl:base}:{})})});const d=await r.json().catch(()=>({}));return{ok:r.ok,...d}}catch(x){return{ok:false,reason:x instanceof Error?x.message:"Worker konnte nicht gestartet werden"}}}
async function pause(db:DB,c:any,userId:string){await restoreMailboxes(db,c,userId);const{error}=await db.from("energy_campaigns").update({status:"paused",next_send_at:null,lead_filter:cleanFilter(c),updated_at:new Date().toISOString()}).eq("id",c.id).eq("user_id",userId);if(error)throw error}
async function start(db:DB,userId:string,id:string,kickNow=true){let c=await owned(db,id,userId);if(!c)throw new Error("Kampagne nicht gefunden");const[{count:members},{count:steps}]=await Promise.all([db.from("energy_campaign_members").select("id",{count:"exact",head:true}).eq("campaign_id",id),db.from("energy_campaign_steps").select("id",{count:"exact",head:true}).eq("campaign_id",id).eq("active",true)]);if(!members)throw new Error("Die Kampagne hat noch keine Empfänger");if(!steps)throw new Error("Die Kampagne hat noch keine Sequenz");if(!/^https:\/\//i.test(String(c.tracking_base_url||"")))throw new Error("Tracking-URL fehlt");const approvalRequired=String(c?.lead_filter?.approval_required||"")==="true"||c?.lead_filter?.approval_required===true;const approved=String(c?.lead_filter?.manual_launch_approved||"")==="true"||c?.lead_filter?.manual_launch_approved===true;if(approvalRequired&&!approved)throw new Error("MANUAL_LAUNCH_APPROVAL_REQUIRED: Erste Mail und Landingpage müssen vor dem Start ausdrücklich freigegeben werden.");const vr=await videoReadiness(db,c);if(Number(vr.required||0)>Number(vr.ready||0))throw new Error(`VIDEO_LAUNCH_BLOCKED: ${Number(vr.ready||0)}/${Number(vr.required||0)} finale MP4-Videos bereit. Erst alle Videos rendern.`);if(Number(vr.unpublishedMaster||0)>0)throw new Error("VIDEO_LAUNCH_BLOCKED: Golden Master ist nicht veröffentlicht.");await restoreMailboxes(db,c,userId);c={...c,lead_filter:cleanFilter(c)};const{data:boxes,error:be}=await db.from("energy_mailboxes").select("id,email_address,status").eq("user_id",userId).order("created_at");if(be)throw be;const requested=Array.isArray(c.mailbox_ids)?c.mailbox_ids.map(String):[];const ready=(boxes||[]).filter((x:any)=>x.status==="ready");const selected=requested.length?requested:ready.map((x:any)=>x.id);const selectedReady=ready.filter((x:any)=>selected.includes(x.id));if(!selectedReady.length)throw new Error("Keine ausgewählte Mailbox ist versandbereit. Erst SMTP testen.");const{data:other,error:oe}=await db.from("energy_campaigns").select("*").eq("user_id",userId).eq("status","active").neq("id",id);if(oe)throw oe;for(const x of other||[])await pause(db,x,userId);const pausedIds=ready.filter((x:any)=>!selected.includes(x.id)).map((x:any)=>x.id);if(pausedIds.length){const r=await db.from("energy_mailboxes").update({status:"paused",updated_at:new Date().toISOString()}).eq("user_id",userId).eq("status","ready").in("id",pausedIds);if(r.error)throw r.error}const now=new Date().toISOString();const patch:any={status:"active",completed_at:null,next_send_at:now,mailbox_ids:selected,lead_filter:{...cleanFilter(c),mailboxes_paused_by_campaign:pausedIds},updated_at:now};if(!c.started_at)patch.started_at=now;const ur=await db.from("energy_campaigns").update(patch).eq("id",id).eq("user_id",userId);if(ur.error)throw ur.error;return{ok:true,videoReadiness:vr,worker:kickNow?await kick(db,String(c.tracking_base_url||"")):null}}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:H});if(req.method!=="POST")return reply({error:"Method not allowed"},405);try{const u=await user(req);if(!u)return reply({error:"Nicht autorisiert"},401);const b=await req.json().catch(()=>({}));const action=String(b?.action||"load");const db=admin();if(action==="load")return reply({ok:true,...await loadAll(db,u.id)});if(action==="preview")return reply({ok:true,...await preview(db,u.id,b?.audience||{})});if(action==="create")return reply({ok:true,...await createCampaign(db,u.id,b)});const id=String(b?.id||"");if(!id)return reply({error:"Kampagnen-ID fehlt"},400);const c=await owned(db,id,u.id);if(!c)return reply({error:"Kampagne nicht gefunden"},404);if(action==="start"||action==="resume")return reply(await start(db,u.id,id,true));if(action==="run"){if(c.status!=="active")return reply({error:"Kampagne ist nicht aktiv"},409);return reply({ok:true,worker:await kick(db,String(c.tracking_base_url||""))})}if(action==="pause"){await pause(db,c,u.id);return reply({ok:true})}if(action==="delete"){if(c.status==="active")return reply({error:"Aktive Kampagne zuerst pausieren"},409);await restoreMailboxes(db,c,u.id);const r=await db.from("energy_campaigns").delete().eq("id",id).eq("user_id",u.id);if(r.error)throw r.error;return reply({ok:true})}return reply({error:"Unbekannte Aktion"},400)}catch(e){return reply({error:e instanceof Error?e.message.slice(0,900):"Interner Fehler"},500)}});