/* Shared OSS adapter. Upstream: firecrawl/firecrawl JS SDK 4.39.0, MIT. */
export type FirecrawlDocument={markdown?:string;html?:string;links?:string[];metadata?:Record<string,unknown>;[key:string]:unknown};
export type FirecrawlScrapeOptions={formats?:Array<string|Record<string,unknown>>;onlyMainContent?:boolean;timeout?:number;blockAds?:boolean;removeBase64Images?:boolean;maxAge?:number;[key:string]:unknown};
const MAX_RESUMES=5,MAX_WAIT=20*60*1000,MIN_DELAY=5000,MAX_DELAY=10*60*1000;
function base(){return(process.env.FIRECRAWL_BASE_URL||"https://api.firecrawl.dev").replace(/\/$/,"")}
function key(){const value=process.env.FIRECRAWL_API_KEY?.trim();if(!value)throw new Error("FIRECRAWL_API_KEY fehlt.");return value}
export function firecrawlConfigured(){return Boolean(process.env.FIRECRAWL_API_KEY?.trim())}
async function call<T>(path:string,init:RequestInit,timeoutMs=330000):Promise<T>{const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(`${base()}${path}`,{...init,signal:c.signal,headers:{authorization:`Bearer ${key()}`,"content-type":"application/json",...(init.headers||{})},cache:"no-store"});const body=await r.json().catch(()=>({})) as Record<string,unknown>;if(!r.ok){const e=new Error(String(body.error||body.message||`Firecrawl HTTP ${r.status}`)) as Error&{status?:number;code?:string;details?:unknown;retryAfter?:string|null};e.status=r.status;e.code=typeof body.code==="string"?body.code:undefined;e.details=body.details;e.retryAfter=r.headers.get("retry-after");throw e}return body as T}finally{clearTimeout(t)}}
function resumeDelay(error:unknown){const e=error as{status?:number;code?:string;details?:{state?:string;retryAfterSeconds?:number};retryAfter?:string|null};if(e.status!==408||e.code!=="SCRAPE_TIMEOUT"||e.details?.state!=="processing_continues")return undefined;const h=Number(e.retryAfter),s=typeof e.details.retryAfterSeconds==="number"?e.details.retryAfterSeconds:Number.isFinite(h)?h:60;return Math.min(MAX_DELAY,Math.max(MIN_DELAY,s*1000))}
export async function scrapeWithFirecrawl(url:string,options:FirecrawlScrapeOptions={}):Promise<FirecrawlDocument>{if(!url.trim())throw new Error("URL cannot be empty");let resumes=0,waited=0;while(true){try{const result=await call<{success:boolean;data?:FirecrawlDocument;error?:string}>("/v2/scrape",{method:"POST",body:JSON.stringify({url:url.trim(),...options})},Math.max(typeof options.timeout==="number"?options.timeout:300000,300000)+30000);if(!result.success)throw new Error(result.error||"Firecrawl scrape failed");return result.data||{}}catch(error){const delay=resumeDelay(error);if(delay!==undefined&&resumes<MAX_RESUMES&&waited+delay<=MAX_WAIT){resumes++;waited+=delay;await new Promise(r=>setTimeout(r,delay));continue}throw error}}}
