import { NextRequest, NextResponse } from "next/server";

export const dynamic = "force-dynamic";

type Intent="Transactional"|"Commercial"|"Local"|"Informational"|"Mixed";
const COMMERCIAL=/\b(kosten|preis|preise|angebot|anbieter|vergleich|beste|agentur|service|dienstleister|beratung)\b/i;
const TRANSACTIONAL=/\b(kaufen|buchen|bestellen|termin|anfragen|angebot|beauftragen|mieten|abschließen)\b/i;
const LOCAL=/\b(in der nähe|nähe|near me|berlin|hamburg|münchen|köln|frankfurt|stuttgart|düsseldorf|dresden|leipzig|nürnberg|hannover|bremen|dortmund|essen)\b/i;
const INFO=/\b(was|wie|warum|welche|welcher|ratgeber|tipps|anleitung|erklärung|definition)\b/i;
function intent(k:string):Intent{if(TRANSACTIONAL.test(k))return"Transactional";if(LOCAL.test(k))return"Local";if(COMMERCIAL.test(k))return"Commercial";if(INFO.test(k))return"Informational";return"Mixed";}
function opportunity(k:string,i:Intent){const words=k.trim().split(/\s+/).length;const a=i==="Transactional"?38:i==="Commercial"?32:i==="Local"?30:i==="Mixed"?20:12;const b=Math.min(24,Math.max(0,(words-1)*5));const c=/kosten|preis|angebot|anbieter|vergleich|buchen|agentur|dienstleister|beratung/i.test(k)?20:6;return Math.min(96,24+a+b+c);}
async function suggest(q:string,hl:string,gl:string){const u=new URL("https://suggestqueries.google.com/complete/search");u.searchParams.set("client","firefox");u.searchParams.set("q",q);u.searchParams.set("hl",hl);u.searchParams.set("gl",gl);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),6500);try{const r=await fetch(u,{cache:"no-store",signal:controller.signal,headers:{"user-agent":"Walkenhorst-Radar/1.0"}});if(!r.ok)return[] as string[];const d=await r.json() as unknown;return Array.isArray(d)&&Array.isArray(d[1])?d[1].filter((x):x is string=>typeof x==="string"):[];}catch{return[] as string[];}finally{clearTimeout(timer);}}
export async function POST(req:NextRequest){try{const p=await req.json().catch(()=>({}));const keyword=String(p?.keyword||"").trim().slice(0,120);if(keyword.length<2)return NextResponse.json({error:"Bitte ein Keyword eingeben."},{status:400});const hl=String(p?.language||"de").replace(/[^a-z-]/gi,"").slice(0,8)||"de";const gl=String(p?.country||"DE").replace(/[^a-z]/gi,"").slice(0,2).toUpperCase()||"DE";const mods=[""," kosten"," preis"," anbieter"," förderung"," gewerbe"," in der nähe"," vergleich"];const batches=await Promise.all(mods.map(m=>suggest(`${keyword}${m}`,hl,gl)));const unique=Array.from(new Set([keyword,...batches.flat()].map(x=>x.trim()).filter(Boolean))).slice(0,70);const ideas=unique.map(keyword=>{const i=intent(keyword);return{keyword,intent:i,opportunity:opportunity(keyword,i)}}).sort((a,b)=>b.opportunity-a.opportunity||a.keyword.localeCompare(b.keyword));return NextResponse.json({seed:keyword,ideas,exactVolumeAvailable:false,note:"Exaktes Suchvolumen wird erst mit Google Ads Keyword Planning ergänzt und nicht geschätzt."},{headers:{"cache-control":"no-store"}});}catch{return NextResponse.json({error:"Keyword-Recherche fehlgeschlagen."},{status:500});}}
