import { NextRequest } from "next/server";
import { lookup } from "node:dns/promises";
import net from "node:net";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const USER_AGENT = "Mozilla/5.0 (compatible; WalkenhorstEnergyRadar/1.0; +https://www.walkenhorst-pv.de/)";
function private4(ip:string){const p=ip.split(".").map(Number);if(p.length!==4||p.some(Number.isNaN))return true;const[a,b]=p;return a===10||a===127||a===0||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===100&&b>=64&&b<=127)||a>=224;}
function private6(ip:string){const v=ip.toLowerCase();return v==="::1"||v==="::"||v.startsWith("fc")||v.startsWith("fd")||/^fe[89ab]/.test(v);}
async function assertPublic(url:URL){const host=url.hostname.toLowerCase();if(host==="localhost"||host.endsWith(".local")||host.endsWith(".internal"))throw new Error("blocked");const literal=net.isIP(host);if(literal===4&&private4(host))throw new Error("blocked");if(literal===6&&private6(host))throw new Error("blocked");if(!literal){const records=await lookup(host,{all:true,verbatim:true});if(!records.length)throw new Error("dns");for(const r of records){if(r.family===4&&private4(r.address))throw new Error("blocked");if(r.family===6&&private6(r.address))throw new Error("blocked");}}}
function sanitize(html:string,base:string){let out=html.slice(0,2_000_000);out=out.replace(/<script\b[^>]*>[\s\S]*?<\/script\s*>/gi,"").replace(/<iframe\b[^>]*>[\s\S]*?<\/iframe\s*>/gi,"").replace(/<object\b[^>]*>[\s\S]*?<\/object\s*>/gi,"").replace(/<embed\b[^>]*\/?\s*>/gi,"").replace(/<form\b[^>]*>[\s\S]*?<\/form\s*>/gi,"").replace(/<meta[^>]+http-equiv=["']?(?:refresh|content-security-policy)[^>]*>/gi,"").replace(/\son[a-z]+\s*=\s*(["']).*?\1/gi,"").replace(/\son[a-z]+\s*=\s*[^\s>]+/gi,"");const head=`<base href="${base.replace(/"/g,"&quot;")}"><meta name="referrer" content="no-referrer"><style>html{scroll-behavior:auto!important}body{pointer-events:none!important}a,button,input,select,textarea{pointer-events:none!important}</style>`;return /<head[^>]*>/i.test(out)?out.replace(/<head[^>]*>/i,m=>m+head):`<!doctype html><html><head>${head}</head><body>${out}</body></html>`;}

export async function GET(req:NextRequest){const raw=req.nextUrl.searchParams.get("url")||"";let current:URL;try{current=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`);}catch{return new Response("Ungültige URL",{status:400});}if(!["http:","https:"].includes(current.protocol))return new Response("Ungültige URL",{status:400});try{let response:Response|null=null;for(let i=0;i<4;i++){await assertPublic(current);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),9000);try{response=await fetch(current,{redirect:"manual",signal:controller.signal,headers:{"user-agent":USER_AGENT,accept:"text/html,application/xhtml+xml"},cache:"no-store"});}finally{clearTimeout(timer);}if([301,302,303,307,308].includes(response.status)){const loc=response.headers.get("location");if(!loc)break;current=new URL(loc,current);continue;}break;}if(!response?.ok)return new Response("Website konnte nicht geladen werden",{status:502});const type=response.headers.get("content-type")||"";if(!type.includes("text/html")&&!type.includes("application/xhtml+xml"))return new Response("Keine HTML-Seite",{status:415});const len=Number(response.headers.get("content-length")||0);if(len>2_000_000)return new Response("Website zu groß",{status:413});const html=await response.text();return new Response(sanitize(html,current.toString()),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"private, max-age=300","content-security-policy":"default-src 'none'; img-src https: http: data:; style-src https: http: 'unsafe-inline'; font-src https: http: data:; media-src https: http: data:; connect-src 'none'; frame-src 'none'; form-action 'none'; base-uri *;","x-content-type-options":"nosniff","referrer-policy":"no-referrer"}});}catch{return new Response("Vorschau nicht verfügbar",{status:502});}}
